### ISSUE TITLE
Defining a `serverSetup` function without args crashes the server

### ISSUE THREAD

**Issue by infomiho** [wasp-lang/wasp#1035]
### Issue
If the user defines the `serverSetupFn` like this:
```js
export default async function () {
  await github.submit()
  await loadTime.submit({
    url: "https://wasp-lang.dev",
    name: "wasp-lang.dev Load Time"
  })
}
```
the server crashes with the error:
```
src/server.ts(21,21): error TS2554: Expected 0 arguments, but got 1.
```

### Possible solution
If the user changed *his* function as:
```js
export default async function (context) {
```
it would work.

This makes the newest addition https://github.com/wasp-lang/wasp/pull/1017 a breaking change.

### Making it backwards compatible

If we changed our `server.ts` from:
```ts
await serverSetup(serverSetupFnContext)
```
to
```ts
await (serverSetup as ServerSetupFn)(serverSetupFnContext)
```
it would work 😃

**Comment by Martinsos** [comment]
Just to clarify, above are two solutions depicted: one where users have to add `context`, and one where we better specify the type we expect from serverSetup, so TS knows context is optional, and users don't have to change anything then.

Certainly the second solution is better so let's go with it!

**Comment by shayneczyzewski** [comment]
Ah good catch, thanks @infomiho. I'll add the `as` to cast it. I was wondering why it "worked" when I tested with zero args, but I left the type annotation: `const setup: ServerSetupFn = async () => {}` but yes, without, it would blow up. Using `as` here is a nice trick 👍🏻 thnx
