### ISSUE TITLE
Generator should be responsible for copying migrations/ folder from source to the generated project

### ISSUE THREAD

**Issue by matijaSos** [wasp-lang/wasp#105]
Currently we are doing within db commands, migrate-save and migrate-up, but it might make sense this is actually a responsibility of the generator, since migrations/ can also be considered to be part of a source code.

**Comment by Martinsos** [comment]
We could it the same way we do it for `ext/` directory, by first reading all the files from the dir recursively, and then creating filedrafts for each of them. Or, we could create new type of FileDraft called CopyDirFileDraft (or smth like that) that copies the whole directory.

**Comment by Martinsos** [comment]
@turbodami while simple in the essence, this one might be somewhat harder on the part of figuring out how to do this in Haskell/Wasp, so let's discuss the details of how this could be done after you give it a look.
