### ISSUE TITLE
Ensure consistency between `src/client/tsconfig.json` and `.wasp/out/react-app/src/tsconfig.json`

### ISSUE THREAD

**Issue by sodic** [wasp-lang/wasp#1057]
Moving from `create-react-app` to `vite` caused a discrepancy between our `tsconfig.json` files. This causes incorrect errors inside the IDE.

Specifically, IDE reports errors are not errors at all (i.e., the project compiles fine), while at the same time failing to detect some of the real errors.

One example of a false-positive is an error the IDE reports when you try to access `import.meta` on the frontend:

![image](https://user-images.githubusercontent.com/22752307/225290106-0365e954-f971-48f9-8174-7afb003b689e.png)

We should ensure that the `tsconfig.json` we generate for users is as similar as possible to the `tsconfig.json` file we use to compile their code.

This tweet may be relevant:
https://twitter.com/youyuxi/status/1636551895002255362

**Comment by Zeko369** [comment]
... I have a lot of thoughts/notesFromWaspTesting on this and the whole "tsconfigs that dev sees and that are used to compile are different", should I wait to go over this in person this/next week or try to summarise here?

**Comment by sodic** [comment]
I'd be happy to have a call! One of us can then summarise it here.

**Comment by Martinsos** [comment]
@sodic reminder to summarize this!

**Comment by sodic** [comment]
Main idea: Use the same `tsconfig.json` for both the IDE support and compilation. We haven't initially done this because Wasp-generated code would possibly fail user-defined compiler rules. There are several ways around this:
 - Easy and safe: Read the user's config and extend it with an `include` or `exclude` field that ignores files generated by Wasp (we can read the JSON file, parse it, add what we need, and stringify it)
 - Harder and more unclear: Bundle all Wasp-generated code and use it as a library (this will be explored within the restructuring research)

**Comment by sodic** [comment]
With changes introduced in Wasp 0.12.0 (no separation between client and server code, a single tsconfig per project), this issue became deprecated.
