### ISSUE TITLE
Get rid of an ugly loading message that appears when auth is being processed.

### ISSUE THREAD

**Issue by matijaSos** [wasp-lang/wasp#1076]
Currently, when you use Wasp auth and a user logs in / signs up, the unstyled loading message appears on a blank white screen in the upper left corner.

Can we get rid of that and put something nicer by default, e.g. a spinner?

**Comment by Martinsos** [comment]
"Offending" piece of code: https://github.com/wasp-lang/wasp/blob/20eb9e007a7afbf9a2edf5edde7e20b596f09be0/waspc/data/Generator/templates/react-app/src/auth/pages/createAuthRequiredPage.jsx#L21 .

We should either put something nicer, or a blank screen. Ideally, we would allow customizing it!

**Comment by Martinsos** [comment]
Related discord convo: https://discord.com/channels/686873244791210014/1156236595842785321/1156236595842785321 .

**Comment by Martinsos** [comment]
Dmitry also asked if we could fix this
