### ISSUE TITLE
In our Tailwind docs, mention that you need to restart after adding config files, doesn't work otherwise

### ISSUE THREAD

**Issue by matijaSos** [wasp-lang/wasp#1077]
I was adding tw support to a project so that slowed me a down a bit.

**Comment by LLxD** [comment]
Hey! Was going to do this one since it looked easy enough but it seems it's already done in the new version of the docs hahah, nice work! This probably can be closed, but let me know otherwise 👍 
![image](https://github.com/wasp-lang/wasp/assets/48529975/6580aaaa-b37a-4bb3-b608-eeedd32328b9)

**Comment by infomiho** [comment]
Thanks for the heads up :) check this one instead https://github.com/wasp-lang/wasp/issues/1424
