### ISSUE TITLE
Improve how Wasp handles user accounts

### ISSUE THREAD

**Issue by sodic** [wasp-lang/wasp#1080]
To get Social logins in Wasp (e.g., Google, GitHub), the programmer has to:
1. Add the necessary environment variables.
2. Add the appropriate flag to the Wasp file.
3. Add necessary entities to the Wasp file (i.e., set up an external auth entity).
4. Implement one or two JavaScript functions (depending on how their user model looks like).

Similarly, if they want to use password auth, programmers must ensure their User entity follows a specific structure.

**We want to improve the current setup and make different login methods as frictionless as possible**. I recommend looking at T3's Prisma models for inspiration on how best to approach this.

### Ideas
1. Implement username-and-password as one of the providers.
2. Keep the business logic User (i.e., the entity programmers define in their Wasp file) separate from auth models (i.e., something containing passwords and other login information). We could generate the auth models and allow the programmers to focus on the business logic.

### Questions
A couple of questions that should help with designing the new system:
1. What happens if the User model includes mandatory fields which aren't derivable from the data we get from the external auth provider?
3. How much of the code do users need to change when switching between different providers (username-and-password provider included)?

**Comment by infomiho** [comment]
![image](https://user-images.githubusercontent.com/2223680/227159236-b5eb8f72-8c0c-441d-8ba5-59cd2313946a.png)

Here's some ideas from a brainstorming session a while back.

### Injecting Prisma auth models if not defined explicitly

One of the things we can do for making the auth setup easier is to inject Prisma models as if the user defined them. This way the auth setup becomes much easier (user can not care about the implementation details). 

The tricky part is what happens to the database when the users goes to "turn off Google auth just to test something out" and then we have a problem - do we remove the models (causing a migration) or not?

### If the user wants to keep arbitrary data from providers, we should define e.g. `GoogleData` entity

Another idea we had was to use custom models to store provider data, that could be used like this:
```
auth: {
  methods: {
    google: {
      dataEntity: GoogleData
    }
  },
  onAuthFailedRedirectTo: "/"
},

entity GoogleData {
  id @id @unique
  profilePicture String
}
```

**Comment by sodic** [comment]
Nice graph, thanks for including it.

> If the user wants to keep arbitrary data from providers, we should define e.g. GoogleData entity

I think Wasp should know about these models ahead of time. More precisely, we should "hardcode" the most popular auth providers' models into Wasp and automatically set everything up if the users decide to use those providers. Of course, we could also allow Users to override (and maybe even extend) them, as your example shows.

> The tricky part is what happens to the database when the users goes to "turn off Google auth just to test something out" and then we have a problem - do we remove the models (causing a migration) or not?

This is tricky, yes. We can think about introducing aggressiveness levels for migrations.

The main question we still need to think about is:
> What happens if the User model includes mandatory fields which aren't derivable from the data we get from the external auth provider?

For example, what if the `User` entity in your graph above contains a mandatory "age" field that Google/Github/etc don't know about.

**Comment by sodic** [comment]
> so not every reader of this comment has to go and check it out, also possibly coming to different conclusions?

I didn't do it :smile: 

That's why the `research` tag is there. The idea is: _whoever takes on this issue should study T3's models._
