### ISSUE TITLE
Not being on Windows it's hard for me to dig super deep into this, but I'm curious if maybe composer isn't installed on the same drive as your theme? I see this in your debug log: 

### ISSUE THREAD

**Issue by GenuisX** [wasp-lang/wasp#1138]
Not being on Windows it's hard for me to dig super deep into this, but I'm curious if maybe composer isn't installed on the same drive as your theme? I see this in your debug log:
```
9696 error path D:\#Websites\christmas-music\app\public\wp-content\themes\christmas-music
9697 error command failed
9698 error command C:\Windows\system32\cmd.exe /d /s /c composer install --quiet && npm run build
```

And to me, it looks like your theme is installed on the D drive but the error may be coming from the C drive? (doing a quick search, there are folks who have had a similar issue: https://github.com/composer/composer/issues/8680 and https://stackoverflow.com/questions/24664269/install-composer-for-windows-on-d-drive).

I also wonder if the `#` in your path causes some kind of parsing issue. Have you used the theme without issue on the same drive with the same `\#Websites\` path before?

Thanks!

_Originally posted by @coreymcollins in https://github.com/WebDevStudios/wd_s/issues/760#issuecomment-944320561_

Yep I'm rfc 1918: all drives AGO

**Comment by infomiho** [comment]
Looks like spam, check if your account was hacked
