### ISSUE TITLE
Tell us more about you Adelia Dione Oates someone used my social security number to open a pay pal business account under Google LLC...help me call the FBI please 

### ISSUE THREAD

**Issue by GenuisX** [wasp-lang/wasp#1139]
https://www.sandbox.paypal.com/bizsignup/#/personalInfo

**Comment by GenuisX** [comment]
Urgency I really need your assistance the police where I live won't help because they were payed off

**Comment by infomiho** [comment]
Looks like spam, check if your account was hacked
