### ISSUE TITLE
blockpg-dock.safezone.mcafee.com

### ISSUE THREAD

**Issue by GenuisX** [wasp-lang/wasp#1153]
http://blockpg-dock.safezone.mcafee.com/blockpage/?ref=72297164f0cae5981443206c7ce3d2d4

**Comment by GenuisX** [comment]
> http://blockpg-dock.safezone.mcafee.com/blockpage/?ref=72297164f0cae5981443206c7ce3d2d4

Where's the joint account for end-users

**Comment by infomiho** [comment]
Closing as spam
