### ISSUE TITLE
Allow users to add postgres extensions, e.g. pgvector

### ISSUE THREAD

**Issue by vincanger** [wasp-lang/wasp#1222]
Currently there is no way to extend the configuration of the `schema.prisma` file, specifically for adding `previewFeatures` such as `postgresqlExtensions` in order to use pgvector:

```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
  shadowDatabaseUrl = env("SHADOW_DATABASE_URL")
  extensions = [pgvector(map: "vector", schema: "extensions")]
}

generator client {
  provider = "prisma-client-js"
  output = env("PRISMA_CLIENT_OUTPUT_DIR")
  previewFeatures = ["postgresqlExtensions"]
}
```
(Side note: if developing with a Supabase DB in the cloud, we need to create a second "shadow" database which Prisma creates and drops each time we `migrate dev` in order to compare changes and detect drift. It would be nice to add the ability to add a SHADOW_DATABASE_URL env var, as well)

**Comment by Martinsos** [comment]
Related: #1224 , #1357

**Comment by infomiho** [comment]
@vincanger can you expand on the shadow db behaviour? Is this specific to Supabase? Do you know why it's needed?

I would create a separate issue for this if we want to tackle it.

**Comment by infomiho** [comment]
Done in #2035
