### ISSUE TITLE
migrate-dev is not working with Prisma unsupported fields 

### ISSUE THREAD

**Issue by maksim36ua** [wasp-lang/wasp#1224]
Prisma breaks if you'll add an unsupported field to your Wasp entity

**Steps to reproduce**
1. Create Postgres DB (I'm using Fly.io)
2. Install [pgvector](https://github.com/pgvector/pgvector) extension  

How to install pgvector on Fly.io
```
fly ssh console -a <app-name> -C "apt install git"
fly ssh console -a <app-name> -C "git clone --branch v0.4.1 https://github.com/pgvector/pgvector.git"
fly ssh console -a <app-name> -C "apt install make"
fly ssh console -a <app-name> -C "apt install gcc"
fly ssh console -a <app-name> -C "apt install postgresql-server-dev-14"
fly ssh console -a <app-name> -C "make -C /pgvector"
fly ssh console -a <app-name> -C "make install -C /pgvector"
```
3. Create a Wasp entity that uses the `vector` field
```
entity Entity {=psl
  id              Int     @id @default(autoincrement())
  vector          Unsupported("vector (1536)")
psl=}
```

4. Perform migration via `wasp db migrate-dev`
5. Change any entity in the .wasp file and try to run `wasp db migrate-dev` again

**Expected behavior**
Wasp creates a new migration file and applies it successfully

**Actual behavior**
While trying to re-apply the previous migration (that is already applied to the DB), you'll get an error message:

```
Migration `20230527082150_init` failed to apply cleanly to the shadow database. 
Error:
db error: ERROR: type "vector" does not exist
   0: migration_core::state::DevDiagnostic
             at migration-engine/core/src/state.rs:269
```
             
Despite the `vector` type present in DB

![image](https://github.com/wasp-lang/wasp/assets/10496082/f4ebc088-47c1-48b4-be53-74c99fdfc83d)

I have no idea how Prisma checks if the actual DB schema is in sync with the migration files. Maybe that's the issue.

**Comment by infomiho** [comment]
This now works, this example app built a few months ago proves it: https://github.com/wasp-lang/ask-the-documents/blob/main/schema.prisma#L22

Deployed here: https://client-production-0be2.up.railway.app/
