### ISSUE TITLE
Add section about custom domains to Fly deployment docs

### ISSUE THREAD

**Issue by shayneczyzewski** [wasp-lang/wasp#1225]
We have had a few people ask about how to setup custom domains on Fly. It would probably be good to have a section on this.

In it, we can show:
- what `flyctl` command to run to add a custom domain
- remind them to update their server `WASP_WEB_CLIENT_URL` envar to the new URL
- anything else that needs to be done

**Comment by Martinsos** [comment]
Do we maybe already have the details somewhere, probably in some answer on Discord? If so would be great to copy paste that here for faster start.

**Comment by shayneczyzewski** [comment]
> Do we maybe already have the details somewhere, probably in some answer on Discord? If so would be great to copy paste that here for faster start.

There may have been some in passing, but if so, it seems those threads were archived.

**Comment by Martinsos** [comment]
@infomiho I believe you solved this just a couple of days ago?

**Comment by infomiho** [comment]
It's live here: https://wasp-lang.dev/docs/deploying#using-a-custom-domain-for-your-app
