### ISSUE TITLE
[Auth] Allow customizing SignUp form with additional fields

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#1233]
Right now, SignUp form offered by Wasp will contain only fields neccessary to do a signup. So for example for email-password login, it will ask for email and password. But if dev also wants to have username, it won't ask for that.

If they want to add e.g. username also, they can't at the moment. They need to create a second, separate step, where user can specify username and other stuff, but at that point sign up already happened. Or they could write their own sign up form and use our signup action, but it feels a bit bad to drop the whole form just to add one field and now you have to write your own.

We had a couple of people already ask for this.

What we could do is allow them to specify additional fields to have on the very signup form. Or, maybe provide just a bit lower-level API, but not immediately drop to "here is action and that is it". So, we need a way for them to customize these fields without too much work. This is a DX challenge, but I am sure we can come up with a couple of solutions and evaluate them.

Here is relevant Discord chat: https://discord.com/channels/686873244791210014/1115305238442823751/1115305238442823751 .

**Comment by infomiho** [comment]
Closed with https://github.com/wasp-lang/wasp/pull/1395
