### ISSUE TITLE
Disallow duplicate declaration names

### ISSUE THREAD

**Issue by infomiho** [wasp-lang/wasp#1234]
While working on the `crud` feature, I've noticed that if you declare two `crud`s with the same name, the analyzer will allow it.

The generator then fails due to "duplicate file draft file names" which is just a symptom. 

```
Internal Wasp error (bug in compiler):
  FileDraft destination paths are not unique! Duplicates include:
  Left (RelFile "server/src/crud/tasks.ts" NoPrefix)
  Left (RelFile "server/src/routes/crud/tasks.ts" NoPrefix)
  Left (RelFile "web-app/src/crud/tasks.ts" NoPrefix)

  CallStack (from HasCallStack):
    error, called at src/Wasp/Generator/WriteFileDrafts.hs:72:48 in waspc-0.10.6-inplace:Wasp.Generator.WriteFileDrafts
``` 

We should ideally handle this head on by not allowing duplicate declaration names.

**Comment by Martinsos** [comment]
I believe this is the same problem that is routes to have same names: https://github.com/wasp-lang/wasp/issues/579
