### ISSUE TITLE
Tailwind not working

### ISSUE THREAD

**Issue by cdmoss** [wasp-lang/wasp#1249]
**Describe the bug**
After I add `postcss.config.cjs` and `tailwind.config.cjs` to the root of my project with their respective appropriate configs found [here](https://wasp-lang.dev/docs/integrations/css-frameworks), and added 
```
@tailwind base;
@tailwind components;
@tailwind utilities;
```
to `./src/client/Main.css`, tailwind classes still don't seem to apply. 

I started the project with the todo-ts template.

tailwind.config.cjs:
```
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [require("daisyui")],
};
```

postcss.config.cjs:
```
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
```

MainPage.tsx:
```
import React from "react";

export function MainPage() {
  return <span className="text-fuchsia-600">hello</span>;
}
``` 

My directory:
![my directory](https://github.com/wasp-lang/wasp/assets/40777533/f6cd501d-0753-49d8-98e4-c81a8b4b0b24)

Output:
![image](https://github.com/wasp-lang/wasp/assets/40777533/9b3c387b-a3af-4417-a667-672e929996c1)

**Desktop (please complete the following information):**
 - Fedora 37
 - Firefox 114.0
 - Wasp 0.10.6

Edit: add missing wasp version

**Comment by Martinsos** [comment]
Just a quick stab: could it be this: https://github.com/wasp-lang/wasp/issues/1077 ?
Meaning that you should restart `wasp start` for changes to be picked up?

**Comment by cdmoss** [comment]
It seems that unfortunately restarting doesn't solve the issue

**Comment by cdmoss** [comment]
Ahh, I caught the problem. I didn't have `Main.css` imported in my `MainPage.tsx` 🤦. It works now.

**Comment by cdmoss** [comment]
It might be useful to add it to docs, I see CRA has it in [theirs](https://create-react-app.dev/docs/adding-a-stylesheet/). But it's a pretty standard react thing that I'm sure many pick up on automatically.
