### ISSUE TITLE
JWT secret must not be hardcoded in the back-end code

### ISSUE THREAD

**Issue by matijaSos** [wasp-lang/wasp#129]
We did this for simplicity and to test how Wasp works, but this must be changed going forward. This value (along with others secret values) should come from some config/env file in an encrypted way. We have to yet determine what is the best way to implement this.

**Comment by matijaSos** [comment]
By Discord user Rob from Webdev:

![Screenshot 2020-11-10 at 13 55 48](https://user-images.githubusercontent.com/1536649/98676963-9ba24b00-235c-11eb-9651-60cd6356e8b3.png)

**Comment by Martinsos** [comment]
It is not hardcoded any more! Now it is read from ENV VAR: JWT_SECRET.
I also created issue https://github.com/wasp-lang/wasp/issues/174 for figuring out if we should generate it automatically in the future.
