### ISSUE TITLE
Todo App Tutorial Step 4 Issue

### ISSUE THREAD

**Issue by pwilson0** [wasp-lang/wasp#1323]
Hi all,

I'm working through the Wasp "TodoApp" tutorial, and reached an error that prevented me from moving forward on this page: https://wasp-lang.dev/docs/tutorials/todo-app/04-creating-tasks

Under the "Invoking the Action on the Frontend" section, there is a try/catch within the handleSubmit function that reads as follows:

```
const handleSubmit = async (event) => {
    event.preventDefault()
    try {
      const target = event.target
      const description = target.description.value
      target.reset()
      await createTask({ description })
    } catch (err: any) {
      window.alert("Error: " + err.message)
    }
  }
```

When I got to this step, the wasp server stopped hosting the page due to a compilation error because type declarations can only be used in TypeScript files. Removing the type as shown below allowed me to proceed.

```
   ...
    } catch (err) {
   ...
```
Hope this helps!

**Comment by Martinsos** [comment]
Thanks @pwilson0 , this must be a leftover! @craigmc08 took care of it!
