### ISSUE TITLE
Prisma errors are shown twice, once by client and once by server

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#1341]

**Comment by Martinsos** [comment]
This happens doing `wasp start`, and it can confuse users quite a bit. Let's fix this.
@sodic might have some ideas about this, as it is probably caused by us having schema in two places at the same time.
Maybe it will be resolved by restructuring?

**Comment by sodic** [comment]
No longer a problem as of Wasp 0.12.0 (Closed by #1604).
