### ISSUE TITLE
Improve fly deployment docs

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#1345]

**Comment by Martinsos** [comment]
I (Martin) had hard time learning about `wasp deploy fly deploy --skip-server` command. In general, I think we could structure the portion of docs that explain deployment to Fly in a more clearly manner, more organized, right now it is a bit messy.

**Comment by infomiho** [comment]
Docs have been improved, but still no mention of `--skip-server` https://wasp-lang.dev/docs/advanced/deployment/cli

**Comment by Martinsos** [comment]
I found this piece of feedback in my notes but I can't remember if it was before or after we restructured docs :D, I will still put it here just in case:

> I found Wasp CLI Fly deployment instructions in our docs too verbose, too much info at once. We should better explain `setup` vs `deploy` steps.
