### ISSUE TITLE
Improve env vars docs

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#1351]
- [x] Explain in general what env vars are.
- [x] Document how to import them from client (import.meta.env) vs server.
- [x] Explain .env files are only for development.
- [x] Explain how are they set in production -> that for the server they are provided via wherever they are hosted, while for the client, they are embedded into the code during the build step, when static files for it are being generated. We don't have this mentioned for the client in the current docs.
- [x] Maybe nice diagram for all this could help? Decision flow?
- [x] Provide specific instructions for deployment to Fly.

**Comment by Martinsos** [comment]
Document how they work with now with Vite (import meta.env).

Also, explain a bit when they are used where -> explain that .server.env and .client.env are used only during the development, and explain how are then env vars used during production -> that for the server they are provided via wherever they are hosted, while for the client, they are embedded into it during the build step, when static files for it are being generated. I nice diagram could work well here, explaining these concepts simply.

Maybe also explain a bit in general what are env vars about, what is the idea behind them, what should they be used for, ... . So similar like for other features, explain this concept in general first, for all web apps, then go into Wasp specifics.

**Comment by Martinsos** [comment]
We don't mention anywhere in the docs how to set client env vars for production!

We do mention how to do it for the server vars, but we don't for client vars -> ok, I do think we mention how to set them when building client manually, but it is not clear at all how to do it for example when using `wasp deploy fly deploy`.

We should document this nicely.

It should be very clear how each side of env vars is provided during deployment vs production, for be it client or server.

**Comment by Martinsos** [comment]
Here is a conversation about it:
https://discord.com/channels/686873244791210014/1105217201331523724/1105217201331523724

**Comment by infomiho** [comment]
Solved here: https://wasp-lang.dev/docs/project/env-vars
