### ISSUE TITLE
Client side env vars are getting loaded from .env.server?

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#1354]
We had users report that they managed to import env vars to the client by putting them into .env.server. That sounds weird, I don't think that should be happening! We should check that out.

Check convo here: https://discord.com/channels/686873244791210014/1105217201331523724/1105217201331523724 .

**Comment by Martinsos** [comment]
Connected to https://github.com/wasp-lang/wasp/issues/1036 .

**Comment by infomiho** [comment]
Fixed by https://github.com/wasp-lang/wasp/pull/1391
