### ISSUE TITLE
MacOS wasp command line detects latest NodeJS version but still throws Node requirement error

### ISSUE THREAD

**Issue by thisistaimur** [wasp-lang/wasp#1396]
**Describe the bug**
Wasp commands after installations on MacOS throw "Node requirement not met" even though it detects the correct Node version (see screenshot below).

**To Reproduce**
Install Wasp using (in Terminal):

`curl -sSL https://get.wasp-lang.dev/installer.sh | sh
#run any wasp command
wasp completion
`

**Expected behavior**
should run the Wasp command. 

**Screenshots**

<img width="922" alt="Screenshot 2023-08-20 at 16 26 50" src="https://github.com/wasp-lang/wasp/assets/59065240/ac6eabf1-caa5-4728-9994-a59587c0883f">

**Desktop (please complete the following information):**
 - OS: MacOS ventura (13.5)
 - Node: 20.5.1

**Comment by infomiho** [comment]
Read the error message one more time :)

Wasp depends on the latest Node.js LTS version which is Node.js 18 at the moment. Read more about this and how to set up nvm: https://wasp-lang.dev/docs/quick-start#requirements

**Comment by thisistaimur** [comment]
Typical. Thank you!
