### ISSUE TITLE
Installation using Homebrew

### ISSUE THREAD

**Issue by bashovski** [wasp-lang/wasp#140]
**Is your feature request related to a problem? Please describe.**
It'd be also very good to have a very simple installation process for MacOS. The curl command from the docs is fine, although users may need to move the executable to a directory such as ```/usr/local/bin```, so the executable can be reached.

By default, the executable is being placed inside user's ```./local/bin``` dir, which is still okay, but for the vast majority of MacOS users, there could be an installation process involving Homebrew.

The error a MacOS user would most-likely receive is:

```shell script
WARNING: It looks like '/Users/bashovski/.local/bin' is not on your PATH! You will not be able to invoke wasp from the terminal by its name.
-e   You can add it to your PATH by adding following line into your profile file (~/.profile or ~/.zshrc or ~/.bash_profile or some other, depending on which shell you use):
-e   export PATH=$PATH:/Users/bashovski/.local/bin
```

This is fine as long as the user additionally runs another command to create/move a copy of an executable here:
```/usr/local/bin```

A simple Homebrew config would be enough and would resolve that.

Later, it'd be nice to apply for the binary approval from Homebrew by creating a PR in their official repository once (somewhat) stable release is ready for use.

**Describe the solution you'd like**

I suggest on creating a repository which would include configuration for Homebrew. Automatically, the users would be able to fetch and install a tap.

**Describe alternatives you've considered**
I didn't really think of any other alternatives, maybe a separate script would be also sufficient.

**Additional context**
After discussing this with @Martinsos , I'd be able to complete this task as long as you have the homebrew-wasp repository created. I can provide a PR with fully-working configuration (which is sufficient for the tap to be publicly available).

**Comment by Martinsos** [comment]
Awesome, thanks for this, all sounds good to me!
Here is repo: https://github.com/wasp-lang/homebrew-wasp -> create a PR and we will merge it.
Closing this issue!
