### ISSUE TITLE
Write a docs writing style guide

### ISSUE THREAD

**Issue by infomiho** [wasp-lang/wasp#1402]
We want to write a style guide for our docs similar to those of Vue and Prisma. 

We should use the @sodic's  Meet presentation as a source of inspiration as well.

### Implementation 

Ideally, it's a short Markdown doc somewhere in the `docs` dir.

We should reference it in the PR template as well.

**Comment by ayan-joshi** [comment]
@Martinsos I would like to work on it can u assign

**Comment by infomiho** [comment]
This was completed 👍  https://github.com/wasp-lang/wasp/blob/main/web/docs/writingguide.md
