### ISSUE TITLE
"Take the Tutorial" button redirecting to a Page Not found

### ISSUE THREAD

**Issue by IMPranshu** [wasp-lang/wasp#1416]
**Describe the bug**
When I click the take the tutorial button it takes me to a webpage where I am getting a "Page Not found" message.

<img width="1506" alt="Screenshot 2023-08-29 at 1 36 19 PM" src="https://github.com/wasp-lang/wasp/assets/43396684/82d45e50-1e75-470b-be55-da6aa6977343">
<img width="1506" alt="Screenshot 2023-08-29 at 1 36 27 PM" src="https://github.com/wasp-lang/wasp/assets/43396684/9169bce5-0ea0-41e4-b416-4831b449af57">

**To Reproduce**
1. In the CLI run `wasp new test`
2. Then run `cd test`
3. Then run `wasp start`
4. Click the "Take the tutorial" button in the opened browser window.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Brave

**Comment by martinovicdev** [comment]
I suppose that the best thing to do is link to the https://wasp-lang.dev/docs/tutorial/project-structure section since the first step of the tutorial (creating the project) is already done. 

If this idea works, I can give solving this issue a go.
