### ISSUE TITLE
Make sure our visualisations in the docs work in dark mode

### ISSUE THREAD

**Issue by infomiho** [wasp-lang/wasp#1424]
For example:

<img width="881" alt="Screenshot 2023-08-31 at 10 24 08" src="https://github.com/wasp-lang/wasp/assets/2223680/95720a16-a6ce-440c-811b-3776d7d04aa3">

We should consider:
1. Adding a white background
2. Using SVGs with dynamic colors

**Comment by ArslanYM** [comment]
Id like to take this issue to get a basic understanding of the codebase.

**Comment by infomiho** [comment]
Go for it! The docs are located in the `web` folder and you can start with `npm run start` :)

**Comment by Martinsos** [comment]
The one from the example got fixed by #1456 !

**Comment by Martinsos** [comment]
My quick superficial check of docs said that we don't have any more problematic images, so I am closing this issue!
