### ISSUE TITLE
Decide how to handle and import full-stack packages

### ISSUE THREAD

**Issue by sodic** [wasp-lang/wasp#1432]
Wasp provides a uniform full-stack interface for some functionalities. For example, importing and using Queries and Actions looks the same in both backend and frontend code. However, what happens in runtime is a different story entirely:
1. Importing and using `@wasp/queries/someQuery` on the backend resolves to a Wasp-generated decorator (which then calls the User's query with the appropriate context).
2. Importing and using `@wasp/queries/someQuery` on the frontend resolves to an RPC call to the server.

In essence, the import and the API are the same, but the runtime is completely different.

TODO(filip): finish, check personal notes.

**Comment by Martinsos** [comment]
> We decided that, for the time being, we won't be doing anything special with full-stack packages.
> 
> The restructuring will sacrifice the uniform calling interface in favor of something like (the exact import locations are still TBD):
> 
> * Importing from `@wasp/client/queries` on the client.
> * Importing from `@wasp/server/queries` on the server.
> 
> This solution implies that jumping to the definitions of Actions and Queries won't take users to their implementations, but will instead take them to the generated code (as is currently the case).
> 
> Note: @Martinsos found that perhaps we can point to the right location in the comments, and even have it as a clickable link in VS Code.

Or have TS LS plugin that takes them to the right place.

**Comment by sodic** [comment]
Further discussion moved to #1847
