### ISSUE TITLE
Add support for sockets (client <-> server)

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#144]
In case users want to react in live to the events happening on server, we should add support for listening to a server socket.

It would be interesting to figure out how this fits with the Operations, if there is some kind of synergy or if sockets would be a separate mechanism.

**Comment by Martinsos** [comment]
Per @shayneczyzewski's suggestion, what if we provided support in Wasp for cache invalidation/updates from the server side? Would that how this would fit into Operations?

**Comment by sodic** [comment]
We've had this for some time, so I'm closing.

> what if we provided support in Wasp for cache invalidation/updates from the server side? Would that how this would fit into Operations?

This is interesting and covered here: https://github.com/wasp-lang/wasp/issues/1454#issue-1917224953
