### ISSUE TITLE
Missing `commander` npm package installation when deploying wasp app?

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#1467]
User said:

> What I meant was the output at .wasp was missing the commander package
Which was a requirement to deploy
So I had to cd into /.wasp/out/server and npm i commander

> this was for the embeddings starter, I hadn't made any changes myself

We should investigate why this happens, maybe `commander` is a dependency that is not listed? Question is also if this is a problem with Wasp in general or with embeddings starter?

Discord convo: https://discord.com/channels/686873244791210014/1158758774731972648/1158799069452435556 .

**Comment by TheOjasSingh** [comment]
Hi I want to work on this issue

**Comment by Martinsos** [comment]
Hey @TheOjasSingh , sure, give it a go if you wish! Let me know if you need any help.

**Comment by Martinsos** [comment]
Sure! Check out https://github.com/wasp-lang/wasp/blob/main/CONTRIBUTING.md , and then https://github.com/wasp-lang/wasp/blob/main/waspc/README.md .

**Comment by TheOjasSingh** [comment]
I discovered that the commander was not included in the npm package, causing it to be missing during the deployment of the Wasp app.

**Comment by Martinsos** [comment]
> I discovered that the commander was not included in the npm package, causing it to be missing during the deployment of the Wasp app. So adding the commander in the npm package will work fine.

Uf sorry it seems I dropped the ball on this one -> ok, but can you give more context? Which part of Wasp needs commander? To which npm package did you add it?

**Comment by Martinsos** [comment]
This hasn't happened again, possibly a false alarm, so closing it for now.
