### ISSUE TITLE
Make generated log in / sign up optional / flexible

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#147]
Right now, if user is using Auth, we automatically generate login and signup page, which means: routes, pages, actions.
Routes are "signup" and "login".

However, right now you can't turn those off! Which means, you can't use signup and login routes for your own purposes, and you also can't remove generated pages from them. We should allow more flexibility.

Some options:
1. Provide a boolean property in `auth` declaration with which you can turn off automatic generation of auth pages.
2. Instead of generating routes + pages + actions, generate pages + actions and let user use the pages if they want (by declaring route to them in .wasp file).

I like the second option better, although first option might be more straightforward for now.

**Comment by matijaSos** [comment]
Another thing -> currently signup and login pages redirect user to "/" route after authentication. We should also make that location flexible, so developer can specify where should user be redirected.

**Comment by matijaSos** [comment]
This was implemented, just forgot to close the issue! We are not generating auth routes and pages anymore, but just the forms which dev can then incorporate wherever they want.
