### ISSUE TITLE
Remove old import from documentation

### ISSUE THREAD

**Issue by vincanger** [wasp-lang/wasp#1470]
we no longer export `logoUrl` from auth helpers, so it needs to be removed from our docs:

![image](https://github.com/wasp-lang/wasp/assets/70215737/d2e48f69-f51f-4182-ac82-102d22d176bd)

**Comment by MSaiKiran9** [comment]
hi i'm new to this repository can i work on this issue?

**Comment by AJBrownson** [comment]
Hi @vincanger I would like to work on this issue
Can it be assigned to me?

**Comment by vincanger** [comment]
@AJBrownson @sivangbagri @gmirzayev -- check out our other Documentation issues or our Starter Templates if you're looking for a javascript-friendly contribution: https://github.com/wasp-lang/starters

**Comment by HeetVekariya** [comment]
Is this issue still open, then i would like to work on this.

**Comment by Martinsos** [comment]
This just got fixed yesterday! Closing!
