### ISSUE TITLE
Installation failed: There is no wasp version 0.11.5

### ISSUE THREAD

**Issue by vaibhavpnimkar** [wasp-lang/wasp#1472]
I am trying to install wasp lang on my ubuntu machine 
i am getting this ****WARNING**:Failed to open the file /tmp/tmp.Fha3V3zIF4/wasp-linux-x86_64.tar.gz:** 
more details:Warning: No such file or directory
  0 13.2M    0 21759    0     0   8375      0  0:27:38  0:00:02  0:27:36 26567
curl: (23) Failure writing output to destination
Installation failed: There is no wasp version 0.11.5

I have node js version 18.18.0 installed on my machine still facing issues can somebody help

**Comment by Martinsos** [comment]
This is almost certainly an issue with how curl is installed on your ubuntu, check out here https://github.com/wasp-lang/wasp/issues/1455#issuecomment-1739549085 for solution!
