### ISSUE TITLE
Prettier formatting, .prettierignore, import orders

### ISSUE THREAD

**Issue by martinovicdev** [wasp-lang/wasp#1489]
A suggestion for improving the code readability in the web page/docs section of the project: 

1. Create a .prettierignore file, ignoring files such as package.json, .MD files, etc. so they don't get formatted automatically.
2. Add plugin for ordering imports, so they are consistent (for example https://github.com/IanVS/prettier-plugin-sort-imports)
3. Add automatic Tailwind class sorting - https://tailwindcss.com/blog/automatic-class-sorting-with-prettier
4. _Optional:_ Add additional parameters to prettier.config.js, such as `endOfLine: 'lf'`, `tabWidth: 2,` to keep the code more consistent between different OS's and different configurations
5. Run the `prettier --write .` so the whole codebase is evenly formatted

Current situation is that we have the prettier.config.js file set up, but whole project isn't formatted yet. This could cause a bit of confusion for new contributors + we would want the code to be evenly formatted anyways.

I'd be happy to do it myself.

**Comment by heysagnik** [comment]
I want to work on this issue

**Comment by Martinsos** [comment]
@martinovicdev that sounds good, and if you want to go for it that would be amazing! Should we also make prettier a part of CI, or have it as a git commit hook, or something like that, to ensure it is always applied?

**Comment by martinovicdev** [comment]
Thanks @Martinsos I'll do it 😄. 

I would suggest putting code formatting (Prettier) in a pre-commit hook and/or inside a check for PR, where it would fail if docs aren't formatted as they should be.
I think that having it inside CI wouldn't be ideal, as code changes could potentially happen and you have no control over them.

**Comment by Martinsos** [comment]
> Thanks @Martinsos I'll do it 😄.
> 
> I would suggest putting code formatting (Prettier) in a pre-commit hook and/or inside a check for PR, where it would fail if docs aren't formatted as they should be. I think that having it inside CI wouldn't be ideal, as code changes could potentially happen and you have no control over them.

That makes sense to me, sounds good!
