### ISSUE TITLE
Remove createNewUser() function

### ISSUE THREAD

**Issue by matijaSos** [wasp-lang/wasp#150]
Since we our now hashing password within Prisma's middleware, this function is not doing anyting, except wrapping a call of `prisma.user.create()`. We can remove it and replace it with direct invocations of prisma client.

**Comment by thvu11** [comment]
Hi @matijaSos , I'd like to grab this, look quite straight forward for me to explore the code base.

**Comment by Martinsos** [comment]
@thvu11 hey that would be great :)!
I agree, it should be an easy task to get started.
Here is a short introduction I gave to another contributor just a day or two ago, I believe it is also applicable to you as an advice to get started: https://github.com/wasp-lang/wasp/issues/168#issuecomment-772627514 .
