### ISSUE TITLE
[Suggestion] : Change 'Twitter' icon on home page to 'X'

### ISSUE THREAD

**Issue by create-dan** [wasp-lang/wasp#1507]
The Twitter icon on the home page is still the old bird icon, even though Twitter has updated their branding to use the X icon. Please update the home page to use the new X icon.

![image](https://github.com/wasp-lang/wasp/assets/85820206/bd1d5080-8041-4910-abd0-4f54d76d6bfd)

Can you assign this issue to me?

**Comment by siddhakdak** [comment]
can i go for it??

**Comment by Martinsos** [comment]
Hey sure! @create-dan was first so let's give him an opportunity to handle this one!

**Comment by create-dan** [comment]
Thanks working on it.

**Comment by khanjanSanghavi** [comment]
@Martinsos  I am soo Sorry 
I did't check that you have assigned it to someone

**Comment by Martinsos** [comment]
@khanjanSanghavi reviewed! This is a small issue so it shouldn't be a biggie, so let's review your PR @khanjanSanghavi for now.
