### ISSUE TITLE
Logo change

### ISSUE THREAD

**Issue by gaurav9117** [wasp-lang/wasp#1536]
Hey i want to change the twitter logo to x 
please assign to me

**Comment by infomiho** [comment]
Can you be more specific which icon you want to change?

**Comment by gaurav9117** [comment]
![image](https://github.com/wasp-lang/wasp/assets/110013013/446101a7-877f-43cf-ac9c-3e09d685df64)
this old twitter logo

**Comment by khanjanSanghavi** [comment]
I have solved this in #1522 PR
I don't know why changes are not reflected 
@infomiho

**Comment by infomiho** [comment]
We haven't deployed the latest docs, forgot about this being solved. Thanks @khanjanSanghavi

**Comment by Martinsos** [comment]
@khanjanSanghavi they will be visible once we release new version of web/docs, but they are in!
