### ISSUE TITLE
Change websockets example app home button behavior (Release branch)

### ISSUE THREAD

**Issue by gmirzayev** [wasp-lang/wasp#1537]
Right now, clicking the logo of the [websockets example app](https://websockets-client-production.up.railway.app/login ) redirects to the flowbite react site. Not sure if this is intended but it seems strange when it's supposed to be a wasp example. I think it should be changed to regular behavior of redirecting to the webpage itself or even to the wasp site. There is also a small typo in the description of the app in the docs. If this fix sounds appropriate, I can create a pull request to address it.

**Comment by Martinsos** [comment]
Hey @gmirzayev ! SO regarding typos -> sure, feel free to create a PR!
Logo URL -> you are right, that is a mistake I believe! So that would also be nice to fix!

Feel free to create a PR that fixes this all together and we will see it to get merged.
