### ISSUE TITLE
Improve the Security Contact Information

### ISSUE THREAD

**Issue by tvermaashutosh** [wasp-lang/wasp#1547]
- I'm submitting an enhancement request.

- **Summary**
There are rooms for improvement/enhancement in the Security Contact Information that is being provided in the SECURITY.md file. The language as well as the clarity/comprehensibility can be really improved for the users.

@Martinsos @sodic I request you to assign me this issue. I would like to work on it as I'm new to open-source.

**Comment by Martinsos** [comment]
Hey @tvermaashutosh !

I thought our SECURITY.md is good enough at the moment. How do you think it could be improved? If you want to explain it here before you do something, that might help. Or you can go straight for it. But at the moment I can't really imagine meaningful improvement on that side that we would be keen to accept.

**Comment by tvermaashutosh** [comment]
@Martinsos 
The current CODE_OF_CONDUCT.md file in the repo has been written taking reference of the `Contributor-covenant Version 1.4`.
But, the latest version that has been released till now is the `Version 2.1`.

Therefore I would like to update the CODE_OF_CONDUCT.md file using the https://www.contributor-covenant.org/version/2/1/code_of_conduct .

**Comment by tvermaashutosh** [comment]
@Martinsos 
I have made the SECURITY.md file more descriptive by taking reference of the `https://supabase.com/.well-known/security.txt`.

**Comment by tvermaashutosh** [comment]
@Martinsos 
Please checkout PR #1548 for this issue that I have made.
