### ISSUE TITLE
Enhance the Contributing Guidelines

### ISSUE THREAD

**Issue by tvermaashutosh** [wasp-lang/wasp#1549]
- I'm submitting an enhancement request.

- **Summary**
There are rooms for improvement/enhancement in the Contributing Guidelines that is being provided in the CONTRIBUTING.md file. The language as well as the clarity/comprehensibility can be really improved for the users, ensuring that users can easily access and understand the contributing instructions info.

@Martinsos @sodic I request you to assign me this issue. I would like to work on it as I'm new to open-source.

**Comment by tvermaashutosh** [comment]
@Martinsos 
Please checkout PR #1550 that I have raised for this issue.

**Comment by Martinsos** [comment]
Thanks @tvermaashutosh but we will not be proceeding with this change at the moment -> I explained in the PR! Thanks for the effort!
