### ISSUE TITLE
Fix Full-stack type safety type names

### ISSUE THREAD

**Issue by sodic** [wasp-lang/wasp#1570]
#1544 bumped the version of Prisma from 4.12 to 4.16.

This change introduced a regression in our full-stack type safety DX. The functionality is still there, but type names are far less ergonomic.

We should do our best to find a way to again show meaningful type names again, and also address other potential changes between Prisma 4.12 and 4.16.

### Before
![image](https://github.com/wasp-lang/wasp/assets/22752307/897e7ced-c5e1-43de-9e96-caa3244ad091)

### After
![image](https://github.com/wasp-lang/wasp/assets/22752307/00768df0-0cfe-4d6d-affa-3bbb74341c84)

**Comment by infomiho** [comment]
This will most likely be solved by upgrading to Prisma 5.X according to this fix: https://github.com/prisma/prisma/pull/20319

**Comment by infomiho** [comment]
One extra thing to consider when we solve this: Prisma started branding their model types so our branded `_Entity` types are no longer needed.

**Comment by sodic** [comment]
Also related: generating variations of Prisma entity types: https://discord.com/channels/686873244791210014/1246062324792557638/1246062324792557638

**Comment by FranjoMindek** [comment]
This happened again, we should find out when, and add a regression test for it.
