### ISSUE TITLE
Add "warning" to username & pass section of the docs that it is for learning/testing purposes only

### ISSUE THREAD

**Issue by matijaSos** [wasp-lang/wasp#1572]
The username & password auth method is a fast way to get started, but IMO isn't suitable for production use cases, since there is no account recovery.

I would denote that immediately in the docs, as it might be a bit of a pain to do migration when you already have users. Especially if they haven't used their email as usernames, and then you have no way to migrate them without somehow contacting them (which again, you don't have a way of doing)

**Comment by Martinsos** [comment]
In that case, we should also make it so that you can't deploy with username and pass enabled, it should be only for development.
But we talked about completely phasing out username and pass, so this will all become solved by that at the end.

**Comment by Martinsos** [comment]
We will handle this differently, we won't make it so "bad" to use username/pass, but we will document the cons of it. We have another issue for this.
