### ISSUE TITLE
Migrations are broken (incompatible Prisma version?)

### ISSUE THREAD

**Issue by edoloughlin** [wasp-lang/wasp#158]
**Describe the bug**
The 'Added Task Entity' migration in the tutorial fails

**To Reproduce**
Install wasp using **curl -sSL http://get.wasp-lang.dev | sh**
Follow tutorial steps "Creating New Project" and "Task Entity"
Run  **wasp db migrate-save "Added task entity"**

**Expected behavior**
Task entity is created

**Console output**

```
➜  todo  wasp db migrate-save "Added task entity"
Compiling wasp code...
Code has been successfully compiled, project has been generated.

Setting up database...
Server (stderr): npm WARN
Server (stderr): optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
Server (stderr): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
Server (stderr):
Server: audited 397 packages in 1.339s
Server:
Server: 44 packages are looking for funding
Server:   run `npm fund` for details
Server:
Server: found 0 vulnerabilities
Server:
Database successfully set up!
Copying migrations folder from Wasp to Prisma project...
Done.
Checking for changes in schema to save...
Db (stderr): Error: The current command "save" doesn't exist in the new version of Prisma Migrate.
Db (stderr): Read more about how to upgrade: https://pris.ly/d/migrate-upgrade
Error: Migrate save failed: Migrate save failed with exit code: 1
➜  todo wasp version
0.1.8
```

**Desktop (please complete the following information):**
 - OS: Pop_OS (20.04)
 - Browser: Chrome
 - Version: n/a - doesn't get that far

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by Martinsos** [comment]
Hi @edoloughlin , thanks for letting us know!

Prisma introduced breaking changes in 2.13, and we fixed version to 2.x, which broke Wasp.

We now fixed version of Prisma to 2.12 so problems like this can't happen again, and we will update it to 2.13 in the future.

So now should be ok, just download/install wasp again to get the version 0.1.9 and it should work!
