### ISSUE TITLE
Change the `additionalSignupFields` feature to `getUserFieldsFn`

### ISSUE THREAD

**Issue by infomiho** [wasp-lang/wasp#1608]
After we introduce the new auth models (https://github.com/wasp-lang/wasp/issues/1080) which don't require mixing business logic fields and auth fields on the same `User` entity, the concept of "additional signup fields" won't make sense anymore. Since, there will be only "business logic user fields" but they are not "additional".

For Google & Github auth methods, we have the `getUserFieldsFn` which does exactly that - it specifies which `User` fields to set based on the all available data from e.g. Google like `email`.

We should convert our `additionalSignupFields` into `getUserFieldsFn` but it would receive all the signup form data and then the developer can decide what to put on the `User` object.

**Comment by sodic** [comment]
Closed by #1583
