### ISSUE TITLE
Decide what do we want to do with username & password auth method

### ISSUE THREAD

**Issue by infomiho** [wasp-lang/wasp#1609]
Username & password auth method is not a really viable option for serious project that require email verification and password reset.

Username & password is a great way to start with Wasp in development since it requires zero setup. Maybe we should invest in making the dev mode for email auth simple like that.

Some people start with username & password and then have the need to migrate later to email which is a painful experience after you had your project in production for some time, it's better if we have `email` as the best way to start.

There are some simpler project that might not ever need anything more complex than username & password, are we scaring those projects away? 

Do we want to deprecate the username & password method first and then drop it?

**Comment by Martinsos** [comment]
On one hand we want to get rid of it as it is not good for real usage, on the other hand, email and password require you to have some kind of email provider which is a proper hurdle. So what do we do? Do we just go with it? They can use social auth (that also requires some effort but no payment). Do we offer them our own email provider, kind of like Supabase does? But that makes them dependent on us.

**Comment by Martinsos** [comment]
Superseded by https://github.com/wasp-lang/wasp/issues/1848 .
