### ISSUE TITLE
Upgrade Node version requirement to 20

### ISSUE THREAD

**Issue by flmn** [wasp-lang/wasp#1618]
When run wasp new, wasp reports error message:

❌ --- [Error] Node requirement not met: ------------------------------------------

Your Node version does not meet Wasp's requirements! You are running Node 20.10.0.
Wasp requires Node ^18.12.0 to be installed and in PATH. Check Wasp documentation for more details: https://wasp-lang.dev/docs/quick-start#requirements.

The latest LTS version is 20 from 2023-11-22.

**Comment by skorotkiewicz** [comment]
```
nvm install 18
nvm use 18

wasp new myproject
```

**Comment by Martinsos** [comment]
@skorotkiewicz thanks for the solution!

@flmn we just merged new PR (https://github.com/wasp-lang/wasp/pull/1533) which will make Wasp's node requirements more reasonable -> from now on, it will allow any node version >= 18, not just 18. After some time that will become 20 >=, but basically from now we will only have lower limit for Node version, no upper limit.

New release of Wasp is coming out in a couple of weeks, so then the change will become effective.

**Comment by flmn** [comment]
> @skorotkiewicz thanks for the solution!
> 
> @flmn we just merged new PR (#1533) which will make Wasp's node requirements more reasonable -> from now on, it will allow any node version >= 18, not just 18. After some time that will become 20 >=, but basically from now we will only have lower limit for Node version, no upper limit.
> 
> New release of Wasp is coming out in a couple of weeks, so then the change will become effective.

Thanks a lot.
