### ISSUE TITLE
Add `wasp telemetry` command

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#164]
It should give user an idea of what is telemetry doing in general, and should show for the specific project if it is enabled or disabled.

Rough features:
1. It should give general information on telemetry in Wasp, probably link to docs also, also instructions on how to disable it.
2. If enabled, it should say so and also show some interesting information like: where is telemetry cache stored, when was data sent last time, and what the data that was sent looks like (if it was about to be sent right now).
3. If disabled, it should say it is disabled.

This task comes down to creating a new command in `wasp/waspc/src/cli/Command/Telemetry.hs` and triggering it in `wasp/waspc/src/cli/Main.hs`. All complex pieces of logic can be found in `wasp/waspc/src/cli/Command/Telemetry/` dir.

**Comment by kolharsam** [comment]
@Martinsos is this issue open? If so, could I take a stab at it?

**Comment by Martinsos** [comment]
@kolharsam of course, that would be great!
I suggest, for the first PR, to go simple -> just create a command that says if telemetry is on or off.
Then, you can create additional PR where we will figure out what is the additional information we can display.
I already provided some info in the description that should help you get started, but feel free to ping if anything is unclear of you need more guidance!

**Comment by kolharsam** [comment]
@Martinsos okay! Thanks :)
You should expect a PR soon!

**Comment by Martinsos** [comment]
Awesome, looking forward to it :)!

**Comment by kolharsam** [comment]
Once this above PR is merged, please let me know what plans you have about this command going forward :)

**Comment by kolharsam** [comment]
Hey! Thanks for merging the first part. I guess this issue should still be open.

**Comment by Martinsos** [comment]
Yay we have a `telemetry` command!
So, the idea was to make command provide some extra info, just to give a better idea of what is happening with telemetry.

Besides what we already have (enabled/disbled), I think the main piece of information is short sentence saying how we track only very basic things + link to docs on telemetry (https://wasp-lang.dev/docs/telemetry). Ok that is very simple, we could with smth like "Our telemetry is anonymized and very limited in its scope: check https://wasp-lang.dev/docs/telemetry for more details.".

What could be more cool is if we also printed when was the last time we sent telemetry. If you check Telemetry/Project.hs, you will find ProjectCache there -> it contains information on when was the last telemetry sent, so that is what you need.

I think that is it! Do you have any wishes on what to display :D?

**Comment by kolharsam** [comment]
Hey @Martinsos! Apologies about the late response. I've started work based on the suggestions that you've made here. Could you check the PR, I've mentioned some ideas on the PR description as well.
