### ISSUE TITLE
Handle case when JWT token verification fails

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#168]
Right now, if JWT token verification fails, error 500 is sent. Verification normally fails because either JWT_SECRET changed or token has expired.
This is not right -> it should sent 401.
Also, client should respond to this by deleting/forgetting the JWT token, therefore forcing client to perform login.

So, to fix this, we should:
1. Throw 401 when JWT token verification fails. Right now this happens at waspc/data/Generator/templates/server/core/auth.js, line 31 -> `const userIdFromToken = (await verify(token)).id`. `verify` function here throws an error. We should catch it and return 401.
2. On the client, we should delete token if error was 401. I am not sure what is the best way to handle that -> probably by adding an axios response interceptor in waspc/data/Generator/templates/react-app/src/api.js .

**Comment by jpcarroll** [comment]
Hi @Martinsos I would like to work on this issue!

**Comment by Martinsos** [comment]
Hi @jpcarroll , sounds great :)!
I see that your background is mostly web development which is great, and probably no Haskell, which should be also fine since this issue should not require any Haskell code.

To help you get started, I suggest you go through the https://github.com/wasp-lang/wasp/tree/master/waspc#first-time-contributor-checklist, most important being https://github.com/wasp-lang/wasp/tree/master/waspc#basics -> you should make it as far as running an example TodoApp app, which is in `waspc/examples/todoApp`.

Hardest part might be correctly installing stack, especially if you are on Windows -> let me know if you get stuck somewhere and I can try to help.

Once you are able to run TodoApp example app, I suggest developing this PR in a following manner:
`wasp compile` while in TodoApp will compile Wasp code into TodoApp/.wasp/out.
Then go to .wasp/out/server and run `npm start` to start running the server.
Go into .wasp/out/web-app and run `npm start` to start running the web app.
Then you can go into .wasp/out and directly modify the code there, until you get it behaving as it should. So for this PR, you will probably want to modify .wasp/out/server/core/auth.js and .wasp/out/react-app/src/api.js .
You can also add new files, whatever is needed.
Once you are done, we will want to take those changes back into Wasp code, which most likely means into Wasp templates -> those are under waspc/data/Generator/templates, and based on them is created generated code that you were modifying above.
For this PR, I think it should be enough to just modify templates and not write any Haskell code, but if there will be some Haskell code to write, we can help with that.
Finally, once you feel like you updated the templates correctly, run `wasp compile` again and it will overwrite code in .wasp/out with the freshly generated code -> you will possibly want to store the changes you did manually so they are not lost at this moment in case templates are not completely correct and you want to look into your manual changes for guidance.
Now, run `wasp start` and if you succeeded, app will behave as it should!

Now that I am writing this it seems relatively complicated, which is because it is hehe :D, but once you get into it you will realize it is nothing super smart.
Let me know if anything is confusing and I will be happy to help, either here or on our Discord: https://discord.com/invite/rzdnErX .

**Comment by jpcarroll** [comment]
@Martinsos I have pushed up changes and created a PR for this issue [here](https://github.com/wasp-lang/wasp/pull/177).

I ran through the steps above which all succeeded and the app behaved as it should! I also ran the testing suite using `stack test` which passed all tests. Would there be tests I need to write/update for my change - I couldn't find any tests pertaining to the bug I was fixing?

**Comment by Martinsos** [comment]
Awesome! We unfortunately don't yet have tests for generated code (shame shame!!) -> I wrote more about it in the PR :).

**Comment by Martinsos** [comment]
Fixed by @jpcarroll !
