### ISSUE TITLE
Getting Started Issues

### ISSUE THREAD

**Issue by Salahuddeen** [wasp-lang/wasp#1684]
**Describe the bug**
There are a couple issues. 
1. The Getting started suggests that you use Node LTS. Current LTS is 20.11.0
2. When using Node 18, I was unable to start the Basic starter when using wasp new. 

**To Reproduce**
For 1: 
1. Go to https://wasp-lang.dev/docs/quick-start#requirements
3. Follow Getting Started using Node 20.11.0
4. Get Error

For Error 2:
1. Switch to Node 18. 
2. Create app with wasp new. 
3. Cd into dir.
4. run `wasp start`
5. Get error

**Expected behavior**
Wasp App is bootstrapped

**Screenshots**
Error for scenario 1
<img width="937" alt="image" src="https://github.com/wasp-lang/wasp/assets/17343589/45159ba7-56a5-4ccc-8ebc-7d6f12925c5f">

Error for scenario 2
<img width="1678" alt="image" src="https://github.com/wasp-lang/wasp/assets/17343589/514598d6-a92a-42c4-ab26-23d613744ebb">

**Desktop (please complete the following information):**
 - OS: MacOS Ventura

**Comment by Martinsos** [comment]
Thanks @Salahuddeen ! We are releasing new version of Wasp in a week or so, and it will allow any Node version >= 18, therefore resolving this issue.
