### ISSUE TITLE
Expose `import { getMe } from 'wasp/client/auth` in the SDK + document it

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#1721]
We never had this documented in the docs, but it is the only way for users to mock auth in their client testing, so we should expose it!

@infomiho knows more about this.

**Comment by infomiho** [comment]
Exported in this PR: https://github.com/wasp-lang/wasp/pull/1696/commits/101b13b11316de33619917cd3bf9d483c6990bd9#diff-fcf7f7adc36cfeb165d400a725c23d5bcc39ca9982ea6f894104ffe3817d8546R17
