### ISSUE TITLE
Stop depending on `secure-password`

### ISSUE THREAD

**Issue by sodic** [wasp-lang/wasp#1779]
`secure-password` is unmaintained and causes build issues:
- Core issue: https://github.com/sodium-friends/sodium-native/issues/160
- Fix for pre-0.12.0: https://github.com/wasp-lang/wasp/pull/729
- Fix for 0.12.0 and explanation: https://github.com/wasp-lang/wasp/pull/1773/files#diff-aa79f536fd3bb9203f9d976c63594a52a9f3533759e2b754e2a6baec6403a7dbR215

We should replace `secure-password` with something else (probably from Lucia) and remove the hacks we introduced to make it work.

**Comment by Martinsos** [comment]
Hack we introduced is `override` in `package.json`, for `sodium-native`.

**Comment by Martinsos** [comment]
@infomiho says we could use Oslo instead, from the Lucia ecosystem.

**Comment by infomiho** [comment]
Closed by https://github.com/wasp-lang/wasp/pull/1782
