### ISSUE TITLE
`wasp db reset` command is not running -> it is missing from cli/exe/Main.hs

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#1787]
Either it was never added or it was dropped, although we have the implementation -> let's make sure to add it to cli/exe/Main.hs .
Also, let's add a test (e2e) to prevent this from happening again.

**Comment by sodic** [comment]
We should also figure out what really happened and how it was dropped. I'll dig into it.

Us losing code without realizing is a bigger problem than losing this specific command.
