### ISSUE TITLE
Auth UI and OAuth: show auth errors on screen

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#1817]
> [!NOTE]
> This will be closed by #1851 

We had the case (in wasp 0.12) where:
1. `User` has `email` field with `unique` constraint. It is a field we set with email via `userSignupFields` on successful signup.
2. I sign up with Google, with email address E.
3. I try to sign up with Github, with same email address E, but it just returns me to `login`.
  I get following errors in the console: 
![image](https://github.com/wasp-lang/wasp/assets/1536647/1f247228-eaa4-43d1-9ec1-767481c9c2b8)

Instead, I would expect that some kind of nice error is shown on the screen. I am guessing error gets thrown in `userSignupFields` -> well, actually as a result of executing the setters/gettters defined there -> but it doesn't get displayed by Auth UI for some reason.

**Comment by infomiho** [comment]
Done in https://github.com/wasp-lang/wasp/pull/1851
