### ISSUE TITLE
Migrate examples src folder to Wasp 0.12.0 

### ISSUE THREAD

**Issue by sodic** [wasp-lang/wasp#1832]
We should verify we've upgraded all the examples we're planning to migrate and figure out what to do with the rest.

Most examples (except possibly realworld, what do we do with this one?) have now been updated to work with Wasp 0.12.0. 

Do we want to change the folder structure to be feature-based? After all, that's what [our tutorial recommends](https://wasp-lang.dev/docs/tutorial/project-structure).

**Comment by Martinsos** [comment]
We will want to delete the real-world.

We probably should change the folder structure!

**Comment by Martinsos** [comment]
This is completed!
