### ISSUE TITLE
`wasp start` explodes if file from ext/ dissapears after it listed it but before it copies it

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#187]
What Wasp does is: it listens for file changes in ext/ directory, and in .wasp file. If there are any changes, it runs compilation step. First part of that step is that it takes note of all the files in the ext/ dir, remembers them, but does not read them, just does some processing (figuring out what code to generate), and then in a second or so it actually starts copying them. So some other change triggered the compilation step and then it looked in the ext/ dir and saw the image there, but the moment later it wasn't there any more so when it tried to copy it, it exploded. Maybe you deleted multiple files at once so deletion of another file was a trigger and Wasp actually managed to see the image before it got deleted. Might also be cause by checking out previous commit.
Fix should be easy, we just need to tell it to not worry if file is not there any more and just ignore it.
This will probably also fix the problem we have with Vim swap files dissapearing in the middle of the compilation, which causes the same problem.

Example of error message:
```
 wasp-bin: .../workspace/hello-wasp/MyNewApp/ext/waspLogo.png: copyFile:atomicCopyFileContents:withReplacementFile:copyFileToHandle:openBinaryFile: does not exist (No such file or directory)
```

Thanks @ricklamers for reporting this!

**Comment by xrendan** [comment]
I also get this while editing files in Webstorm normally:

Looks like Webstorm (and other Intellij editors presumably) create a temporary file on edit that

**Comment by matijaSos** [comment]
@xrendan thanks for reporting, you identified the error correctly! This should be fixed now.
