### ISSUE TITLE
Discord Invite Link Broken

### ISSUE THREAD

**Issue by GavPierce** [wasp-lang/wasp#1879]
I've been wanting to join the Discord but it seems to be broken the invite. Can someone link me an updated one? Thank you!

**Comment by Martinsos** [comment]
That is weird, it works for me! Have you tried this one https://discord.gg/rzdnErX ? What link did you use?

**Comment by GavPierce** [comment]
@Martinsos Great! Thank you, it is working now. But I _did_ try it on multiple devices and it gave the "Whoops... Unable to accept invite", so I have no idea ha

**Comment by Martinsos** [comment]
No worries @GavPierce , maybe it was an issue on the Discord side, I am glad it works now!
