### ISSUE TITLE
hGetContents: invalid argument

### ISSUE THREAD

**Issue by cognitivetech** [wasp-lang/wasp#1892]
**Describe the bug**
compiling error

```
🐝 --- Compiling wasp project... --------------------------------------------------

wasp-bin: /home/asimov/github/seaman-cx1i9/._main.wasp: hGetContents: invalid argument (invalid byte sequence)
```

**To Reproduce**
1. Unpackage created application.
2. Install node v19.9.0
3. go to application directory
4. run `wasp db migrate-dev`

**Expected behavior**
The app will compile and then I can run it.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20, Bash

**Comment by Martinsos** [comment]
@cognitivetech what was the cause of this issue?

Btw node 19 is a bit tricky -> odd version numbers are not considered stable, so you will likely want to go with 18 or 20 instead.

**Comment by Martinsos** [comment]
> I don't know, I was using code auto generated by an ai app, only after I submitted this issue I realized you weren't the app-maker... just decided to pivot.
> 
> thanks for the tip

No worries! We are also creators of usemage.ai though, so if that is what you are referring to, then you asked in the right place.
