### ISSUE TITLE
Document our environment variables

### ISSUE THREAD

**Issue by sodic** [wasp-lang/wasp#1894]
We should have a table documenting the names, scopes, and uses of all our environment variables.

A couple of sections only mention them in passing (manual deployment instructions and configuration object docs).

**Comment by infomiho** [comment]
Related to https://github.com/wasp-lang/wasp/issues/1067#issuecomment-1552971969

**Comment by sodic** [comment]
Related to #2053

**Comment by sodic** [comment]
Closed by #2375
