### ISSUE TITLE
Update Prisma to the latest version (2.17.0)

### ISSUE THREAD

**Issue by matijaSos** [wasp-lang/wasp#194]
Right now Prisma version in Wasp is fixed to 2.12.1, which means it uses [legacy migrate features](https://www.prisma.io/docs/concepts/components/prisma-migrate/legacy-migrate), where `migrate up` and `migrate save` is used. [New migrate](https://www.prisma.io/docs/concepts/components/prisma-migrate) from 2.13.0 introduces only `migrate dev` which covers both `save` and `up` cases. Other commands are `deploy`, `reset`, `status` and `resolve`.

We want to add support for all of that - we'll need to set up a 2-way communication with Prisma CLI and that way users will be able to use Prisma directly from Wasp, without our layer in between. Also, `migrate dev` now sometimes asks for extra input (in case of save) and sometimes not, so we cannot shy away anymore from 2-way communication.

**Comment by Martinsos** [comment]
Solved with #217
