### ISSUE TITLE
SDK build failed with exit code: 2 

### ISSUE THREAD

**Issue by clickbrain** [wasp-lang/wasp#1942]
**Describe the bug**
Used the Mage interface to create an app and received this error message when I ran: wasp db migrate-dev
SDK build failed with exit code: 2 

**To Reproduce**
1. Go to Mage and describe app
2. Download zip and uinzip it in app directory
3. Run wasp db migrate-devwasp db migrate-dev
4. See error:

🐝 --- Compiling wasp project... --------------------------------------------------

✅ --- Successfully completed npm install. ----------------------------------------

🐝 --- Setting up database... -----------------------------------------------------

[   Db  !] Error: P1003
[   Db  !] 
[   Db  !] Database dev.db does not exist at /Users/bradn/Documents/dev/MidTrack/MidTrack-pkulz/.wasp/out/db/./dev.db
[   Db  !] 
✅ --- Database successfully set up. ----------------------------------------------

🐝 --- Building SDK... ------------------------------------------------------------

[  Wasp  ] ext-src/pages/Home.jsx(18,30): error TS1005: '{' expected.
[  Wasp  ] ext-src/pages/Home.jsx(18,32): error TS1005: ',' expected.
[  Wasp  ] ext-src/pages/Home.jsx(18,33): error TS1382: Unexpected token. Did you mean `{'>'}` or `&gt;`?
[  Wasp  ] ext-src/pages/Home.jsx(19,27): error TS1005: '{' expected.
[  Wasp  ] ext-src/pages/Home.jsx(20,26): error TS1005: '{' expected.
[  Wasp  ] ext-src/pages/Home.jsx(21,35): error TS1005: '{' expected.
[  Wasp  ] ext-src/pages/Home.jsx(22,35): error TS1005: '{' expected.
[  Wasp  ] ext-src/pages/Home.jsx(24,13): error TS1381: Unexpected token. Did you mean `{'}'}` or `&rbrace;`?

❌ --- [Error] Your wasp project failed to compile: -------------------------------

- SDK build failed with exit code: 2

❌ --- [Error] Compilation of wasp project failed: --------------------------------

1 errors found

**Expected behavior**
App compile and prepare and then run it

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.4.1
 - Browser Edge

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Martinsos** [comment]
This will be due to Mage outputing code that is invalid (it does that sometimes, it is LLM). Seems that such code is in Home.jsx. Maybe it generate all code in one line? It can do that sometimes. If so, I suggest you run Mage again, or use GPT to fix that code for you.

I will be closing this one for now, but we can reopen if issue continues!

**Comment by clickbrain** [comment]
Just an update. Ran Mage again with the same desctiotion and this time everything seems to compiled correctly, and it auto-loaded localhost, but now I get a blank browser page.

**Comment by Martinsos** [comment]
> Just an update. Ran Mage again with the same desctiotion and this time everything seems to compiled correctly, and it auto-loaded localhost, but now I get a blank browser page.

Check out console logs in the browser, now it is probably different mistake!
