### ISSUE TITLE
Update docs on deploying to Netlify

### ISSUE THREAD

**Issue by infomiho** [wasp-lang/wasp#1999]
It seems that OAuth redirects don't work properly without using a special `_redirect` file to set up the redirect on Netlify.

Discord thread: https://ptb.discord.com/channels/686873244791210014/1233257829897605282/1234504751408742460

**Comment by sodic** [comment]
Related: #1982

**Comment by infomiho** [comment]
After testing it again, it seems that there is no need for a special `_redirect` file since we already provide a `netlify.toml` with the needed redirects listed in the config file. This issue will close after we merge https://github.com/wasp-lang/wasp/pull/2041
