### ISSUE TITLE
Automatic Crud Override Issue

### ISSUE THREAD

**Issue by atasoya** [wasp-lang/wasp#2032]
**Describe the bug**
When getAll query is overrode and custom logic requires arguments from client, wasp doesn't let to provide arguments.

**To Reproduce**
1. Create crud object in .wasp file.
2. Override getAll query and use arguments.
3. Call query from client with arguments.

**Expected behavior**
Let argument passed from client.

**Comment by infomiho** [comment]
@atasoya thank you for the report, I've assigned myself to test this out and see what's going on.

**Comment by infomiho** [comment]
Yep, it seems that our implementation currently doesn't support passing arguments to the CRUD override functions on the client. 

One workaround (temporary because we will fix this) is to use the `useQuery` helper with the CRUD query directly like this:
```ts
import { tasks as tasksCrud } from 'wasp/client/crud'
import { useQuery } from 'wasp/client/operations'

const { data: tasks, isLoading } = useQuery(tasksCrud.getAll.query, {
  filter: 'my search',
})
```
