### ISSUE TITLE
Make final TS SDK RFC

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#2047]
Let's make a plan (RFC) on ideas how we will implement TS SDK (TS eDSL) (#551 ).

We want to make a prototype that will run alongside Wasp DSL, then once we see how that goes, we will decide how to continue (keep both, keep just one).

This issue is just for the initial planning.

EDIT: Did initial planning, now let' do final RFC before starting a prototype.

**Comment by sodic** [comment]
This was done here: https://www.notion.so/wasp-lang/RFC-TS-DSL-SDK-86c4082ab9924c77b07dcb25d4cd95ad
