### ISSUE TITLE
 deleteDocument } from 'wasp/client/operations';

### ISSUE THREAD

**Issue by FELS-Zak** [wasp-lang/wasp#2051]
After the running Marge and adding the migration, I run the start and get a blank screen 
on inspect I see this  ...
.wasp/out/sdk/wasp/dist/client/operations/index.js' does not provide an export named 'deleteDocument' (at Dashboard.jsx:3:49)

**Comment by Martinsos** [comment]
Ah yes, Mage can make silly mistakes!

This is not a Wasp issue though -> pls join our Discord and go to "questions" for help with this!
