### ISSUE TITLE
Clean up /build dir before `wasp build`

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#210]
This is to ensure that there are no left-overs from the previous `wasp build`.

**Comment by kolharsam** [comment]
Hey @Martinsos! 👋 
Can I pick this up?

**Comment by Martinsos** [comment]
Hey @kolharsam , sure, go for it :)!

**Comment by kolharsam** [comment]
@Martinsos I've made a PR relevant to this issue. Please go through it and share feedback! :)
