### ISSUE TITLE
Propagate deletion of db migrations from Wasp src to the generated project

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#211]
Right now, if you delete `migrations/` dir from the Wasp project root dir and run `wasp start` or `wasp build`, any previously generated `migrations/` dir will remain in the generated code -> it will not get removed!
Instead, we want it to get removed.
We should do it the same way we did this for .env file.

**Comment by Martinsos** [comment]
NOTE: This issue already has some work done in this PR: https://github.com/wasp-lang/wasp/pull/282 !

**Comment by shayneczyzewski** [comment]
Hey @Martinsos! I reviewed the noted PR and it seemed like there was some work being done in `cli` land, some in `src` land, but it was not unified or connected together in any way. I'm not sure of the ultimate direction it was intending to go.

As I'm sure you recall, the crux of the issue is we need access to two directories, the `waspDir` and `outDir`. Commands in `cli` have access to both, but things in `src` only `outDir` (like `ServerGenerator.preCleanup` which removes `.env` in the `outDir` but does not need to care about its status in `waspDir` when deleting.

However, it is kind of nice to be able to track/resolve those dependencies in `src`. One way we _can_ do this (not sure if it is the right way though), is update `Lib.compile` to pass the `waspDir` to `Generator.writeWebAppCode`. Then, `DbGenerator.preCleanup` can access both. You can see the code involved in this commit for my Draft PR: https://github.com/wasp-lang/wasp/pull/383/commits/a045b1639b7d1211cc272726b42ef897ec66a42d (Note: still lots to clean up, but wanted to push early for direction feedback.) The downside is we no longer have full encapsulation of using a `Wasp` in `Generator` and can make use of `waspDir`. Is this a dealbreaker?

If so, we can make the clean calls in each `Command` needing it (like `Build`, `Start`) to ensure the migrations dir has been cleaned. That could reference a helper exposed in `src` too (not sure of value) or just live entirely in `cli`. Biggest downfall here is we will need to ensure we add it to any commands in the future that need it. That could be helped by a design where we indicate what commands require what cleaning steps, but that is TBD.

Or is there some other approach I may be missing? Thanks so much for thoughts on the direction!

**Comment by Martinsos** [comment]
> Hey @Martinsos! I reviewed the noted PR and it seemed like there was some work being done in `cli` land, some in `src` land, but it was not unified or connected together in any way. I'm not sure of the ultimate direction it was intending to go.
> 
> As I'm sure you recall, the crux of the issue is we need access to two directories, the `waspDir` and `outDir`. Commands in `cli` have access to both, but things in `src` only `outDir` (like `ServerGenerator.preCleanup` which removes `.env` in the `outDir` but does not need to care about its status in `waspDir` when deleting.
> 
> However, it is kind of nice to be able to track/resolve those dependencies in `src`. One way we _can_ do this (not sure if it is the right way though), is update `Lib.compile` to pass the `waspDir` to `Generator.writeWebAppCode`. Then, `DbGenerator.preCleanup` can access both. You can see the code involved in this commit for my Draft PR: [a045b16](https://github.com/wasp-lang/wasp/commit/a045b1639b7d1211cc272726b42ef897ec66a42d) (Note: still lots to clean up, but wanted to push early for direction feedback.) The downside is we no longer have full encapsulation of using a `Wasp` in `Generator` and can make use of `waspDir`. Is this a dealbreaker?
> 
> If so, we can make the clean calls in each `Command` needing it (like `Build`, `Start`) to ensure the migrations dir has been cleaned. That could reference a helper exposed in `src` too (not sure of value) or just live entirely in `cli`. Biggest downfall here is we will need to ensure we add it to any commands in the future that need it. That could be helped by a design where we indicate what commands require what cleaning steps, but that is TBD.
> 
> Or is there some other approach I may be missing? Thanks so much for thoughts on the direction!

Great analysis!

Yeah, the main thing is that information about location of WaspDir is not available in the Generator, and solution is to either obtain that information, or to move the logic that needs it outside of the Generator (or to somehow avoid needing that information at all).

The thing is, we don't want any other piece of code but Generator to know where the code is being written generated / and how -> that should be sole responsibility of Generator. Right now that is not completely followed though: we have this issue to move the logic for copying migration directories: https://github.com/wasp-lang/wasp/issues/105 -> this is connected to this issue actually.

Regarding source code, right now it consists of:
- .wasp source files -> they are captured in `Wasp` AST and given to Generator like that
- external source files (ext/) -> they are also captured in `Wasp`, and partially in CompileOptions? (not sure about this last part).
- .env file -> this one is also provided via `Wasp` AST
- migrations/ dir -> this one is not provided to Generator at all, instead they are copied by the certain commands in CLI (to be fixed with #105).

So we have this "mix" here -> it all started with just .wasp, and then as other things were added, we didn't always make consistent decisions. Right now, if I had to make a quick decision, I would put all of them into Wasp. If I have more time to think, then it becomes a bit more complicated (especially with .env, since it is not part of the code that will be deployed to production, it serves only for local dev).

So looking at this, one solution might be to not provide Generator with the Wasp source dir, but instead with the migrations dir. Then it can use that path to both delete the old migrations dir, if needed, and to copy the migrations from source to the generator. This could solve both of the issues, this one and #105, I believe.

Another solution is to provide Generator with the Wasp source dir -> that certainly makes sense, but it also kind of opens a lot what Generator can do, possibly a bit too much -> I am afraid that with time people will start using that information to do more and more stuff in Generator and at some point it will be hard to figure out on which stuff in Wasp source dir Generator depends, what it reads / accesses from there. So thinking about this, I would rather that Generator doesn't know about Wasp source dir - what do you think? It is what you mentioned regarding encapsulation - ideally Generator would have well defined set of inputs (`Wasp` AST + maybe something else, like CompileOptions) that directly determine what will be generated, and that is it, we are sure that is all the input it uses.

Btw, a small correction on what you said -> it is not that none of the code in src/ knows about waspDir -> code in src/Wasp/Lib.hs does know -> but that is it, only Lib.hs knows, and then from there on it is pretty limited.
In theory, what we want is for Generator to not know about wasp dir, but I think we are ok with Parser (future Analyzer) possibly knowing some info about waspDir -> however that is not relevant for this PR I think and it will become more clear as I make future progress with Analyzer.

Uff ok so I dropped a lot of info here on you, hoping it will help! I think I am most inclined toward solution where we embed information about migration src dir into Wasp.hs and then provide it to Generator that way, however I believe you will be able to possibly get a better picture of the whole situation than me after you go through it more so I am open to other alternatives if judge they might be better.

**Comment by Martinsos** [comment]
Oh, one more thing -> you will notice that in Generator.hs main function is IO, but all the <smth>Generator functions it calls are pure (no IO in return type). So basically Generator does IO only at this top level, and from there on the rest is pure. Therefore, my argument from before, that Generator can do whatever it wants with waspSrcDir if it has access to it, is still correct, but it is somewhat weakened -> it can do whatever it wants in this IO part, which is very small in Generator.hs, but it can't do anything with it in the pure parts, which are the bigger part of the generator. I still think the direction I suggested in comment above might be making most sense, but this shines a bit different light on it, in the sense that solution where Generator knows waspSrcDir might not be that terrible. Hm! Complex :D.

**Comment by shayneczyzewski** [comment]
Hi @Martinsos thanks for the info, context, and related concerns, it is helpful! Let me do some more digging and thinking and I can come back with some info/ideas. Thanks!

**Comment by shayneczyzewski** [comment]
Hey there @Martinsos! Thanks again for the prior replies, it was helpful! After reviewing the conventions I agree that in this case the best approach is probably putting migrations dir info into `Wasp`. That way, the Generator can only care about a `Wasp`, `outDir`, and `CompileOptions`. As you noted, the fact that it does all `IO` at the top level though does mean in the future we may consider passing additional args, but in this case I think having migrations in `Wasp` makes the most sense.

I have updated my original direction with a second commit here: https://github.com/wasp-lang/wasp/pull/383 It now embeds `migrationsDir` into `Wasp` and provides a `DbGenerator.preCleanup` function the Generator can use (similar to `dotEnvFile`). The PR is still Draft as I would like to investigate/add some tests around it, but if you get a few minutes in the coming days and have any early feedback on Haskell conventions, etc. I would greatly appreciate it. Thank you! 👍🏻

**Comment by Martinsos** [comment]
> Hey there @Martinsos! Thanks again for the prior replies, it was helpful! After reviewing the conventions I agree that in this case the best approach is probably putting migrations dir info into `Wasp`. That way, the Generator can only care about a `Wasp`, `outDir`, and `CompileOptions`. As you noted, the fact that it does all `IO` at the top level though and pure below does mean in the future we may consider passing additional args, but in this case I think having migrations in `Wasp` makes the most sense.
> 
> I have updated my original direction with a second commit here: #383 It now embeds `migrationsDir` into `Wasp` and provides a `DbGenerator.preCleanup` function the Generator can use (similar to `dotEnvFile`). The PR is still Draft as I would like to investigate/add some tests around it, but if you get a few minutes in the coming days and have any early feedback on Haskell conventions, etc. I would greatly appreciate it. Thank you! 👍🏻

Sounds good, left initial comments on PR!

**Comment by shayneczyzewski** [comment]
Hey @Martinsos thanks for the PR feedback! As I begin to wrap this one up, I crossed over to the rabbit hole of testing it. This one is tricky, since I don't have a pure portion to test and the only "real" way to test it is to involve the actual filesystem (I don't even think I can mock the FS part here, but maybe I missed how while reviewing options). But real FS tests do not seem to be a canonical way to go for Haskell unit tests, and I think that makes sense. :D

I wanted to toss out the idea of some larger (in the future), higher level test suite at the blackbox CLI level. So probably something using bash or some equivalent way that we can run real commands, muck with real files, and then run tests, to make sure the observed behavior with _real files_ is what we expect (so we can test this migration one, for example, by creating a project with an entity, migrating, running start, removing wasp migrations dir, and then running start again to make sure it is removed from the generated project).

Was anything like this on the roadmap, or does it sound not worth it?

While that idea is a long way off, any other near-term ideas on how I may be able to test this one (or just punt for now)? Thanks!! 🙏🏻

**Comment by Martinsos** [comment]
> Hey @Martinsos thanks for the PR feedback! As I begin to wrap this one up, I crossed over to the rabbit hole of testing it. This one is tricky, since I don't have a pure portion to test and the only "real" way to test it is to involve the actual filesystem (I don't even think I can mock the FS part here, but maybe I missed how while reviewing options). But real FS tests do not seem to be a canonical way to go for Haskell unit tests (or most languages), and I think that makes sense. :D
> 
> I wanted to toss out the (possibly crazy) idea of some future, higher level test suite at the blackbox CLI level. So probably something using bash or some equivalent way that we can run real commands, muck with real files, and then run tests, to make sure the observed behavior with _real files_ is what we expect (so we can test this migration one, for example, by creating a project with an entity, migrating, running start, removing wasp migrations dir, and then running start again to make sure it is removed from the generated project).
> 
> Was anything like this on the roadmap, or does it sound not worth it?
> 
> While that idea is a long way off, any other near-term ideas on how I may be able to test this one (or just punt for now)? Thanks!! 🙏🏻

Those are all very valid concerns / questions / suggestions!

So, in Haskell in general, idea is that you make as much of your code pure as you can, since that is then easy to test. The whole "IO shell, pure core" approach. However, you will inevitably have some part of the code left in the IO, and then the questions comes how to test that. In javascript, you would just monkey-patch and therefore mock the functions that are doing IO, and that way do the tests. In Haskell you can't do that (at least not in a nice way), so what people do instead is abstract away the IO / side effects.
I believe there are different ways to do that, and you can see us using one approach to mock and test the Writeable typeclass (that is the reason why `write` doesn't have IO in it, but instead has `WriteableMonad`, which then in real code we replace with IO but in tests we replace it with the state monad, so we can simulate the side effects and count function calls and similar). However, in our case this resulted with a lot of boilerplate. I believe in the mean time there have been some libraries created that help with this, basically they automatically generate this boilerplate for you -> but I have to admit I haven't looked into that enough. To put it shortly, it can be done, but it proved to be a bit tedious on our side -> however I think we might be able to improve that by finding a better way (using some libraries that generate mocks).

Another way would be to do what you said, some kind of external testing / integration tests. We don't have anything yet, but we certainly should at some point. Certainly as we move further toward stable version of Wasp and as we become frustrated with manual testing. Besides what you desribed with the bash and similar, it might also make sense to have Wasp generated e2e tests for the web app (Cypress of Testcaffe) and then use those to test the generated code (although tests are also generated but well). So, yes, there are tests missing on multiple levels of Wasp and I think it will be very interesting challenge to add them! And I think we might come to doing that relatively soon.

**Comment by shayneczyzewski** [comment]
Thanks for the great overview! I too have seen in my limited research that the "IO shell, pure core" makes sense, but it can then get a bit messy if you need to break it.

Good point on the desire to not only test the CLI, but generated web app itself! Indeed, many future testing options that we can explore as it becomes too painful. :D
