### ISSUE TITLE
Installation failed: There is no wasp version 0.13.2

### ISSUE THREAD

**Issue by AitshKay** [wasp-lang/wasp#2114]
Trying to install, but getting the following:

```
hussein@aitsh:~/code$ curl -sSL https://get.wasp-lang.dev/installer.sh | sh

Installing wasp version 0.13.2 (latest).

Downloading binary package to temporary dir and unpacking it there...

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Warning: Failed to open the file /tmp/tmp.qjzy7gbbXm/wasp-linux-x86_64.tar.gz: 
Warning: No such file or directory
  0 77.3M    0 14355    0     0  15349      0  1:28:05 --:--:--  1:28:05 15349
curl: (23) Failure writing output to destination
Installation failed: There is no wasp version 0.13.2
hussein@aitsh:~/code$ wasp new
Command 'wasp' not found, did you mean:

```

 - OS: Ubuntu 23.10

Have tried searching for a way around the error with gemini or google generally but didn't find anything relevant.

Really excited to try opensaas.sh still tho.

**Comment by Martinsos** [comment]
This is aproblem with curl installation you have on your Ubuntu likely!
Check this one for solution: https://github.com/wasp-lang/wasp/issues/1455#issuecomment-1739549085 -> you basically got to make sure you have properly installed `curl`.

I will close this issue but do comment again if you are still facing an issue!
