### ISSUE TITLE
Mailgun email provider not working.

### ISSUE THREAD

**Issue by Aunchers** [wasp-lang/wasp#2141]
**Describe the bug**
I am using OpenSaaS.sh which is using the wasp software, infact it is built into wasp.
When making the Email Sending Provider "MailGun" like in the docs, the code errors out as if MailGun is not a recognizable term. Refer to
[The OpenSaaS.sh Docs](https://docs.opensaas.sh/guides/email-sending/) for more info

**To Reproduce**
1. Create SaaS template, and go through steps to initialize.
2. in `.env.server` change `ln:79` or emailSender.provider to "MailGun"
3. run `wasp build` to build for deploy

**Expected behavior**
Builds the deployable .wasp/build just like it works with sendgrid provider

**Screenshots**
![image](https://github.com/wasp-lang/wasp/assets/91509158/e0ed5888-e653-40ff-9cbc-5c6c6654ab73)

**Desktop (please complete the following information):**
 - OS: Windows 11, WSL2, Ubuntu 22.04.4 LTS
 - Browser Arc (Chromium Latest)
 - Node Version [v20.15.0]
 - Wasp Version [Latest]

**Additional context**

**Comment by infomiho** [comment]
You need to put `Mailgun` as the provider (lowercase g) as per the docs: https://wasp-lang.dev/docs/advanced/email#using-the-mailgun-provider

Let me know if that worked out for you.

**Comment by Martinsos** [comment]
@infomiho it seems our comments in open saas are wrong then, they say to use SendGrid or MailGun (big G), you can see them printed there in the screenshot above.

**Comment by Aunchers** [comment]
@infomiho Yep, that worked perfectly, thanks.

**Comment by Martinsos** [comment]
Ok, made a PR to fix the comments in open-saas here https://github.com/wasp-lang/open-saas/pull/221 .
