### ISSUE TITLE
Disallow using entities in the Wasp file

### ISSUE THREAD

**Issue by infomiho** [wasp-lang/wasp#2148]
Users with the current iteration of Wasp + Prisma file can still define their entities in the Wasp file.

Wasp compiler will allow it and include them in the Wasp AST. 

We didn't remove the `entity` declaration to make it easier to switch to using the `models` from the Prisma file without touching the compiler too much.

### What we need to decide

- Do we want to allow users to define entities in the Wasp file? 

  IMHO we should disallow it. It creates a cognitive dissonance for our users with two things being possible but Wasp now officially support only one of them. 

- How do we behave in that scenario? 
  
  We should make it a validation error: "Hey, entities are no longer allowed in the Wasp, please use the Prisma file at `schema.prisma` in your project's root directory ..."

**Comment by Martinsos** [comment]
Yup, sounds all good to me!

**Comment by infomiho** [comment]
Ok, then we are in agreement, I'll introduce validation that forbids using entity declarations in the Wasp file.
