### ISSUE TITLE
Wasp not working with node 22.5.0 (this is npm bug, not Wasp!)

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#2195]
![image](https://github.com/user-attachments/assets/a482f8c2-766d-4a05-9c00-2e9f1c0bc72f)

This is npm bug that happens only with node 22.5 which was just released: https://github.com/npm/cli/issues/7657 . I assume it will be resolved soon but I am still documenting this in case Wasp users start looking at the Wasp issues for possible solution.

We can close this issue once npm/node pplz fix this.

Solution right now: use some other version of node. `22.4.0` already works fine.

**Comment by infomiho** [comment]
Node 22.51.0 is out and fixes the issue: https://nodejs.org/en/blog/release/v22.5.1

**Comment by Martinsos** [comment]
Awesome, I will close this one then!
