### ISSUE TITLE
`useQuery` doesn't handle errors thrown from wasp operation

### ISSUE THREAD

**Issue by JakeLo123** [wasp-lang/wasp#2208]
**Describe the bug**
`useQuery` from `wasp/client/operations` doesn't seem handle errors thrown from the operation passed to it. Consider the following. The `error` property returned from `useQuery` remains `null`.

```
// main.wasp
query getTasks {
  fn: import { getTasks } from "@src/tasks/queries",
  entities: [Task]
}
```

```typescript
// src/tasks/queries
export const getTasks = ((_args, context) => {
  throw new HttpError(500, "Something went wrong");
}) satisfies GetTasks<void, Task[]>;
```

```jsx
export const MainPage = ({ user }: { user: AuthUser }) => {
  const { data: tasks, isLoading, error } = useQuery(getTasks);

  if (isLoading) return "Loading...";
  if (error) return "Error: " + error;
 // ...
}
```

**To Reproduce**
[Here is a minimum reproducing example](https://github.com/JakeLo123/wasp-client-query-error-handling/tree/error-handling). Generated from the todo template with `wasp new -t todo-ts`. Modified to throw `HttpError(500)` from the `getTasks` query.

1. Pull the repo on branch `error-handling`
2. `wasp db migrate-dev && wasp start`
3. Go to the root page
4. Observe that the page remains in "loading" even though the request has resolved to a response with code 500.

**Expected behavior**
It should show that there is an error.

**Desktop (please complete the following information):**
 - OS: macOS
 - Wasp version: 0.14.0
 - Node version: 20.13.1

**Comment by Martinsos** [comment]
Solved! We concluded it wasn't a bug, just normal react-query behaviour that can be a bit confusing if you don't know about it (it polls 3, 4 times before returning an error + restarts on window focus). More details here in Discord convo https://discord.com/channels/686873244791210014/1265713311731810408/1265713311731810408 .
