### ISSUE TITLE
Improve error messaging when wasp build detects that SQLite is used.

### ISSUE THREAD

**Issue by turbodami** [wasp-lang/wasp#225]
SQLite shouldn't be used in production, so when user runs wasp build but has SQLite set as db system (either because he defined no db system and SQLite is default or because they explicitly chose SQLite), wasp throws an error.

To make this happen just run wasp build in a newly created app.

Message right now is somewhat hard to understand -> we should make it clearer! User should understand from it that they need to set db { system } to something that is not SQLite (which for now is PostgreSQL).

**Comment by Martinsos** [comment]
Sub-task of #213 .

**Comment by Martinsos** [comment]
Done!
