### ISSUE TITLE
possible 0.14.1 bug ✘ [ERROR] Could not resolve "@node-rs/argon2-wasm32-wasi"

### ISSUE THREAD

**Issue by Billyjameshowell** [wasp-lang/wasp#2257]
**Describe the bug**
I was running wasp 0.14.0 on mac sonoma 14.1.1 no problem. i updated to 0.14.1 and started getting this error "✘ [ERROR] Could not resolve "@node-rs/argon2-wasm32-wasi""

I've tried wasp clean, removing all node modules manually and uninstalling wasp and reinstalling. can't fix it.
I've cleared all my docker containers and volumes too

T

**Comment by infomiho** [comment]
Could you maybe try deleting the `package-lock.json` file and trying it again?

**Comment by Billyjameshowell** [comment]
tried that! not sure what's going. have killed all background processes, updated node, etc.

**Comment by Billyjameshowell** [comment]
unsure if related but after updating wasp i'm getting this /Users/billy/.wasp-completion.zsh:1: bad pattern: ^[[1mUSAGE^[[0m

but my wasp commands are working fine

**Comment by Billyjameshowell** [comment]
and to clarify i deleted package lock
wasp clean
wasp db start
wasp db migrate-dev
wasp start

**Comment by infomiho** [comment]
Could you please come to our Discord and post this in the #questions channel so we can have a more real-time communication :) https://discord.gg/rzdnErX

**Comment by Martinsos** [comment]
Is it correct @Billyjameshowell @infomiho that cause here was stray yarn file and that this was fixed by removing it?

**Comment by infomiho** [comment]
This report and the report on Discord (which was resolved by deleting the `yarn.lock` file) are two different things. I don't believe that @Billyjameshowell reported his issue as resolved?

**Comment by Martinsos** [comment]
Closing for now due to lack of info at the moment, but if it turns out it is still a problem please let us know and we will reopen!
