### ISSUE TITLE
Upgrade @headlessui/react to latest version

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#2282]
### Discussed in https://github.com/wasp-lang/wasp/discussions/2274

<div type='discussions-op-text'>

<sup>Originally posted by **JakeLo123** September  9, 2024</sup>
Wasp uses `@headlessui/react@1.7`. As a wasp user, it would be nice to be able to use the latest version since some of the 1.7 APIs are deprecated.

It's not possible in wasp 0.14 to upgrade dependencies that wasp already uses internally.

Relevant issue:
https://github.com/wasp-lang/wasp/issues/645</div>

**Comment by infomiho** [comment]
`@headlessui/react@1.7` is not used by Wasp internally, this is an userland Open SaaS dependency which can be upgraded freely.
