### ISSUE TITLE
wasp deploy fly creare-db region command fails due to wrong name

### ISSUE THREAD

**Issue by hellwaiver** [wasp-lang/wasp#2286]
Running the launch command fails, because the CLI gets the name wrong. See the screenshot:

![image](https://github.com/user-attachments/assets/80069307-36ca-41a5-91fc-684ec737ed45)

See how the name in the screenshot differs? Requires a user to rerun manually after correcting it

**Comment by infomiho** [comment]
Yep, this is a problem of robustness of our CLI setup for deploying with Fly. We aren't checking if the app names are available.

This is something we want to improve in the future and are tracking it here: #1588
