### ISSUE TITLE
Template link from terminal 404s

### ISSUE THREAD

**Issue by billyowex** [wasp-lang/wasp#2287]
The template link from Wasp (0.14.0) terminal is dead

1. type wasp in terminal
2. >  GENERAL
    new [<name>] [args]   Creates a new Wasp project. Run it without arguments for interactive mode.
      OPTIONS:
        -t|--template <template-name>
           Check out the templates list here: [](https://github.com/wasp-lang/start)
3. go to https://github.com/wasp-lang/start 
4. link returns 404

**Comment by infomiho** [comment]
Are you sure your terminal didn't cut off the output early? :)

<img width="892" alt="Screenshot 2024-09-16 at 23 27 35" src="https://github.com/user-attachments/assets/22baef5c-6388-4d9d-aaa0-d4082da3a314">

The URL is https://github.com/wasp-lang/starters which is correct.
