### ISSUE TITLE
Replace Wasp favicon/logo in the templates with something else (da boi? bee emoji? something generic?)

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#2302]

**Comment by mmaksimovic** [comment]
I added this to open-saas
![da-boi](https://github.com/user-attachments/assets/6b02a6c1-0f0b-4f5f-9d34-59cd2e65cbca)

**Comment by Martinsos** [comment]
Actually it turns out most other frameworks do have their own logo as favicon, so this is probably not a problem actually.
