### ISSUE TITLE
Foreign keys do not work when using UUID as field type

### ISSUE THREAD

**Issue by amontalban** [wasp-lang/wasp#2323]
**Describe the bug**

I'm trying to create a relation between two tables using an UUID field (userID in this case), however this seems to not be supported by Wasp (Although it is supported by Prisma). I'm using latest release `v0.15.0-rc1`.

Here are some related issues for another request I had to allow using `uuid` field for the User table.

- https://github.com/wasp-lang/wasp/pull/2243
- https://github.com/wasp-lang/wasp/issues/2167
- https://github.com/wasp-lang/wasp/issues/2137

Probably @infomiho has enough context on the above.

Thanks in advance for the help!

**To Reproduce**
Use the following model:

```
model User {
  id                      String       @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
  createdAt               DateTime     @default(now())
  updatedAt               DateTime     @default(now())
  email                   String       @unique
  firstName               String
  lastName                String
  receiveMarketingEmails  Boolean
  codes                   Code[]
}

model Code {
  id                      String       @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
  createdAt               DateTime     @default(now())
  updatedAt               DateTime     @default(now())
  url                     String
  isActive                Boolean      @default(false)
  user                    User?        @relation(fields: [userId], references: [id])
  userId                  String       @db.Uuid
}
```

And you will get the following error:

```
Environment variables loaded from .env
Prisma schema loaded from ../db/schema.prisma
Datasource "db": PostgreSQL database "ezqr-1bc4831260", schema "public" at "localhost:5432"

Error: P3006

Migration `20241005124610_initial_schema` failed to apply cleanly to the shadow database.
Error:
ERROR: foreign key constraint "Code_userId_fkey" cannot be implemented
DETAIL: Key columns "userId" and "id" are of incompatible types: text and uuid.
   0: sql_schema_connector::validate_migrations
           with namespaces=None
             at schema-engine/connectors/sql-schema-connector/src/lib.rs:335
   1: schema_core::state::DevDiagnostic
             at schema-engine/core/src/state.rs:276
```

**Expected behavior**
Use native PostgreSQL fields for foreign keys (`uuid` in this case).

**Comment by infomiho** [comment]
Using `0.15.0-rc1` and this as my `User`:
```prisma
model User {
  id    String @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
  tasks Task[]
}
```
works for me 🤷 

Maybe you have old migration files? Try starting from scratch and/or updating the migrations. 

Also, could you post your `.wasp/out/db/schema.prisma` file? This is the final schema that Wasp generates - it should help us.

**Comment by amontalban** [comment]
Hey @infomiho,

Thank you for checking this that quick, you were right looks like when I started with the SQLite I didn't run `wasp clean` and that's why it didn't work.

I have validated the schema and it is as I wanted.

Thank you!
