### ISSUE TITLE
Migration from v0.14.0  to v0.15 leads Prisma errors

### ISSUE THREAD

**Issue by rajkrajpj** [wasp-lang/wasp#2365]
**Describe the bug**
.wasp/out/sdk/wasp/node_modules/.prisma/client/default.d.ts Is not updated to include the defined prisma schema tables. So starting the wasp server leads to getting error: Module '"@prisma/client"' has no exported member

**To Reproduce**
1. Go to 'https://wasp-lang.dev/docs/migration-guides/migrate-from-0-14-to-0-15'
2. Follow migration steps
3. Run wasp start or npx prisma migrate
4. .wasp/out/sdk/wasp/entities/index.ts is visibly getting errors: Module '"@prisma/client"' has no exported member "model"

**Expected behavior**
.wasp/out/sdk/wasp/entities/index.ts and .wasp/out/sdk/wasp/node_modules/.prisma/client/default.d.ts should be to have generated the defined prisma schema tables

**Screenshots**
<img width="630" alt="Screenshot 2024-11-04 at 4 19 23 PM" src="https://github.com/user-attachments/assets/7687f44c-7b89-4b0b-8478-91299ba0ad7e">

<img width="621" alt="Screenshot 2024-11-04 at 4 19 00 PM" src="https://github.com/user-attachments/assets/98aefd1b-60d8-415a-85d2-c99a1c164566">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
When using wasp version 0.14.2: The contents of node_modules/.prisma/client/index.d.ts Are being generated correctly.

When in wasp version 0.15.0: The contents are missing the defined prisma schema contents

**Comment by infomiho** [comment]
You shouldn't run `npx prisma migrate` with Wasp, only `wasp db migrate-dev`. Did you try running that command?

**Comment by Martinsos** [comment]
Does `wasp clean` maybe help?

Also, does your project compile otherwise?

Can you share althe output from the terminal that you get when you run `wasp start`?

**Comment by infomiho** [comment]
Closing for now, but let us know if you managed to replicate this issue again and we can reopen and investigate again :)
