### ISSUE TITLE
Improve instructions for running PostgreSQL via Docker to work if you have multiple Wasp projects on same machine

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#237]
Right now, if you follow our documentation on how to run Postgre via Docker, and if you have multiple Wasp apps, they will get into conflict because they are sharing the same database. We should adapt instructions so that we avoid this.

Some ideas on how to do it:
- Name the docker volume by the Wasp app.
- Name the database in Postgre by the Wasp app.

However is taking this one should research it a bit more and test it.

**Comment by rishi-kai21** [comment]
hi @Martinsos , I would like to contribute to this issue. Please can you assign it to me please :)

**Comment by Martinsos** [comment]
Sure @rishi-kai21 ! Small warning: this one requires a bit of research and testing as mentioned in the description!

**Comment by rishi-kai21** [comment]
> Sure @rishi-kai21 ! Small warning: this one requires a bit of research and testing as mentioned in the description!

thank you for letting me know :) ,your help is much appreciated . I'll work on this sooner and let you know .

**Comment by Martinsos** [comment]
This is not needed any more now that we have managed dev db.
