### ISSUE TITLE
Split dependencies into client and server dependencies

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#243]
Right now we just replicate dependencies onto both client and server. This works, but it results in warning messages in CLI and is not very efficient and it is ugly.

We should probably do smth like:
```
dependencies: {
  client: { },
  server: { }
}
```

**Comment by infomiho** [comment]
What about doing it like this, since we have `client` and `server` sections:

```js
client: {
    dependencies: [
        ("@tailwindcss/forms", "^0.5.3"),
        ("@tailwindcss/typography", "^0.5.7")
    ],
},
server: {
    dependencies: [],
},
```

**Comment by Martinsos** [comment]
Related to #734, might be worth waiting to see what happens there, maybe it solves this for us or redefines the problem somewhat differently.

**Comment by Martinsos** [comment]
I will close this for now, since code reorganization made this potentially not an issue any more.
