### ISSUE TITLE
Thoughts - Fix lint errors

### ISSUE THREAD

**Issue by cursorial** [wasp-lang/wasp#246]
There are a few linting errors in the Thoughts app currently that need cleaning up. We should do this for a couple of reasons:

- To clean the code up and get it ready to be refactored further
- To reduce excessive console output when we change a file / compile the code

The current lint output requires the following changes:

Templated files:

Not sure if there's a process for modifying these, seems like even after changing them and restarting the app the warnings persist.

`src/auth/pages/createAuthRequiredPage.js`

- Remove the unused import for `Link`
- Remove the unused variable definitions `isFetching` and `status` (or start using them)

`src/auth/useAuth.js`

- Remove the unused variable definition `setAuthToken` (or start using it)

Source files:

These should just be simple change and save.

`ext/MainPage.js`

- Remove the unused variable definition `useQuery` (or start using it)
- Remove the `togglePreviewMode` function, there is another function called `toggleInPreviewMode` that is used here instead

`ext/TagsSidebar.js`

- Remove the unused variable definitions `isFetching` and `error` (or start using them)

`ext/ThoughtsPage.js`

- Remove the unused import for `Link`
- Remove the unused variable definitions `isFetching` and `error` (or start using them)

**Comment by Martinsos** [comment]
@cursorial regarding lint errors in templates -> they need to be fixed directly in the code of wasp compiler (which is this repo, you can find them under wasp/waspc/data/Generator/templates/...).
These however might need some work done in Haskell (maybe, maybe not). I created additional feature to handle those: https://github.com/wasp-lang/wasp/issues/251 .
