### ISSUE TITLE
Fix linter errors in code that Wasp generates

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#251]
As described here (#246):

`src/auth/pages/createAuthRequiredPage.js`

- Remove the unused import for Link
- Remove the unused variable definitions isFetching and status (or start using them)

`src/auth/useAuth.js`

- Remove the unused variable definition setAuthToken (or start using it)

We should look into these templates and see if these are completely redundant or just in some situations. If completely redundant then we just remove them, if just in some situations then we do some conditional logic in Generator code to take care of this (to remove then when not needed).

**Comment by Patil2099** [comment]
I would love to work on it. @Martinsos

**Comment by Martinsos** [comment]
Hi @Patil2099 , great, feel free to take this one on!
Just keep in mind, this one will require some Haskell knowledge.
Let me know if you need any additional information on this one.

**Comment by sodic** [comment]
Fixed in #554
