### ISSUE TITLE
Thoughts - Create reusable Tag component

### ISSUE THREAD

**Issue by cursorial** [wasp-lang/wasp#254]
Tags are used in `ThoughtsPage.js`, `MainPage.js` and `TagsSidebar.js`.

They all have differing implementations.

`ThoughtsPage.js` tags are the most basic implementation. They are not clickable and are simply used to categorise Thoughts in the list view.

`MainPage.js` tags are a little more complex. They are clickable, when the user clicks on one it is removed from the list. It's styles are very similar to those in `ThoughtsPage.js`, except when it is hovered, it's styles change to indicate that clicking on it will delete it with `text-decoration: line-through;` and `cursor: pointer;`

`TagsSidebar.js` has a slightly different implementation. This renders a `Link` rather than a `div`. The styles are also a bit different for this one. The tag itself has padding instead of a margin and applies `text-decoration: none;` for some reason (not really sure why it's there, might be able to pull it out without causing any issues). On hover it becomes bold, and it can have a class of active to underline it.

The re-usable component we build will need to take into account all of the above in order to be used in all three cases. We can define a new CSS file for the Tag component to handle it's different configurations, this should include classes to handle:
- Universal layout (margin/padding, try to figure something out that works for all three)
- Universal `::before` in order to prefix `#` on `content` (might not work with `Link`s, will need to trial this)
- Hover for deletion
- Hover for bold
- Active (underline it)

We can then pass props to the component to decide which of these classes should be applied.

We can define an `href` prop. If this is defined, it should be rendered as a `Link`, else, it should be rendered as a `div`.

**Comment by Martinsos** [comment]
Great, sounds good, love the analysis! I commented in the PR, I believe that should address most of the things from here also.
