### ISSUE TITLE
Implement `wasp info` command

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#277]
`wasp info` should tell you basic info about the project `wasp info` command was run from!

It should certainly write out the project name.

It could also provide some information like: What kind of database it uses, how big is the project, when was it compiled last time, ... .

We might also consider just `wasp` command always printing if it is inside a wasp project or not, and if so, what is the name of the project.

**Comment by zant** [comment]
Hey @Martinsos! Thanks for opening issues for contributors. I would like to work on this one :)
