### ISSUE TITLE
Run Haskell CI worklow only when code inside waspc/ changes

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#291]
Since have a monorepo and haskell compiler (waspc/) is not the only thing in the repo -> instead we also have `examples/`, and we have `web/`.
However, current github actions workflow, ci.yaml, runs on any change in the repo. This doesn't make much sense, especially if for example only stuff in `web/` changes -> we don't need to build `waspc/` in that case, instead we are just wasting time and resources.

We should find a way to run relevant CI logic based on which files changed.

I found https://github.community/t/is-it-possible-to-run-the-job-only-when-a-specific-file-changes/115484/11 .
From this it sounds like we should probably create one workflow for waspc (we could rename ci.yaml to waspc-ci.yaml) and use `on.push.paths` to ensure it runs only for changes in `waspc/`, and then if needed we can create more workflows for handling other parts of the repo, e.g. we could create `web-ci.yaml` for `web/` and similar.

**Comment by rishi-kai21** [comment]
hello @Martinsos I would like to work on this issue , I'm very new to haskell and it would act as a stepping stone in letting me know more about the related subject . Please assign it to me :)

**Comment by Martinsos** [comment]
Sure @rishi-kai21 , pls go for it! This is more of a GH Actions task than Haskell, but it does touch Haskell a bit!

**Comment by rishi-kai21** [comment]
hello @Martinsos  , i was having a little trouble finding the article you have attached to the issue . As soon as I click on it ,I get transported to the github discussions page and not to the article you're referring . Would you please let me know how can I access that article or better tell me a little more about the issue and how we should tackle it .

**Comment by Martinsos** [comment]
@rishi-kai21 ah sorry, the link must have become obsolete!
I did quick googling, found this, both answers look relevant: https://stackoverflow.com/questions/70708306/github-actions-run-step-job-in-a-workflow-if-changes-happen-in-specific-folde?rq=1 .

I am happy to share more info, but I am not sure what you are interested in -> I believe the initial comments already covers the basics? Let me know if there is something specific you would like my help with!

**Comment by suyog-patil-21** [comment]
Hello @Martinsos , I would like to contribute to this issue. Please assign this issue to me.

**Comment by Zeko369** [comment]
Have at it @suyog-patil-21
