### ISSUE TITLE
[Analyzer] Remember name of referenced declaration

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#308]
If we have following Haskell types

```hs
App { defaultPage :: Page }
Page { content :: String }
```

that are both instances of `IsDeclType`, and we have following Wasp source code as input to Analyzer:

```
page HomePage { content: "Hi" }
app MyApp { defaultPage: HomePage } 
```

then the output of Analyzer will be:
```
[ ("HomePage", Decl (Page { content = "Hi"})), ("MyApp", Decl (App { defaultPage = Page { content = "Hi"}}))
```

`Decl` is actually a heterogenous type so that is why we can have a list like this, which I described in a bit of pseudocodish manner above.

As is visible in the output of Analyzer, there is no way for us to figure out that `defaultPage` from `App` is the one named "HomePage"! And this is a problem, because Generator cares about that name, it considers it to be the very name of the page and needs it to be able to correctly work with it. But, it can't because it doesn't know the name of the page that `defaultPage` is describing.

In the old Wasp AST this is solved by all references being just names (Strings), so defaultPage would be just a String that is a name of the page. But that is in itself pretty unelegant and unsafe approach.

So what could be the solution to this? Some ideas:
1. Package the declaration name together with the Page somehow -> maybe say that if Page has name field, then we will always set it to the declaration name (while defining the IsDeclType with TH), or smth like that?
2. Introduce Ref type, as permanent construct of Wasp AST, and instead of having App { defaultPage :: Page }, we would have App { defaultPage :: Ref Page }, and Ref contains the name and is properly handed by the Analyzer. Ref is really `type Ref a = (String, a)` in its core, or maybe even just `type Ref a = String`, not sure yet.

It is up to us to decide how we want this to work, what makes the most sense, what does the "name of the declaration" mean in Wasp and how it should behave. Maybe going with Ref would also easily enable referencing declarations that have not yet been declared, which is currently not supported?

**Comment by craigmc08** [comment]
Why does Generator care about the name of the page? I tried looking around the code for where it's used, but I don't know generator that well. Maybe it's possible to refactor Generator instead of adding this `Ref` type. No idea how possible this is, just throwing around an idea.

**Comment by Martinsos** [comment]
Well imagine having two pages with exactly the same content but different names -> somewhat silly, but it is something we should allow -> in that case, we do want to be able to distinguish them.

And in Generator right now -> so generator will create a React component for the HomePage and when choosing a name for that component it will actually name it HomePage..., and then we have `defaultPage` set to HomePage as in example above, it will generate a route that points to that page -> but for that it will need to know which React component to import, and that is HomePage..., so the name is important.

There are also some other situations where this could be important.

If we assume names are important -> does `Ref` sounds reasonable to you, or would you do it in some other way? What do you dislike about `Ref`?

**Comment by craigmc08** [comment]
I see, that makes sense. `Ref` sounds like a good option then, because solves this problem and out-of-order references. I think `newtype Ref a = Ref { unref :: String }` should be used, since having `(String, a)` brings back the ordering problem.

The implementation will require changing evaluator code a bit:
- `decl` TypedExprEvaluation should have type `TypedExprEvaluation (Ref a)` (and implementation just returns a ref with the name of the variable).
- `makeDeclType` code generator should no longer allow arbitrary `IsDeclType a => a` being treated as `KDecl :: WaspKind`. Should instead consider only `IsDeclType a => Ref a` as `KDecl`.

These changes means that (from your first example in issue) `data App = App { defaultPage :: Ref Page }` instead.

**Comment by Martinsos** [comment]
Awesome @craigmc08 -> yes, I think this is going in the right direction! Thanks for these notes, let's leave it at this for now then, it should be enough information for whoever picks up this issue to get this done.
