### ISSUE TITLE
In examples/, modify example apps so that they have links to the Wasp source code

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#323]
When users are looking at Wasp example apps, they have no idea where to find the Wasp source code from which these apps were built! We could add, to each app, a banner at the bottom (or top), or some link, that says "check out the Wasp source for this app here".

**Comment by h4r1337** [comment]
Do you mean something like this [https://github.blog/2008-12-19-github-ribbons/](https://github.blog/2008-12-19-github-ribbons/)?

**Comment by h4r1337** [comment]
I think I can do that...
Is that also required for all pages? like in `example/thoughts` there is a main page and login/signup pages so, should I add that to all of the pages or just the main page?

**Comment by Martinsos** [comment]
Sounds good, pls do give it a try!
Hmmm, I am not sure actually, I haven't thought about it. It might be a bit tricky to do it for all pages in Wasp, since we don't have an easy way to do "layouts" yet. You could do it by having your own wrapper in which you wrap all of the React components though.
What do you think is better, having it only on homepage or on all pages? I am a bit tempted to have it everywhere, so it is easy for users to jump to the code at any point. But I am ok with whatever approach you pick, homepage is also good.

**Comment by shayneczyzewski** [comment]
Hey gang, I added this simple example banner a while back: https://github.com/wasp-lang/wasp/blob/a0b7477d19ff1ab70215ade454a81406720c6997/examples/waspleau/ext/WaspExampleHeader.js that was integrated into to these sample apps:
- https://waspleau.netlify.app/
- https://waspello.netlify.app/

Feel free to use it as inspiration, or throw it away :D

**Comment by h4r1337** [comment]
I am not familiar with wrapper components, can I add it manually for now?
will think of some way to inherit from a base layout component later...

**Comment by Martinsos** [comment]
Go for whatever you feel comfortable with and we can then discuss it in the PR!

**Comment by h4r1337** [comment]
Just saw that this issue is not yet closed. Can we close this?

**Comment by Martinsos** [comment]
Yes you did this one, let's close it!
