### ISSUE TITLE
Login and Signup forms cannot be customized - they look ugly

### ISSUE THREAD

**Issue by matijaSos** [wasp-lang/wasp#326]
**Is your feature request related to a problem? Please describe.**
When building out Waspello I was trying to make it look similar to Trello and then I realised that our Login & Signup forms cannot be customized (except accidentally with some global css, which happened in my case).

**Describe the solution you'd like**
I see two main ways to address this, which might even be combined:
* Login/Signup components offer props for developer to use (e.g. `width`, `height`, etc?)
* It is documented which classes developer can change to affect the looks of the forms

I believe this is a problem that appears with every solution that offers ready-to-use components - we should investigate and see what are the best practices for dealing with this.

**Comment by sodic** [comment]
@infomiho This is done, right? Or needs to be rephrased?

**Comment by infomiho** [comment]
They are no longer ugly! And we allow certain customisation via the component props. So, I'd close this since we have other issues like #1251
