### ISSUE TITLE
When installing an NPM dependency, Wasp dev has to specify an exact version (instead of 'npm install package)'

### ISSUE THREAD

**Issue by matijaSos** [wasp-lang/wasp#328]
**Is your feature request related to a problem? Please describe.**
As the title describes, it is a bit cumbersome to have to search for the latest npm package version number and write it down.

**Describe the solution you'd like**
I guess we could have something similar to `npm install package_name`, e.g. `wasp install package_name` which would then take care of it the same way `npm install` does.

**Comment by sodic** [comment]
We no longer require users to write their package versions in the wasp file. Instead, they write it in `package.json` (or they call `npm install`): https://wasp-lang.dev/docs/project/dependencies#adding-a-new-dependency

So I'd say this is done.
