### ISSUE TITLE
When building the client for deployment, API requests are invalid if wasp dev puts `/` at the end of the backend server URL

### ISSUE THREAD

**Issue by matijaSos** [wasp-lang/wasp#332]
In [Deploying web client (frontend)](https://wasp-lang.dev/docs/deploying#deploy-to-a-heroku-app) step, if dev puts a trailing `/` at the end of the url to the backend server, the API calls will be invalid, since it will have an extra `/` in it (e.g. `https://waspello.heroku.app//auth/me`).

It happened to me while deploying Waspello - we should either warn in the docs against it, or make the system (build script I guess?) robust to it.

**Comment by ankeshp03** [comment]
Hi, can I work on this issue?
