### ISSUE TITLE
[example/Waspello] Add link to Waspello source code

### ISSUE THREAD

**Issue by matijaSos** [wasp-lang/wasp#340]
Since Waspello is a demo app, it would be cool to add some kind of e.g. banner with the link to Waspello source code: https://github.com/wasp-lang/wasp/tree/master/examples/waspello

That way when somebody is checking out Waspello demo app they can quickly also see the code!

**Comment by h4r1337** [comment]
Isn't this issue fixed by #649 ?

**Comment by Martinsos** [comment]
You are right, thanks @h4r1337 !!! Closing it.
