### ISSUE TITLE
JavaScript linting issues

### ISSUE THREAD

**Issue by vicnicius** [wasp-lang/wasp#345]
**Describe the bug**
While running the [waspc example app](https://github.com/wasp-lang/wasp/tree/master/waspc/examples/todoApp) I noticed the web app server outputs some linting errors. They seem to be coming from both, [the example's code](https://github.com/wasp-lang/wasp/blob/master/waspc/examples/todoApp/ext/pages/Main.js) as well as [the generated code](https://github.com/wasp-lang/wasp/blob/master/waspc/data/Generator/templates/react-app/src/auth/pages/createAuthRequiredPage.js).

**To Reproduce**

Run the steps as described in https://github.com/wasp-lang/wasp/tree/master/waspc#run-example-app.

**Expected behavior**

First, there shouldn't be any lint errors. On the user code side, it is fine to let the user deal with them, but at least the example code should look ok. On the generated code side, I don't see a way where code could be generated following a certain set of user-defined rules, since some can't be enforced automatically. So I was wondering if it doesn't make sense to add some "lint" ignoring rules to the generated code (that the user could later remove if they want to eject or something). Alternatively, we could change the dev server configuration to ignore the generated code paths. 

**Screenshots**
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/1326024/138553404-e4fffedd-951f-4b1a-8965-88f911f45be1.png">

**Additional Context**

I'm pretty new to the project so I'm not sure how much this makes sense. In any way, I'm happy to help send a PR to fix it.

**Comment by sodic** [comment]
Closing this as it's covered by #347 and #348.
