### ISSUE TITLE
Update prisma from v2 to v3

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#359]
might fix #356

**Comment by shayneczyzewski** [comment]
Did a quick test, and the upgrade to `3.8.1` does seem to fix db studio error. 🎉 

I tried a few basic things and overall it seems to work so far. The main thing I noticed is when you `db migrate-dev` with existing migrations, it seems to ignore them and try to re-create them all as new migrations as the underlying SQL changes a bit. Tried on todoApp and realworld.

I'll see if I can find some v2 to v3 migration guide that may explain recommended procedure. 👍🏻

**Comment by shayneczyzewski** [comment]
https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-3 seems to cover breaking changes, not the upgrading of legacy migrations specifically.

**Comment by Martinsos** [comment]
Hm ok, doesn't sound too terrible! We can just ignore the migrations I guess, and we will recreate them as needed.

I am interested in figuring out if PSL changed significantly, so we can update our PSL compiler if needed. But I don't see any big changes, so probably best not to worry about it for now and we can do a separate effort later, of ensuring that our PSL compiler is up to date.

**Comment by shayneczyzewski** [comment]
Trying to get this answered in Prisma Slack:

> Hey everyone! I had a question about upgrading from Prisma 2.22.1 to the latest version (3.9.1). It seems when I run migrate dev after upgrading, it wants to create a new migration on existing SQLite and PostgreSQL databases. For SQLite, it wants to recreate all my tables (by creating a new migration basically with -- RedefineTables and -- RedefineIndex). For PostgreSQL, it does -- DropForeignKey, -- AddForeignKey, and -- RenameIndex (that I have seen so far).
My main question is, is this expected and I should just add the new migration when upgrading (vs some other approach)? Any other tips/considerations to help migrate existing databases between these major versions? I did see this: https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-3 Thanks!
