### ISSUE TITLE
Stan found 253 observations.

### ISSUE THREAD

**Issue by philderbeast** [wasp-lang/wasp#363]
Please review and address the observations of [stan](https://github.com/kowainik/stan).

[stan.html.zip](https://github.com/wasp-lang/wasp/files/7532341/stan.html.zip)

```
> cabal install stan
waspc> stan report

           Stan's Summary:
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓
┃ Analysed modules             ┃ 152    ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━┫
┃ Analysed Lines of Code       ┃ 9550   ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━┫
┃ Total Haskell2010 extensions ┃ 19     ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━┫
┃ Total SafeHaskell extensions ┃ 0      ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━┫
┃ Total checked inspections    ┃ 44     ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━┫
┃ Total found observations     ┃ 253    ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━┫
┃ Total ignored observations   ┃ 0      ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━┫
┃ Project health               ┃ 61.36% ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┻━━━━━━━━┛

  ⓘ Report is generated here -> stan.html
```

**Comment by Martinsos** [comment]
Connected with https://github.com/wasp-lang/wasp/issues/307 .

**Comment by Martinsos** [comment]
Question here: it says on Stan's README that it should be compiled with the same version of GHC as we are using for the project that is being analyzed.

Wasp is using Stack, and I personally have Stack installed on my machine in a standalone manner, not via ghcup but via Stack's installer script. Stack is managing its own GHC and not using system version.

What is the best way for me to ensure that I use version of Stan compiled with the correct version of GHC?
What if I have projects that use different versions of Stack -> how do I then run Stan for them? I would be ideal if I could install Stan separately for each project, similar like you can do with `npm` for dev dependencies.

**Comment by philderbeast** [comment]
From https://github.com/kowainik/stan#hackage, we could install a `stan-8.10.7` when build wasp with `ghc-8.10.7`:

```
$ cabal v2-install stan \
    -w ghc-8.10.7 \
    --install-method=copy \
    --overwrite-policy=always \
    --program-suffix=-8.10.7
```

**Comment by Martinsos** [comment]
Right, but I would need to manually install that version of stan, and would need to make sure I update it if I change resolver at some point. Even worse, what if I have two projects, using different versions of Stack? How would I then ensure I use correct version of stan?

**Comment by philderbeast** [comment]
There's many ways to skin this cat! I've tried a few:

* Use cabal to install tools.
* Use stack to install tools but then you'd likely want a tool specific `stack-for-tool.yaml`.
* Use nix to ensure a consistent development tool chain and environment.

I've been enjoying ghcup as library author flipping between ghc versions. For a dev team working on a product I'd ask around for recommendations.

**Comment by Martinsos** [comment]
Hm I will ask on r/haskell!

Regarding the first approach, using cabal to install tools -> what happens if you have two cabal projects that use different versions of GHC? How do you make sure you use correct version of Stan for each of them?

Regarding the second approach, using a tool specific `stack-for-tool.yaml` -> could you give me some more details / pointers here, what does that mean?

Nix -> sounds like the best solution? I know people say it is hard to learn but if it can bring me this kind of consistency then it sounds very appealling.

We have both libraries and products so I would love to figure out the best workflow for both.

**Comment by philderbeast** [comment]
> Regarding the second approach, using a tool specific `stack-for-tool.yaml` -> could you give me some more details / pointers here, what does that mean?

I've added a commit showing how this can be done, 67171821bc5ada94e46a25e55ddb4b75fbfe4177.

**Comment by Martinsos** [comment]
> > Regarding the second approach, using a tool specific `stack-for-tool.yaml` -> could you give me some more details / pointers here, what does that mean?
> 
> I've added a commit showing how this can be done, [6717182](https://github.com/wasp-lang/wasp/commit/67171821bc5ada94e46a25e55ddb4b75fbfe4177).

Awesome, I will comment on the PR!

**Comment by Martinsos** [comment]
Not fixed yet! We have stan running now, but we haven't fixed any warnings yet.
We should fix them all, and once we do, we should also add stan to the CI.
