### ISSUE TITLE
Create React component for an image (with an optional caption) to use in our blog/docs

### ISSUE THREAD

**Issue by matijaSos** [wasp-lang/wasp#410]
Right now we don't have a canonical way to add an image with a caption to our blog articles, every time we do some combo of md or HTML, and caption is either a <p></p> or <figcaption>... .

We should create a React component that standardizes this and then we can use that in all the places where we require an image.

**Comment by himanshu007-creator** [comment]
Hey, I would like to work on this issue. Can you guide me in a bit more detail?!
I can make the react component. but where to add that file and how to integrate it in other places across the project.

**Comment by matijaSos** [comment]
@himanshu007-creator sure! The right place to put would be here: https://github.com/wasp-lang/wasp/tree/master/web/blog/components, and we would use it in a very similar way to how e.g. `<InBlogCta/>` is used (you can check the [latest blog post](https://github.com/wasp-lang/wasp/blob/master/web/blog/2021-12-02-waspello.md?plain=1#L11) to see how it is imported and used).

The main requirement is for image to be centered and have an (optional) caption. The content of the component would probably be something like [this](https://github.com/wasp-lang/wasp/blob/master/web/blog/2021-12-02-waspello.md?plain=1#L171)

How does this sound?

**Comment by himanshu007-creator** [comment]
i will give it a shot
