### ISSUE TITLE
.env file in Wasp dir gets copied into build dir when running `wasp build`

### ISSUE THREAD

**Issue by shayneczyzewski** [wasp-lang/wasp#413]
**Describe the bug**
While creating the Waspleau example app, I noticed my local .env file was being copied into the ./wasp/build/server directory when I ran `wasp build`.

**Expected behavior**
This file should not be getting copied over.

**Screenshots**
![image](https://user-images.githubusercontent.com/523636/147096924-5b21666f-3770-4dc6-8f15-f2dda2c06d64.png)

**Comment by faassen** [comment]
There appears to be deliberate code in place that copies over dotenv, in `ServerGenerator`'s `genDotEnv`.
I can simply remove this code, but why was it there in the first place?

There is also cleanup code that seems to ensure any old `.env` file is removed.

**Comment by Martinsos** [comment]
Ah yes - the important thing is that file should be copied, but only during development -> not during building the app to be deployed!
So it comes down to checking if app is being built or not (there is isBuilt flag in AppSpec) and based on that conditionally copying or not copying the .env file.
