### ISSUE TITLE
Investigate Prisma client initialization error on first start after clean

### ISSUE THREAD

**Issue by shayneczyzewski** [wasp-lang/wasp#427]
We should look into the following error:

```
Server (stderr): Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
Server (stderr): In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
Server (stderr):     at new PrismaClient (/Users/shayne/dev/wasp/waspc/examples/todoApp/.wasp/out/server/node_modules/.prisma/client/index.js:3:11)
Server (stderr):     at createDbClient (file:///Users/shayne/dev/wasp/waspc/examples/todoApp/.wasp/out/server/src/dbClient.js:8:24)
Server (stderr):     at file:///Users/shayne/dev/wasp/waspc/examples/todoApp/.wasp/out/server/src/dbClient.js:17:18
Server (stderr):     at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
Server (stderr):     at async Loader.import (internal/modules/esm/loader.js:166:24)
Server (stderr):     at async Object.loadESM (internal/process/esm_loader.js:68:5)
Server (stderr): [nodemon] app crashed - waiting for file changes before starting...
```

This can happen in the examples/todoApp, if you `wasp clean` and then `wasp start` you actually still need a `prisma generate` to generate the prisma client it seems. While `wasp db migrate-dev` can do this too, it is not the root cause.

If you go into wasp/waspc/examples/todoApp/.wasp/out/server and run the following, you can see it is an initial Prisma client generation issue and not a migration issue due to prisma.schema changes:

```
$ npx prisma generate --schema ../db/schema.prisma
Environment variables loaded from .env
Prisma schema loaded from ../db/schema.prisma

added 2 packages, and audited 3 packages in 1s

found 0 vulnerabilities

added 2 packages, and audited 5 packages in 668ms

found 0 vulnerabilities

✔ Installed the @prisma/client and prisma packages in your project

✔ Generated Prisma Client (2.22.1) to ./node_modules/.prisma/client in 105ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client

import { PrismaClient } from './node_modules/.prisma/client'
const prisma = new PrismaClient()
```

After this, `wasp start` works. Perhaps we need to check/run `prisma generate` when _first_ building the app at the Node/NPM level?

**Comment by Martinsos** [comment]
In theory, we could treat this as code generation, from schema.prisma to some code, and then make it part of the Generator -> Generator would run `prisma generate` as needed to generate code from schema.prisma. That could be every time that `compile` is called, with optimization of using checksum to avoid doing it when not needed.

**Comment by shayneczyzewski** [comment]
Did some thinking and testing on this today, and came up with a few thoughts:

- Running `prisma` commands requires the `npm install` process to be done already. I don't think this is an assumption or process (forcing it to install ourselves) we want to build into the Generator. Therefore, we'd probably want to bolt it on to Start/Watch in CLI.
- We likely only want `db migrate-dev` to generate the Prisma client, since it is super easy to get errors without it. Consider if in their schema they changed the type of some column from String to Int and we automatically regenerated the client but they did not migrate. That would cause their app to crash at runtime. Therefore, doing this during Watch is not ideal.
- Lastly, even considering a limited use case like "only on Start when a schema checksum is missing" to solve this exact error actually hides the fact they may actually also need to migrate too. So they wont see that error, but instead things will still strangely fail on the backend, which feels worse.

Do nothing with that error and letting the db migrate warning cover this scenario once it is merged seems like the best plan forward to me. Make sense to you @Martinsos? Thanks!

**Comment by Martinsos** [comment]
I will address the points from above as if they were numbered from 1 to 3.

1. Ah that is a good point that I forgot about! There is however a way to call commands from the Generator without having to assume that `npm install` was called, by using `npx`. You can do `npx prisma generate` (smth like this) and it will run `prisma generate` while using the already installed `prisma` binary from local node_modules, or if not, installing it first if needed. There would still have to be assumption of code being generated first, but I think that is fine. I am guessing we could call it from top function in the Generator, or Db Generator.
2. This is what I am not sure about, I had a different view on it, but it might be wrong. The way I saw it is that we want to get those errors, that it is a good thing. Let's imagine Wasp is using Typescript, and we modify schema.prisma, so that our entity uses String now instead of Int for a certain field. I imagine I would want to see errors based on this? So, if `prisma generate` is run upon this change of mine, Prisma library will get updated to reflect the changes, and TS will warn us in the code of all the places where we are now expecting String but instead passing Int. So that sounds good to me, it gives that feedback loop that we expect from a typed language. If I wouldn't run it, I would have no idea how to update my app to work with this change I made. When I am done fixing the errors that `generate` made, I could go to actually doing a migration, if I am ready for that. Or maybe I am not, maybe first I want to make some more changes to the entity, and again errors from `generate` will guide me. But what I am focusing on here is the experience of getting and fixing type errors, not on the app that is running live due to `wasp start`. Ok, so let's think about that -> yes, it will crash. But that is also ok, it should crash since it is not working any more! So I imagine that is ok? I don't understand the benefits of it not crashing -> so let's say we don't run prisma generate, and it is not crashing, but it is not crashing because it is really an old version of code (since we didn't update it with Prisma generate) -> that doesn't seem very helpful then? Hmmmmmm
3. I would do it on every compile! But this again comes down to the point (2) above.

It seems to all come down to figuring out the relationship between generate and migrate in the development lifecycle. I am currently of opinion that generate should be called on any change in schema.prisma as its product is actually code that is part of our codebase and therefore we need it to be able to get type errors and other errors. While I see migrate as a separate step. But, I am not 100% sure about this, and am thinking that knowing more about specific use cases might help.

I took a look at what Prisma says: https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/generating-prisma-client, and they say:

> Important: You need to re-run the prisma generate command after every change that's made to your Prisma schema to update the generated Prisma Client code.

So I think that fuels the idea that we should run it on every schema.prisma change! They would probably do it if they could.

**Comment by shayneczyzewski** [comment]
Ahh, yeah, I believe you are correct @Martinsos :) Not quite sure why I was so worried about preserving the runtime behavior, and agree it is better to have a broken, consistent app instead of an inconsistent running version for sure. I think it does make sense to view prisma client generation in the context of normal Wasp app generation (even if a potentially expensive step) and not in relation to the state of the database/migration commands. 👍🏻 We are on the same page there now after reframing my thinking around the ultimate purpose.

It would be nice in the console, however, if errors could guide them to all the places things are broken before we have TS support. I'll try it out and see what comes of it, thanks!

**Comment by Martinsos** [comment]
@shayneczyzewski great!

Errors in console -> ah yes, well for that we probably need typed language like TypeScript though, right? Some stuff is caught by React, but I doubt it will catch any of this stuff. But as you said let's see what turns out.

**Comment by shayneczyzewski** [comment]
I should have fleshed that last line out more, apologies - I was primarily thinking if they edited entities while running they may see places on frontend/backend where it breaks in server/client messages, likely just type errors at point of use, but not sure if we will see those even or if Prisma will just be dying when fetching data from the db. We shall see!! :D 

But yes, in a generator output world it would be neat to see what we can do in the future with TS!

**Comment by shayneczyzewski** [comment]
Found some `npx` behavior we need to keep in mind as I was starting to play with this. If you remove your `node_modules/` dir in a generated project and `prisma` from `npx` cache, so you are in a state with no Prisma installed, something like:

```
wasp/waspc/examples/todoApp/.wasp/out/server $ npx prisma version
Need to install the following packages:
  prisma
Ok to proceed? (y)
```

It will try to install `prisma` for you into your global `npx` cache, and give you the latest version:
```
Environment variables loaded from .env
prisma                  : 3.8.1
@prisma/client          : 2.22.1
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at ../../../../../../../../.npm/_npx/2778af9cee32ff87/node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at ../../../../../../../../.npm/_npx/2778af9cee32ff87/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at ../../../../../../../../.npm/_npx/2778af9cee32ff87/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at ../../../../../../../../.npm/_npx/2778af9cee32ff87/node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f
Studio                  : 0.452.0
```

However, if you have already `npm install`ed the generated project and have a `node_modules` binary it can use, you get it:
```
Environment variables loaded from .env
prisma               : 2.22.1
@prisma/client       : 2.22.1
Current platform     : darwin
Query Engine         : query-engine 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 60cc71d884972ab4e897f0277c4b84383dddaf6c (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : 60cc71d884972ab4e897f0277c4b84383dddaf6c
Studio               : 0.379.0
```

Nothing super shocking in those two cases I guess, but if a user tries Wasp right now and has no Prisma installed, and runs any of our existing Prisma commands (like `wasp db migrate-dev`) before they `npm install` (likely via `wasp start`) they will get prompted to install Prisma, and it will use the latest version. :/ The Prisma commands will then either break or put them into a funky state until they finally run `npm install`, and then `npx` will use the correct local `node_modules/` version instead. I wish there was a way to force `npx` to run `node install` when it sees a `package.json` but no `node_modules/` dir.

We probably need to figure out a solution for this since I can imagine there will be some new users who do not have Prisma installed when trying us. If Prisma client generation becomes part of the generator, it will run before `npm install` happens during `wasp start` on a clean setup. 

- One option is we can change our commands to be `npx prisma@2 blah` to ensure our major version is correct at least, but in the missing Prisma example it will install the wrong minor to their global `npx` cache.
- Another option is to try and detect that we have not yet `npm install`ed before any commands rely on local `npx` binaries, and then install it first.

Ok, that is a lot of really intricate info, please let me know if it does not make sense. :) The TLDR is if a user has no Prisma installed locally, and they have a clean project without node_modules, running any Prisma command will prompt them to install the latest version first and result in undefined behavior until a local version is available.

**Comment by Martinsos** [comment]
Thanks for this detailed explanation @shayneczyzewski !

Interesting hm, I was expecting npx to install prisma based on the local package.json even if node_modules/ is missing, not to resort to installing it as a global binary.

I agree with the possible solutions you described, I will to rephrase them here just to make sure we are on the same page:
1. It would be great if we could tell npx to install based on local package.json even if node_modules/ is missing. Maybe there is a flag for that? Or can we maybe trick it into that somehow, buy somehow initializing node_modules in a cheap way? Maybe that is not very dirty but ensures our npx's work correctly?
2. As you said, we can specify prisma version in our commands. I agree that using just major version is not great, but on the other hand we could use major.minor? And ensure the same major.minor is used on all places?
3. Running `npm install` if any command uses `npx` -> well that also makes sense I think. Similar to first command but not as lightweight. However why would they not want to have `npm install` run? If you don't run it, you don't have all the libraries installed. Which is not great if you are looking at the code, maybe, and you want to see type errors and similar. But it doesn't matter if you are running individual commands. Hmmmmm. Well I think even this might be an ok option.

**Comment by Martinsos** [comment]
Reading about `npx` a bit more right now, I conclude it is mostly meant to run binaries from the local node_modules, not to install anything into it -> instead, when it needs to install something (because it is missing in local node_modules), it does so in some relatively global place. So `npx` might not be the solution to this it seems. I am not 100% giving up on it, maybe we can somehow trick it via some flags, but I am not sure anymore that it is the best solution. Hm hm hm.

**Comment by Martinsos** [comment]
I read the docs a bit and only useful flag for `npx` I found (actually for `npm exec` which is alternative to `npx`) was `offline`, which forces it to fail if binary is not already installed on the machine -> so e.g. if we called `npm exec` with `offline` flag and exact version of the binary, then we can be sure that it won't install it globally if it is not already present either in the project via node_modules or globally. Which means we could give that a try, see if error happens, if it does, then we call `npm install`, and then we try again. Just an idea.

**Comment by shayneczyzewski** [comment]
Thanks for the reply @Martinsos. Yeah, that is the feeling I am getting from `npx` too. Either you installed it already locally, or not, but it won't handle local install for you just global if missing.

1) I checked the docs for it https://www.npmjs.com/package/npx and it doesn't seem to have any install related. We could override the command not found behavior perhaps, but that starts feeling fragile. Additionally, we don't want to use a global one accidentally either, so I think we want to force local use (probably via `npm install` somehow).

2) For some reason my initial testing seemed to only work with major, but yeah I think we can change the command to `prisma@2.22.1` and pin it to our package.json file. That isn't that bad. 🤔 

3) The main concern I have there is we may be paying the install price each time without benefit unless we can better detect the actual status somehow.

**Comment by shayneczyzewski** [comment]
> I read the docs a bit and only useful flag for `npx` I found (actually for `npm exec` which is alternative to `npx`) was `offline`, which forces it to fail if binary is not already installed on the machine -> so e.g. if we called `npm exec` with `offline` flag and exact version of the binary, then we can be sure that it won't install it globally if it is not already present either in the project via node_modules or globally. Which means we could give that a try, see if error happens, if it does, then we call `npm install`, and then we try again. Just an idea.

That is an interesting idea! I will try it out, thnx 👍🏻

**Comment by Martinsos** [comment]
Yeah, running `npm install` each time would be too expensive / slow, we need some way to figure out if needs to be running or not.

Maybe `npm exec` with `offline` flag is the solution for that.

Keep in mind that `npm exec` with `offline` flag will use global version of package if installed. So we need to use the very specific version of package if we want to avoid potential discrepancies. If we use the exact version, a.b.c, then we should be completely safe. If we do a.b we are relatively safe but risking it a bit.

**Comment by shayneczyzewski** [comment]
Yep makes sense! I plan to try and see if I can get some fallback behavior (via `offline` or otherwise) while specifying `prisma@2.22.1` everywhere. Thanks for the brainstorm on ideas for this issue 👍🏻 I think we will end up being far safer with db commands this way too (by version pinning them).
