### ISSUE TITLE
[example/Waspello] Show a nice error message when email address is unavailable during signup

### ISSUE THREAD

**Issue by matijaSos** [wasp-lang/wasp#429]
Right now we just show "error 500" console.error() popup. We should show a designed window with a helpful msg, e.g. "This email address is not available". Also, consider if this can be added to Wasp by default, so the developer doesn't have to reimplement it for every app.

**Comment by makinox** [comment]
Is any problem if I work on this?

**Comment by makinox** [comment]
Right now signup errors are showing like this, I think is helpful enough, or you think it has to be more specific? Or replace alerts with a label tag below the input?

<img width="444" alt="Screenshot 2022-10-05 at 7 29 57 PM" src="https://user-images.githubusercontent.com/24579681/194187606-205d07cc-e9f5-4eaf-8543-522945918000.png">

**Comment by Martinsos** [comment]
That actually sounds good enough! I guess we must have improved it in the meantime. Should we close this issue then @makinox ?

**Comment by makinox** [comment]
Yes I think so. 🙌👍
