### ISSUE TITLE
Broken link for migrating from sqlite-to-postgresql in error message

### ISSUE THREAD

**Issue by faassen** [wasp-lang/wasp#436]
**Describe the bug**

I'm working with the latest trunk of Wasp and when I build, I get an error message that points to a URL that is broken:

```
- SQLite (a default database) is not supported in production. To build your Wasp app for production, switch to a different database. Switching to PostgreSQL: https://wasp-lang.dev/docs/language/features/#migrating-from-sqlite-to-postgresql .
```

**To Reproduce**

- Checkout Wasp
- `stack exec wasp-cli new TestProject`
- `cd TestProject`
- `stack exec wasp-cli build`

**Expected behavior**
I expect a link that tells me what to do.

**Comment by faassen** [comment]
The correct link appears to be here: https://wasp-lang.dev/docs/language/basic-elements#migrating-from-sqlite-to-postgresql

**Comment by Martinsos** [comment]
Good catch, however this is actually ok, it will work correctly once we release both new code and new docs, which will happen at the same time!
