### ISSUE TITLE
Allow numbers in names of projects

### ISSUE THREAD

**Issue by faassen** [wasp-lang/wasp#438]
Wasp is rather strict with project names I found when I tried `wasp new TestProject2`. I think it's likely I'm not the only one who will want to do so especially early on, and it may even be legitimate for an application to contain 2 in its name, so I think we should support this.

**Comment by Martinsos** [comment]
Ah yeah we already had a couple of iterations with this, but it seems like we are still not there! Makes sense, we should support this.
