### ISSUE TITLE
[Blog] Individual post - Put some contrasting box around blog intro / CTA part, to distinguish it visually from the content

### ISSUE THREAD

**Issue by matijaSos** [wasp-lang/wasp#462]
Right now, it is hard to distinguish CTA from the text:

<img width="742" alt="wasp_blog_post_cta" src="https://user-images.githubusercontent.com/1536649/153841839-99339b42-a5ac-4fe8-ab46-eceba91b5b9a.png">

**Comment by codingmickey** [comment]
I would love to work on this

**Comment by codingmickey** [comment]
is it okay to just pr before asking for working on it?

**Comment by Martinsos** [comment]
> is it okay to just pr before asking for working on it?

Sure! It is good though to write you are working on it, just so the others know, plus it can be good to ask upfront about certain approaches that might be less clear, to make sure PR has a better chance of getting accepted.
