### ISSUE TITLE
Better output during setup phase for compilation

### ISSUE THREAD

**Issue by faassen** [wasp-lang/wasp#465]
`writeWebAppCode` which is invoked during compilation now has grown a seperate `runSetup` phase. Currently it can only return warnings and errors, which are displayed to the user.

For better UI on the command line, it would also be useful to output the following two messages (in standard way the CLI already uses):

* Start  messages ("Starting npm install")

* Success messages ("npm install successfully concluded")

**Comment by Martinsos** [comment]
Done by @faassen !
