### ISSUE TITLE
Ensure FileDrafts to be written during generation are unique per path

### ISSUE THREAD

**Issue by shayneczyzewski** [wasp-lang/wasp#517]
There was a latent bug which was recently discovered by end-to-end testing as we were optimizing the writing of `FileDraft`s during the generation process. We had two different functions that were generating a `server/src/server.js` file. It was not noticed before as the correct one must have been always written last. When switching to a Map-based implementation with paths as the key, we collapsed both into the problematic version where an unprocessed template output difference was detected.

Goal: We should have an explicit check before writing `FileDraft`s that ensures there are no duplications per path. If any are found, we should `error` out.

**Comment by shayneczyzewski** [comment]
A bit more context:

We use `FileDraft`s as the primary mechanism to write files to disk in the generated Wasp output project (under `.wasp/out`). There are a few different types, but the main operation they all do is `write` where they sync information to disk. https://github.com/wasp-lang/wasp/blob/main/waspc/src/Wasp/Generator/FileDraft.hs#L30

Wasp is smart, and keeps track of when `FileDraft`s have changed, and only writes those that are updated.

The main place where this generation and writing happens is here:
- https://github.com/wasp-lang/wasp/blob/main/waspc/src/Wasp/Generator.hs#L44
- https://github.com/wasp-lang/wasp/blob/main/waspc/src/Wasp/Generator/WriteFileDrafts.hs#L29-L57

The goal of this PR is to ensure when we process `FileDraft`s, that they are unique **per destination file path**.

**Comment by InfiniteVerma** [comment]
I'd like to work on this.

**Comment by shayneczyzewski** [comment]
Awesome @InfiniteVerma feel free to give it a go and ping if you have any questions or hit any snags!

**Comment by InfiniteVerma** [comment]
I suspect is no test case for duplicate destination paths. Can one be added for this scenario?

**Comment by shayneczyzewski** [comment]
> I suspect is no test case for duplicate destination paths. Can one be added for this scenario?

Hey @InfiniteVerma I see you already have a PR, nice! I will take a look at that today. There is no test case for this, as we typically add the new test cases alongside the new code that fixes it. I can point you in the right direction and we can come up with the best place to test your additions. Thanks!
