### ISSUE TITLE
Falling back to older state than requested index-state.

### ISSUE THREAD

**Issue by philderbeast** [wasp-lang/wasp#525]
I'm not sure that this is working as intended as cabal seems happy to ignore it (or maybe cabal has a good reason but this is not well explained?).

https://github.com/wasp-lang/wasp/blob/a4a2b03a81fb84c691b2d6a5a8ce0c8948f4d22d/waspc/cabal.project#L22

```
> waspc on main ◦ cabal build all --enable-tests
Warning: Requested index-state 2022-03-22T14:16:26Z is newer than
'hackage.haskell.org'! Falling back to older state (2022-03-14T21:07:44Z).
Resolving dependencies...
Build profile: -w ghc-8.10.7 -O1
```

**Comment by philderbeast** [comment]
If I update then all is good, the falling back is no longer happening. Should we note of this in the build instructions?

```
> waspc on main ◦ cabal update
Downloading the latest package list from hackage.haskell.org
Updated package list of hackage.haskell.org to the index-state 2022-03-25T09:26:29Z
To revert to previous state run:
    cabal v2-update 'hackage.haskell.org,2022-03-14T21:07:44Z'
> waspc on main ◦ cabal clean
> waspc on main ◦ cabal build all --enable-tests
Resolving dependencies...
Build profile: -w ghc-8.10.7 -O1
```

**Comment by philderbeast** [comment]
Looking at `cabal help update` it looks like I can update to a date but this is not exact.

```
> waspc on main ◦ cabal update hackage.haskell.org,2022-03-22T14:16:26Z
Downloading the latest package list from hackage.haskell.org
Package list of hackage.haskell.org is up to date at index-state 2022-03-25T09:26:29Z
```

```
> cabal help update
Updates list of known packages.

Usage: cabal update [FLAGS] [REPOS]

For all known remote repositories, download the package list.
...
Examples:
  cabal update
    Download the package list for all known remote repositories.

  cabal update hackage.haskell.org,@1474732068
  cabal update hackage.haskell.org,2016-09-24T17:47:48Z
  cabal update hackage.haskell.org,HEAD
  cabal update hackage.haskell.org
    Download hackage.haskell.org at a specific index state.

  cabal new update hackage.haskell.org head.hackage
    Download hackage.haskell.org and head.hackage
    head.hackage must be a known repo-id. E.g. from
    your cabal.project(.local) file.
```

**Comment by philderbeast** [comment]
A bit more exploration. Between each break in code snippets here, I'm deleting `~/.cabal/packages/hackage.haskell.org/`.

```
> cabal update hackage.haskell.org,2022-03-22T14:16:26Z.
Downloading the latest package list from hackage.haskell.org
Updated package list of hackage.haskell.org to the index-state 2022-03-22T14:16:26Z
> cabal update
Downloading the latest package list from hackage.haskell.org
Package list of hackage.haskell.org is up to date at index-state 2022-03-22T14:16:26Z
```

```
> cabal update
Downloading the latest package list from hackage.haskell.org
Updated package list of hackage.haskell.org to the index-state 2022-03-25T14:04:30Z
> cabal update hackage.haskell.org,2022-03-22T14:16:26Z
Downloading the latest package list from hackage.haskell.org
Package list of hackage.haskell.org is up to date at index-state 2022-03-25T14:04:30Z
```

```
> cabal update hackage.haskell.org,2022-03-25T14:04:30Z
Downloading the latest package list from hackage.haskell.org
Updated package list of hackage.haskell.org to the index-state 2022-03-25T14:04:30Z
```

**Comment by Martinsos** [comment]
Hmmm, so what do we conclude here?

From what I understand, if our local list of hackage indexes is older than wanted index-state, then we get a warning from cabal, but the result is that older packages will be used than what we want to be used. So that is not good -> we should have our list of packages to be newer than the wanted index-state, so ensure we get packages from that index-state, right?

As for the exploration you did at the end -> well that was really confusing! That first code snippet is the weirdest, right? I would expect it to end up with index state being that of 25th, not that of 22nd!

**Comment by Martinsos** [comment]
> > From what I understand, if our local list of hackage indexes is older than wanted index-state, then we get a warning from cabal, but the result is that older packages will be used than what we want to be used. So that is not good -> we should have our list of packages to be newer than the wanted index-state, so ensure we get packages from that index-state, right?
> 
> Yes we get the warning but it is on us to call `cabal update`. I'm unhappy that this is a warning and not an error as I don't think it makes sense for `cabal build` to proceed. Also often there is a lot of build output and it would be easy to miss this warning.

I agree with this, I would also prefer this to be an error! As you said, it is easy to miss this, and as a result we lose the reproducibility of the build, it is possible somebody builds it incorrectly. Should we open an issue on Cabal for this?

**Comment by Martinsos** [comment]
> > As for the exploration you did at the end -> well that was really confusing! That first code snippet is the weirdest, right? I would expect it to end up with index state being that of 25th, not that of 22nd!
> 
> Yes this seemed particularly odd. I went further than I describe here, renaming and saving `~/.cabal/packages/hackage.haskell.org` after each `cabal update` call so I could do comparisons. I saw one timestamp file change and not much else when diffing those saved folders.
> 
> This might make sense if nothing had changed on `hackage.haskell.org` between the 22nd and 25th.

Aha! Well maybe, hm. Do you think we should raise an issue for this on Cabal, also? It is somewhat suspicious.

**Comment by philderbeast** [comment]
We get little feedback from the `cabal update` command.

cabal update: option to print which packages were updated, https://github.com/haskell/cabal/issues/7801

**Comment by philderbeast** [comment]
@Martinsos I've logged https://github.com/haskell/cabal/issues/8076.

**Comment by Martinsos** [comment]
Thanks @philderbeast ! I also commented on the issue on Cabal repo, providing a bit of context from my side.
What shall we do with this specific issue, shall we close it? Not sure we can do much more at the moment.

**Comment by philderbeast** [comment]
If you know to `cabal update` then this is not a problem. To that end, I've suggested #552. Not much else we can do for now so closing.

**Comment by philderbeast** [comment]
@Martinsos a different approach is bundling index-state with constraints when a project is buildable with a range of GHC versions.

[cryptol/cabal.GHC-8.10.7.config](https://github.com/GaloisInc/cryptol/blob/master/cabal.GHC-8.10.7.config)
[cryptol/cabal.GHC-9.0.2.config](https://github.com/GaloisInc/cryptol/blob/master/cabal.GHC-9.0.2.config)

**Comment by Martinsos** [comment]
@philderbeast interesting, and then you use different config files for different GHC versions?
On our side problem are not GHC versions, but different platforms though.
