### ISSUE TITLE
Use pg-boss for jobs instead of our JS shim (without repeating support)

### ISSUE THREAD

**Issue by faassen** [wasp-lang/wasp#536]
## Description

Instead of generating our simple JS stuff we now want to issue real persistent jobs and we use pg-boss as the backend. Once we do this we stop supporting the simple node-based in-memory jobs altogether.

If someone uses a `job` in their Wasp code we want to give an error if they're not using PostgreSQL.

This is NOT implementing any repeating support yet.

## Acceptance criteria

* we test it by hand in the example (`waspc/examples/todo-app`)

* make sure the e2e test generates the right code

**Comment by shayneczyzewski** [comment]
https://github.com/timgit/pg-boss
