### ISSUE TITLE
Investigate integration of react-query useMutation into Wasp

### ISSUE THREAD

**Issue by faassen** [wasp-lang/wasp#543]
## Description

To get the full benefit from React Query, including the potential for optimistic update and fancy cache invalidation, we need to support the React Query `useMutation` hook.

## Acceptance criteria

Have an issue that specifies what React Query `useMutation` looks like with Wasp. Perhaps create two issues: one step is the equivalent of current Wasp capabilities, the second step is what exposing more advanced capabilities looks like.

**Comment by Martinsos** [comment]
Let's just make sure usage of useMutation is powered by specific use cases, and not merely to expose react-query functionality!
I remember there was a reason why we didn't use useMutation so far, I believe for some reason we concluded we don't really need it. And I am pretty sure we will need it now, for manual cache invalidation / optimistic updates. But let's make sure to think about it from that point of view, so we can figure out how to best represent it in Wasp -> who knows, maybe there is some cool way we can abstract it or rename it to smth or so on. I just wouldn't want us to directly copy useMutation without rethinking it a bit.

**Comment by Martinsos** [comment]
I would possibly even remove this issue, and make this just a consideration of "have basic support for optimistic updates".

**Comment by sodic** [comment]
We can take a look at this on Wednesday.

If we want optimistic updates and manual cache invalidation, we'll most likely need something that looks and works like react-query's `useMutation`, so using it under the hood does make sense.
