### ISSUE TITLE
Have basic support for (react-query based) manual optimistic updates and cache invalidation

### ISSUE THREAD

**Issue by faassen** [wasp-lang/wasp#544]
### Description

We want to support react-query style manual optimistic updates and cache invalidation in Wasp. 

This issue needs to be further refined.

**Comment by Martinsos** [comment]
Thought: I believe doing manual optimistic updates, and doing manual cache invalidation, will turn out to be exactly the same thing, or at least very similarly thing. So it is worth exploring them together / thinking about them together.

This whole topic has also been discussed in some details as part of https://github.com/wasp-lang/wasp/issues/63 .

**Comment by sodic** [comment]
> Thought: I believe doing manual optimistic updates, and doing manual cache invalidation, will turn out to be exactly the same thing, or at least very similarly thing. So it is worth exploring them together / thinking about them together.

Did you mean "in most, these two things happen together and the same mechanism is used to trigger them"? If so, I agree.
