### ISSUE TITLE
Describe the codebase architecture (for contributors)

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#55]
By giving high lvl overview, similar like they do it for React (https://reactjs.org/docs/codebase-overview.html), we can make it much easier for contributors to start contributing. We should explain basic stuff like Parser, Generator, AST/Wasp, FileDraft, CLI vs Library, ... .

This should probably go to README here or maybe special document.

**Comment by matijaSos** [comment]
Great idea! This should maybe be a part of Contributing guide?

**Comment by Martinsos** [comment]
Done
