### ISSUE TITLE
Db commands (migrate) can be executed before Prisma CLI was installed

### ISSUE THREAD

**Issue by matijaSos** [wasp-lang/wasp#56]
The problem is that user can now run `migrate` commands before the code was generated for the first time and prisma CLI installed.
In that case everything just freezes. A use-case that I had was when I downloaded our todo example files and tried to run `migrate-save` before anything else.

Possible solution: db commands should run code generation and npm install before doing their stuff. Or they could check if it was ever done (e.g. we can save that info in .wasproot file) and then do it only if it is needed.

**Comment by Martinsos** [comment]
Just a note: .wasproot is imagined to be commited to source, so stuff like this would be written somewhere in .wasp/ dir. We don't have file there yet for saving such info, but there will be one, probably smth like wasp.json or waspinfo.json or smth like that. .wasproot will probably never have anything written to it, except for some global project wasp-related settings, in which case it might be renamed to smth more reasonable wasp.json or smth. Although we are for now putting all that info into .wasp code directly hm.

**Comment by matijaSos** [comment]
You are right, this isn't something we'd like to commit, since we use it for tracking the internal state of wasp tools.

**Comment by Martinsos** [comment]
.wasproot gets committed actually! But you are right, it should not get
committed probably, so it should not go into .wasproot, but somewhere into
.wasp dir.

**Comment by matijaSos** [comment]
This will be fixed by #86 . TODO: when this is done open another issue for `wasp start` to automatically run `migrate up`, so wasper does not have to do it manually after e.g. checking out the project.

**Comment by matijaSos** [comment]
Fixed by #86
