### ISSUE TITLE
Refactor how we use Happy

### ISSUE THREAD

**Issue by sodic** [wasp-lang/wasp#563]
We use [Alex](https://haskell-alex.readthedocs.io/en/latest/) for generating a lexer for Wasp. Alex allows us to define the lexical grammar (and appropriate actions) in a _Lexer.x_ file using Alex's DSL. This file then compiles to Haskell and can be used as a regular module.

Alex's DSL syntax supports writing and using plain Haskell (e.g., functions, imported modules) inside the same `Lexer.x` file (read [the intro to Alex](https://haskell-alex.readthedocs.io/en/latest/introduction.html) for details).
Unfortunately, IDEs have limited support for Haskell code inside Alex's files. In other words, the best approach is to define all possible helper functions in a regular `.hs` file outside of the _Lexer.x_ file (something like `LexerUtils.hs`) and then import and use them with Alex.

**All lexer utility functions are currently defined inside the _Lexer.x_ file. This implies poor IDE and IntelliSense support. Therefore, we should move them to a regular _LexerUtils.hs_ file and import them inside _Lexer.x_.**

Relevant files:
- _Lexer.x_: https://github.com/wasp-lang/wasp/blob/main/waspc/src/Wasp/Analyzer/Parser/Lexer.x
- _LexerUtils.hs_ - does not yet exist, you should put it here: https://github.com/wasp-lang/wasp/blob/main/waspc/src/Wasp/Analyzer/Parser/

**Comment by modotte** [comment]
Hello! I would like to try tackling this issue. :slightly_smiling_face:

**Comment by Martinsos** [comment]
Awesome @modotte I see you already went for it -> I am commenting in the PR :)!
