### ISSUE TITLE
Review generated CSS and make plan for it moving forward

### ISSUE THREAD

**Issue by shayneczyzewski** [wasp-lang/wasp#568]
We should review the generated CSS we have now and decide if we want to keep, tweak, or remove it entirely. We should also consider the possible direct/indirect interactions our base settings may have with any popular CSS frameworks out there (e.g. Material UI, Tailwind CSS which we cannot yet support #560 , etc.).

Note: Part of this awareness came after helping a user debug a dark mode Material UI theme question, where they needed to add `<CssBaseline />` for the background color to work.

Some files of interest:
- data/Generator/templates/react-app/src/index.css
- data/Generator/templates/react-app/public/index.html

Overall, this is a small part of a larger UI overhaul question. But this is something we can make progress on before that larger effort.

**Comment by Martinsos** [comment]
We added it to have some nice defaults, but as @shayneczyzewski said, this now can cause interference with user's styling solution, so we might want to completely remove our defaults.
