### ISSUE TITLE
Support seeding the database

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#569]
@joanreyero wanted to seed the database for the project, and while he managed at the end to directly use Prisma's support for this, he would love it if Wasp would support it directly:

> I could not find anywhere in the docs explanations about seeding data. I ended up spinning up my own Prisma server in the root of my project and writing my seed script there. It would be amazing if Wasp had seeding built in. For extra points, it would be super useful if the seeding could make use of the actions defined in Wasp. For example, my createIdea function (Idea is the main entity in my project) is quite complex, thus I would love to be able to use it when seeding instead of having to repeat code. When I tried to use it in Seeding I ended up with several import errors. I think it is because the seeding script is not a module and does not like the import and export used in the actions.js file.

The idea of using Actions (Operations) during seeding is also very cool!

We should figure out how to add support for seeding in Wasp, ideally using as much as we can from Prisma, but integrating it into Wasp.

**Comment by breadchris** [comment]
yeah using actions for seeding sounds like a great idea, that is effectively what an action is already (modifying the state of the db).

**Comment by Martinsos** [comment]
Implemented!
