### ISSUE TITLE
When Wasp forwards CLI output from subprocesses, it is late one line with (stderr) label

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#588]
![image](https://user-images.githubusercontent.com/1536647/167086288-15550e0e-2f18-4c53-a826-cb9f0fb16851.png)

In the example above I ran `wasp db studio`, and as you can see, at some point `prisma studio`, which is being run in the background, printed some stuff first to stdout and then stderr.

What Wasp does is append `(stderr)` in front of any stderr output, to make it clear it came from stderr.
However, as you can see above, it seems that it is being late one line when doing that! This causes the output to break.

I would suggest following:
1. Figure out why is Wasp late one line with adding `stderr` label and fix it.
2. Instead of adding ` (stderr)` to the "prompt", add something shorter, like `!`, so it disrupts the whole output less. Also, add whitespace to "prompt" when printing from stdout, so output is aligned.

So, what I am proposing is the output that looks as following:
```
Db : Environment variables loaded from .env
Db : Prisma schema loaded from ../db/schema.prisma
Db : Prisma Studio is up on http://localhost:5555
Db!: ┌─────────────────────────────────────────────────────────┐
Db!: │  Update available 3.9.1 -> 3.13.0                       │
Db!: │  Run the following to update                            │
Db!: │    npm i --save-dev prisma@latest                       │
Db!: │    npm i @prisma/client@latest                          │
Db!: └─────────────────────────────────────────────────────────┘
```

That exclamation mark would ideally also be colored in red.

**Comment by InfiniteVerma** [comment]
I'd like to work on this.

**Comment by Martinsos** [comment]
Hi @InfiniteVerma , thanks for the interest! Let me konw if you need any assistance/guidance!

**Comment by Martinsos** [comment]
This got fixed by generally improving how prefixed output is done!
