### ISSUE TITLE
extra warning in the db migration process

### ISSUE THREAD

**Issue by realamirhe** [wasp-lang/wasp#597]
**Describe the bug**
I'm following the todo app, in ["Task Entity section"](https://wasp-lang.dev/docs/tutorials/todo-app/task-entity), I ran the following command for the first time,  but it shows me a warning to run it again. 

```bash
wasp db migrate-dev
```

**To Reproduce**
Follow todo instructions, step by step till Task Entity

**Expected behavior**
Not showing the warning of the command for the same command.

**Screenshots**
<img width="731" alt="Screen Shot 2022-05-19 at 2 07 20 PM" src="https://user-images.githubusercontent.com/23579958/169263271-79917472-6908-4b5b-9338-8a6499b2c41a.png">

**Comment by shayneczyzewski** [comment]
Thanks for opening this issue @realamirhe regarding a redundant warning to run `db migrate-dev` _while_ you are actually running `db migrate-dev`. :) The short of it is we do our error/warning checks during compilation, and we compile before we run every command. So when you first migrate, it detects you have not yet run it during compilation before migrating, and hence the warning. But we can/should be smarter about what command you are running and suppress as needed. We will update 👍🏻 Thanks!
