### ISSUE TITLE
File changes not detected by wasp start in WSL2 when using the Windows filesystem

### ISSUE THREAD

**Issue by craigmc08** [wasp-lang/wasp#603]
**Describe the bug**
`wasp start` running in WSL2 for a project on a Windows file system does not automatically recompile and hot-reload the web page when making changes.

**To Reproduce**
1. Open a WSL2 OS and navigate to a directory on the mounted C: drive (`/mnt/c/`).
2. Make a new wasp project
3. Run `wasp start` in the project directory
4. Change a file in the project and save it.
5. `wasp start` will not have any output about seeing new changes and the webpage will not be updated.

**Additional context**
This is an issue with WSL2 (see https://github.com/microsoft/WSL/issues/4739). Recommended solution is to include this issue in Wasp documentation to help new users avoid it. Might also make sense to try to detect when a user runs `wasp start` in a Windows filesystem and warn them of the issue.

**Comment by EmmanuelTheCoder** [comment]
Here is a workaround for this pending the time when Microsoft will provide a permanent fix. **Move your project into the Linux file system root directory**. This will enable WSL to detect changes in your project for hot reload to kick in. You will also notice an increase in performance compared to the Windows file system root directory that is very slow.

**Comment by Martinsos** [comment]
So what I got from this is that problem is if:
1. You use WSL2 (WSL (1) works)
2. Your source files are being stored on Windows filesystem, not WSL's

Then, detection of file changes for such files doesn't work at all, not just for Wasp, but for anybody.

If I got it right, one solution is to have source files on WSL's filesystem. This means you will want to use editor that is running from WSL, not from Windows.

**Comment by Martinsos** [comment]
@EmmanuelTheCoder thanks for providing the fix! Just wondering: If you move them to linux file system, do you need to use editor running via WSL, or can you still use editor you have installed on Windows?

**Comment by EmmanuelTheCoder** [comment]
No, you don't need to run an editor via WSL. Linux is interoperable with Windows, i.e you can run Windows tools from Linux. The thing with WSL not detecting changes from a Window file system directory is an issue that I think Microsoft is working to resolve (to further show the interoperability between Windows and Linux commands).

To get more light on this, you will find this link useful: https://learn.microsoft.com/en-us/windows/wsl/filesystems

@Martinsos, I think we should update our docs to give Windows users a heads-up about this issue and how to work around it.

**Comment by Martinsos** [comment]
Awesome, thanks @craigmc08 and @EmmanuelTheCoder , solve by adding note to docs: cb4dd31169c371c38e898d51647de890a9877add !

**Comment by EmmanuelTheCoder** [comment]
@Martinsos, Good to know you've added a note to docs to give Windows users an heads up.
