### ISSUE TITLE
On file change, Wasp generator tries to copy a temp file which disappears and makes it crash

### ISSUE THREAD

**Issue by matijaSos** [wasp-lang/wasp#61]
In this specific case the problem is with Vim temp files (e.g. someFile.js~) - Upon some file change, filewatch triggers recompiling which registers the temp file but by the time it tries to copy it is already gone - thus wasp tries to copy an inexistent file which crashes wasp.

Possible solutions:
1) add .gitignore or .waspignore support
2) hardcode files that should generator ignore when copying everything from ext (this change should happen in ExternalCode module). If doing this, consider reusing logic from cli Command.Watch module.
3) add delay between filewatch and recompiling

Approach 2) is probably easy enough to do and a good foundation for the future (.wasp/gitignore).

**Comment by Daniellop1** [comment]
I think option 1 would be the most appropriate but option 2 would also work

**Comment by Martinsos** [comment]
Fixed! We added .waspignore + we modified logic that does the copying so it ignores if some file is missing.
