### ISSUE TITLE
Update prisma to 3.13 in order to have support for SSL 3.0

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#629]
Prisma doesn't work for SSL 3.0: https://github.com/mikecao/umami/issues/1081 .
They fixed this in latest version, 3.13.

Let's update Wasp so that people don't hit this problem with Wasp!

**Comment by Martinsos** [comment]
> We may also want to consider allowing any of our major NPM deps to be set via environment variables so users have an escape hatch and don't have to wait for us to update, test, and release.

I am a bit afraid of this as then they can really mess things up if they start using versions that we haven't tested with, right?
But it doesn't sound compelling that they can fix things themselves.
Although, I imagine if there is some serious issue, we can release the new version equally fast as it would take to inform them to upgrade it on their own. So this is more for them to fiddle with stuff, which might end up badly? This way we at least learn about the issues since people have to report them :D. Hm hm! Would you like to open an issue for this @shayneczyzewski , since this one is getting closed?

**Comment by shayneczyzewski** [comment]
> > We may also want to consider allowing any of our major NPM deps to be set via environment variables so users have an escape hatch and don't have to wait for us to update, test, and release.
> 
> I am a bit afraid of this as then they can really mess things up if they start using versions that we haven't tested with, right? But it doesn't sound compelling that they can fix things themselves. Although, I imagine if there is some serious issue, we can release the new version equally fast as it would take to inform them to upgrade it on their own. So this is more for them to fiddle with stuff, which might end up badly? This way we at least learn about the issues since people have to report them :D. Hm hm! Would you like to open an issue for this @shayneczyzewski , since this one is getting closed?

Thanks for upgrading it and releasing! I will create an issue with the idea just for future consideration. It may be the case that a user for a particular configuration has an issue with some version that we do not want to roll out globally, perhaps? Dunno... but will just add an issue for future in case. Thanks!
