### ISSUE TITLE
Produce more user-friendly error when DATABASE_URL envar is not set but app is using PostgreSQL

### ISSUE THREAD

**Issue by shayneczyzewski** [wasp-lang/wasp#647]
**Is your feature request related to a problem? Please describe.**
A user asked a question when running Waspello about why it wasn't starting. We do show a lot of error output, parts of it indicating Prisma cannot connect due to a missing envar, but we should make it clearer.

**Describe the solution you'd like**
The CLI should produce a very clear error message about the missing envar and link to the docs.

**Comment by ussgarci** [comment]
Hello, I'd like to work on this issue.

**Comment by Martinsos** [comment]
Thanks for all the effort so far @ussgarci , unfortunately I have to reopen this one as I completely forgot about .env files! So, we have .env file which can also be used to provide env vars, and if they use that to specify DATABASE_URL, which in 99% cases they do, we will generate warning message that shouldn't be generated!

Solutions:
1. In Haskell, make sure to read that .env file also while deciding if we should generate the warning or not.
2. Move the logic to generated code, into Nodejs codebase, at the place where DATABASE_URL variable is obtained (config.js) and generate warning/error there.

Both are ok I think, the first one involves some duplicated logic compared to what we do in the generated code, but it gives Wasp knowledge about it and we show the warning when we want and so on.

The second solution is simpler, no logic duplication between compiler and generated code, but also it will output just another Nodejs warning so we have less control over when we show the warning.

I am not sure what is the best approach, I am ok with both I think.

For now I reverted the change on the main branch, so we should continue from the old PR and build upon it and merge it again into main!

**Comment by ussgarci** [comment]
Hey @Martinsos, good catch! I would prefer to implement solution #1.

**Comment by Martinsos** [comment]
> Hey @Martinsos, good catch! I would prefer to implement solution 1.

Sounds good, let's give it a try! I think the biggest question will be, how much work is it to read the dot env file.

**Comment by Martinsos** [comment]
Closing this one as things change quite a bit with the introduction of managed wasp db.
