### ISSUE TITLE
Wasp is missing glibc 2.29 on Ubuntu 18

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#650]
Ubuntu 18.04.6

![image](https://user-images.githubusercontent.com/1536647/175925762-c79a2d20-d858-4d83-ac13-d00656947228.png)

The solution to this is us building/compiling Wasp statically during CI, so it does not depend on other libraries. Right now we build it mostly statically but it still depends on some libraries (it is somewhat dynamic) -> we need it to be completely static.

**Comment by modotte** [comment]
Hello! I believe Ubuntu 18.04 requires wasp to be compiled at minimum with [glibc 2.27](https://packages.ubuntu.com/bionic/libc6) for it to execute properly (I didn't test it, so I'm not 100% sure).

**Comment by Martinsos** [comment]
Hm interesting @modotte ! We could try and go with that. I wonder if we are losing anything by not compiling on latest version of Ubuntu? Probably not.
But, static binary still sounds tempting to me, as there are probably some other deps also that might cause problems! I get what you say with size, but do you think that actually has impact in practice? Right now it is 50MB -> ok that is not small, but I wonder if that is actually an issue for people. I personally don't care much, as long as it is not something huge.

**Comment by modotte** [comment]
I'm okay with either way and don't think the executable size increase won't be a massive problem for most people these days. Also, I'd agree with the potential missing required external deps (libgmp comes to mind) with the current, partially dynamic binary that could be solved by having a full, static one instead.

**Comment by Martinsos** [comment]
Regarding building Wasp as static binary:
- it seems that `glibc` is not designed to be statically linked and it can cause problems.
- here is interesting discussion about it with some suggestions (thanks @shayneczyzewski for finding this): https://github.com/haskell/haskell-language-server/issues/2431

Some interesting comments I noticed in discussion above:
> ok the plan then will be build Linux binaries with the flags suggested by @wz1000 against the older Ubuntu provided by GitHub vms

> If I were you, I would just do what the rest of the world does and build on a distribution like Alpine that uses musl. This will greatly simplify things.

I like the best the plan with Alpine with musl, since that is similar to what I read some time ago about how to approach this.

**Comment by Martinsos** [comment]
We are now compiling on an older version of ubuntu so it shouldn't be much of a problem in pracstice any more.
