### ISSUE TITLE
Split file main.wasp

### ISSUE THREAD

**Issue by hoanghiaquyen** [wasp-lang/wasp#656]
how i can split file main.wasp. i see file main.wasp in real world too length to maintaination.

Thanks.

**Comment by Martinsos** [comment]
Hi @hoanghiaquyen , yes that is certainly a plan! There is an issue open for it here: https://github.com/wasp-lang/wasp/issues/315 . We haven't got to it yet, but are planning to do it for Beta or a bit later -> as you said, in real world apps one file is certainly not enough.

**Comment by Martinsos** [comment]
Thanks @hoanghiaquyen , we will do our best to make that happen and looking forward to interacting more with you :)! Btw here is a way to sign up for our newsletter, we send one email per month with updates: https://wasp-lang.dev/#join-the-list .
