### ISSUE TITLE
Consider removing lodash as a core Wasp dependency

### ISSUE THREAD

**Issue by shayneczyzewski** [wasp-lang/wasp#659]
Filip noticed that we only use `lodash` in a single file to perform `_.merge` of configs.

```bash
$ pwd && rg "lodash"  
/home/filip/wasp/reviews/waspc
data/Generator/templates/server/src/config.js
2:import _ from 'lodash'

src/Wasp/Generator/WebAppGenerator.hs
87:            ("lodash", "^4.17.15"),
$
```

We might consider removing it. It's a big dependency anyway and we can easily implement this ourselves. It's also pretty popular and removing it would allow our users to decide on the version they want to use on their own.

**Comment by Martinsos** [comment]
Sounds good to me, nice catch!

**Comment by codingmickey** [comment]
Can I try on this issue?

**Comment by Martinsos** [comment]
> Can I try on this issue?

Sure feel free to go for it!

**Comment by codingmickey** [comment]
before I tried it's done by someone, accept his pr 👍🏽

**Comment by infomiho** [comment]
We replaced `lodash` with `lodash.merge` (which only contains the `merge` fn we use) quite some time ago. This way we are minimising the size of deps and just using what we need. I'll close this issue since the goal of this issue was achieved IMHO.
