### ISSUE TITLE
Change Node base image version in Dockerfile to 16

### ISSUE THREAD

**Issue by shayneczyzewski** [wasp-lang/wasp#667]
We are currently specifying Node 14 in our Dockerfile: https://github.com/wasp-lang/wasp/blob/main/waspc/data/Generator/templates/Dockerfile#L2

We should upgrade that to `FROM node:16-alpine AS node`

**Comment by Martinsos** [comment]
@shayneczyzewski have we maybe fixed this already, it seems to ring a bell when I think about it?

**Comment by shayneczyzewski** [comment]
> @shayneczyzewski have we maybe fixed this already, it seems to ring a bell when I think about it?

This is slotted to be taken care of with the linked google authn PR. That will be updated for the `UsernameAndPassword` refactor after merge and hopefully should be ready for a final round of review in a few days 👍🏻
