### ISSUE TITLE
Add SECURITY.md for wasp

### ISSUE THREAD

**Issue by h4r1337** [wasp-lang/wasp#697]
Currently we don't have a [SECURITY.md file](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository)
 which describes the security policy in a way that is more accessible to GitHub users.

This will help wasp to recieve more bug reports and add the repo to bug bounty platforms like [huntr.dev](https://huntr.dev)

**Comment by Martinsos** [comment]
Sounds good, let's do it! Do we have an idea of what this file should look like, some good examples? Do you want to take this on @h4r1337 ?

**Comment by h4r1337** [comment]
We can enable the [security policy via GitHub](https://github.com/wasp-lang/wasp/security). Basically it should include a way to report the vulnerability(email), rather than creating an issue.

**Comment by Martinsos** [comment]
Thanks @h4r1337 for initiating this! I did it with this commit: https://github.com/wasp-lang/wasp/commit/0473a6e320d4452ef82762ecddf1bf9a1ccdde91 .

**Comment by h4r1337** [comment]
Can you change that to a `security@` mail instead of `hi@`. It would be better in the security context...
If there's any other problems, then `hi@wasp-lang.dev` is just fine for now...

**Comment by Martinsos** [comment]
That is a good idea but I would rather have smaller number of emails, otherwise they easily explode if we create new one for every purpose - so let's keep `hi` for now and if that becomes hard to manage we can always switch to `security`!

**Comment by h4r1337** [comment]
Okay then. Closing the issue now :)
