### ISSUE TITLE
Add e2e test for a complex app with all features

### ISSUE THREAD

**Issue by shayneczyzewski** [wasp-lang/wasp#701]
**Is your feature request related to a problem? Please describe.**
Originally, the e2e golden tests were meant to test basic sequences of CLI command outputs on disk. They then started testing specific features, like Jobs (but via a hacky `printf` command line mechanism for creating/updating files).

However, we'd like to have some way to make sure all the kitchen sink features remain stable, and e2e should ideally support this. What we would like to do for this case is create a golden test for a complex app where we can add pretty much every feature to it, but while it is all already on disk before the test starts. This would not test so much CLI commands themselves, but rather, the compiled output of a complex project. This would be helpful as we modify the parser, for example, or just want to make sure features remain stable as we refactor, and it would scale better than one sample project per feature under test.

NOTE: As stated, we would need to create the golden dir on disk first. The existing tests create them all with `wasp new`. We would not do that, but instead, only test the output of `wasp compile`.  However, I think there are some directory creation/naming assumptions currently baked into `runGoldenTest`, and the fact that it assumes we are creating things on the fly. Would need to test it out some to figure it out and probably refactor it a bit.

**Comment by Martinsos** [comment]
Related to #884
