### ISSUE TITLE
Update React Query to version 4

### ISSUE THREAD

**Issue by sodic** [wasp-lang/wasp#717]
Since the creation of #542, React Query 4 has become stable. We should update as soon as possible. There are several breaking changes, but I went through the list and nothing will seem to affect any of our functionalities.

The migration should be fairly straightforward following their guide: https://tanstack.com/query/v4/docs/guides/migrating-to-react-query-4

**Comment by Martinsos** [comment]
Sounds good!

**Comment by EmmanuelTheCoder** [comment]
@sodic @Martinsos will this also count for hacktoberfest contribution?

**Comment by sodic** [comment]
Hey @EmmanuelTheCoder, go for it!

I've just added the label.

**Comment by EmmanuelTheCoder** [comment]
Hi @sodic, I am not familiar with Haskell so I'd prefer a non-Haskell task.

**Comment by EmmanuelTheCoder** [comment]
I'm fluent in Typescript, JavaScript, Node (Express.js), React, Next.js, and MongoDB

**Comment by sodic** [comment]
Sure! Give me some time (a day max) and I'll get back to you.

**Comment by EmmanuelTheCoder** [comment]
No problem.

**Comment by sodic** [comment]
How about this one: https://github.com/wasp-lang/wasp/issues/756

**Comment by EmmanuelTheCoder** [comment]
Looks great. Kindly assign me to the issue.
