### ISSUE TITLE
Examples links in docs should point to `release` branch, not `main` branch.

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#728]

**Comment by Martinsos** [comment]
Hey @lelouchB , sure, go for it! Let me know if you need any pointers.

**Comment by lelouchB** [comment]
Hey @Martinsos 
Do all the links in `web` directory should point to release ?

**Comment by Martinsos** [comment]
@lelouchB hmmmm, hard to say off the bat.
So `release` branch represents whatever was published on webpage/blog/docs, while `main` branch is the latest progress however it is not yet out there.
So mostly, I would expect that webpage should point to the `release`, but maybe in some special situations we do want it to point to `main` instead.

This PR is only about `examples` though, so with those there is no question, for those we want to point to the `release` branch.

But you found some other links you think might also need fixing? Can you give some examples?
