### ISSUE TITLE
in development only: migrate-save description cannot contain space

### ISSUE THREAD

**Issue by matijaSos** [wasp-lang/wasp#73]
Somehow that doesn't work, we should fix it.
Example of a command we run from CLI: `wasp db migrate-save "Added user"` -> it will just list available db commands, I guess it doesn't match it to any command?

**Comment by Martinsos** [comment]
It seems to work fine on Linux!

**Comment by matijaSos** [comment]
Tried to reproduce again, but couldn't, seems it is working now. Prisma is allowing spaces. I also check out the implementation and that also looks ok - `proc` from `System.Process` accepts a list of arguments and `getArgs` from `System.Environment` parses e.g. `"Add user"` into `["Add user"]` -> removes the quotes but keeps it as one string. So I believe that `proc` which accepts a `[String]` of args knows how to handle a string with spaces.

**Comment by matijaSos** [comment]
Managed to reproduce it: happens only in development, when running e.g. `./run wasp db migrate-save "some name"`. Investigate further, try with stack exec instead of run.

**Comment by Martinsos** [comment]
We deprecated migrate-save, now it is migrate-dev and name is asked for interactively.
