### ISSUE TITLE
Rethinking Wasp code organization

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#734]
Related to https://github.com/wasp-lang/wasp/issues/710 .

So far we have made decisions in Wasp like:
1. Code generated by Wasp is put in .wasp dir.
2. Code generated by Wasp is imported in JS files as "@wasp/...".
3. Generated code is structured in a certain manner (queries are under queries/, actions under actions/, ...).
4. User code is organized under ext/ directory and then just copied into the generated project.
5. And many more decisions!

We are now trying to add IDE support for user code in ext/ (specifically for JS/TS code) and one big thing that makes this somewhat tricky to do is the way our code is organized -> generated project is organized differently than what we have in the source dir, specifically in ext/, so we have to "cheat" editor/IDE into thinking stuff in ext/ is part of the project that is not really there (because IDEs, or their plugins for JS/TS, expect some standard JS project setup, like node_modules in specific place, maybe package.json to be there, tsconfig.json, ... -> and we have none of those in source project in ext/ dir, we only have it once you go to generated project).

So the idea is -> what if we rethink stuff and reorganize Wasp in such way that we maybe avoid some of these issues? Maybe make source code more similar in setup to generated project? Or at least those parts that are needed for IDE support for JS/TS?

So let's rethink stuff @shayneczyzewski @sodic @matijaSos ! Let's let our minds wander and come up with crazy ideas. Doesn't matter if they are unbaked or a bit impossible, let's just try to come up with some new directions and see where they take us.
**I suggest taking an hour or two specifically for this** and just trying to come up with smth.

While thinking about ideas, here are some requirements to keep in mind:
1. In the future we will want to have Wasp modules -> standalone, reusable packages of .wasp files + other JS/html/... files. Likely we will also want to mix .wasp files with other files, so they can be next to each other.
2. We might want to support some other languages next to JS/TS, for example Python, or Go:
  2.1. As languages used on backend, instead of JS/TS backend or next to JS/TS backend.
  2.2. As languages to write jobs in.
3. We want to support deploying our web apps as different architecture and on different providers.
4. We want to support multiple IDEs (even though we are now focusing on vscode).
5. Support stuff like prettier, linter, ... .
6. We want to allow organizing project by feature.

Some rough ideas that were mentioned so far:
1. What if we generated projects directly in the source project, next to files in ext/. Maybe organized as neatly as possible, so they are not too much in the way, but still they would be there.
2. What if users would not write their code in ext/ as they do now, as just JS / HTML / ... files, but instead they organized their code as complete npm packages that import Wasp code as yet another package and generated Wasp code also imports them as npm package? That way their code is an encapsulated, standalone thing that IDE knows how to deal with, and we can easily use it in the generated code.
4. Wasp could be generating more or less of the code as libraries. Some of it could be even prepared before hand as a library, if it does not depend on the source code. This is a bit orthogonal idea though, not so tightly related with what we are doing here hm but could be useful.

**Comment by Martinsos** [comment]
Some of the things this re-organization might fix:
1. Non-customizable build pipeline
2. No way to modify package.json
3. No way to install dev dependencies
4. No package-lock.json support
5. Hacky/partial IDE support
6. No support for tests

**Comment by Martinsos** [comment]
Related to #816

**Comment by Martinsos** [comment]
Current approach here: all code will be organized as one big npm package, with package.json file exposed. Both client and server code will be under this. @sodic is currently actively working on this.

**Comment by uniphonic** [comment]
> Current approach here: all code will be organized as one big npm package, with package.json file exposed. Both client and server code will be under this. @sodic is currently actively working on this.

Having the package.json file exposed sounds great! When is this planned to happen?

**Comment by Martinsos** [comment]
> > Current approach here: all code will be organized as one big npm package, with package.json file exposed. Both client and server code will be under this. @sodic is currently actively working on this.
> 
> Having the package.json file exposed sounds great! When is this planned to happen? Also, what would upgrading an existing Wasp project entail? Thanks!

We are planning to have this out very soon, in a couple of weeks! Most of your JS code won't need to change much, but updating will require moving some stuff around, possibly doing some db migrations (because we are also going to release improved Auth), ... . We will make sure to provide instructions / scripts on how to do the project update most easily.

**Comment by Martinsos** [comment]
whoop whoop

**Comment by sodic** [comment]
Closed by restructuring done for Wasp 0.12.0.

**Comment by cprecioso** [comment]
Should we remove the link to this issue from our docs?

https://github.com/wasp-lang/wasp/blob/release/web/docs/project/dependencies.md?plain=1#L26-L29

**Comment by Martinsos** [comment]
> Should we remove the link to this issue from our docs?
> 
> [wasp/web/docs/project/dependencies.md](https://github.com/wasp-lang/wasp/blob/b411bc2f5ebb1eb4be7d2f0c0b23d7b61c9b0596/web/docs/project/dependencies.md?plain=1#L26-L29)
> 
> Lines 26 to 29 in [b411bc2](/wasp-lang/wasp/commit/b411bc2f5ebb1eb4be7d2f0c0b23d7b61c9b0596)
> 
>  :::note 
>   
>  We are currently working on a restructuring that will solve this and some other quirks: check [issue #734](https://github.com/wasp-lang/wasp/issues/734) to follow our progress. 
>  :::

Oh yes please!

**Comment by sodic** [comment]
Not quite - we still have that problem (dependency version constraints for users). So the docs should still link to somewhere, just not this issue.

These two are relevant: https://github.com/wasp-lang/wasp/issues/1644 and #1653

**Comment by cprecioso** [comment]
Updated the link at https://github.com/wasp-lang/wasp/pull/2720
