### ISSUE TITLE
In CLI, example uses "create" while command is called "new"

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#75]

**Comment by abhishekpatel946** [comment]
can you pls describe a little bit?

**Comment by bhantsi** [comment]
Descriptions, please

**Comment by Martinsos** [comment]
Sure, happy to explain! This is actually very easy, it refers to example of using Wasp that gets printed as part of "Usage" string of the "cli" command for wasp, where example uses "create" command while real one is "new". Point of issue is really to help you get started, check out the project, get it running, figure out some parts of it and so on. Where did you get so far, have you managed to compile the project? Let me know if you need some help.

**Comment by Martinsos** [comment]
This actually just got solved with #83! We actually have some other issues marked as "good first issue" which I think are much better and more interesting as a first issue, so feel free to check out those and let me know if I can help in any way.
