### ISSUE TITLE
Add support for case-insensitive usernames

### ISSUE THREAD

**Issue by shayneczyzewski** [wasp-lang/wasp#752]
**Is your feature request related to a problem? Please describe.**
Currently, the `username` field for `auth` is just a String that is used as-is, and thus, is case-sensitive.

**Describe the solution you'd like**
It would be nice for UX if we had some support for making them case-insensitive so that "shayne" and "Shayne" would be considered the same username.

**Describe alternatives you've considered**
We could make this a new flag on the `auth` dictionary, or maybe also provide some Prisma middleware to handle it so they could do even more elaborate things to normalize.

**Comment by sodic** [comment]
I think the best approach is starting with a middleware for "mapping" usernames.

Case insensitivity doesn't seem like a property that's intrinsic enough to earn an extra special field inside the language (e.g., as opposed to something like stripping numbers or underscores). 

If it proves popular enough and ends up making over 90% of users' middlewares, then sure, we can add it in.

**Comment by infomiho** [comment]
Since #1583 we have standardised the way we save auth provider user IDs: we lowercase them _always_. That's what's also recommended by OWASP anyways: https://owasp.deteact.com/cheat/cheatsheets/Authentication_Cheat_Sheet.html#user-ids
