### ISSUE TITLE
Update Wasp CLI bash completion list

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#754]
Wasp's bash completion support is implemented here: https://github.com/wasp-lang/wasp/blob/1995ccdb9d9dd6d17d880e298b9b1305ca016994/waspc/cli/src/Wasp/Cli/Command/BashCompletion.hs .

In the meantime we added some new commands to Wasp, and so it got somewhat outdated.
We should update it to correctly reflect current commands that Wasp CLI has.

**Comment by ussgarci** [comment]
Hello :wave:, I'd like to work on this.

**Comment by Martinsos** [comment]
Sure @ussgarci go for it! This one should be not too hard if you go with updating to the current state, but could get significantly harder if you go the route of refactoring code so it is constantly up to date -> I assume you are doing the first thing?

**Comment by ussgarci** [comment]
Hey @Martinsos , yeah my PR just updates to the current state.  Sorry for not being explicit.
