### ISSUE TITLE
Ensure the REACT_APP_API_URL and WASP_WEB_CLIENT_URL env vars are valid URLs

### ISSUE THREAD

**Issue by sodic** [wasp-lang/wasp#756]
Wasp users can control their backend server's URL by setting the `REACT_APP_API_URL` to a desired base URL.

We should check whether they specified a valid, absolute URL. To see what I mean, try running the app with the following two settings:
```bash
export REACT_APP_API_URL=something
export REACT_APP_API_URL=htp://something
```

In such cases, we should detect the error and warn the user with an appropriate message. Let's start by implementing this inside JavaScript (i.e., during runtime). We can use [this SO post](https://stackoverflow.com/questions/5717093/check-if-a-javascript-string-is-a-url) for inspiration.

Perhaps later we can extend the CLI to check for this before it runs the app (i.e., on `wasp start` and `wasp compile`)

**Comment by EmmanuelTheCoder** [comment]
This is great. I'd like to take this on @sodic

**Comment by sodic** [comment]
Go for it, good luck!

**Comment by EmmanuelTheCoder** [comment]
Hi @sodic, I'm new to the codebase so I'm still trying to figure out everything and where to make the necessary changes. I'd appreciate any guidance I can get from you in this regard.

**Comment by sodic** [comment]
Hey, I recommend creating and running a simple Wasp application (you can use something from the examples directory, e.g., `todoApp`) and looking at the generated code in the `.wasp` directory.

Think about where you'd want this function to be placed inside the generated project. Implement it there, test it out. After you're satisfied, all that's left is editing the appropriate template in the `waspc/data/Generator/templates` directory.

If you're fuzzy on the details on the compiler's pipeline, we've documented it [here](https://github.com/wasp-lang/wasp/blob/main/waspc/README.md).

**Comment by shayneczyzewski** [comment]
Hey gang, since @Martinsos was just bit by this, can we expand this issue to validate _both_ user-supplied URLs? There is one more called `WASP_WEB_CLIENT_URL` that specifies the URL of where the frontend is running. Thanks for considering that addition!

**Comment by Martinsos** [comment]
Yup, the problem was that it had a trailing slash and then I was getting CORS errors!

**Comment by sodic** [comment]
If there's more env URLs we forgot to list, then those as well! :)
