### ISSUE TITLE
Fix compiler warnings in tests

### ISSUE THREAD

**Issue by sodic** [wasp-lang/wasp#759]
At least two of our tests (`WebAppGeneratorTest` and `ValidTest`) report warnings during compilation. You can see them by executing `cabal test waspc-test` in the _waspc_ directory.

We should fix them.

**Comment by ussgarci** [comment]
Hello :wave:, I'd like to work on this.

**Comment by sodic** [comment]
You're on a roll, two PRs in two days. Thanks!
