### ISSUE TITLE
`wasp new <dir>` can't initiate new project if directory already exists

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#760]
This is problem in the case where user created a new repo on github, with just README, checked it out, and now wants to start new Wasp project in it.

I suggest we make is to that if directory already exists, Wasp happily creates project in it, not caring about existing content of the directory.

**Comment by sodic** [comment]
> I suggest we make is to that if directory already exists, Wasp happily creates project in it, not caring about existing content of the directory.

I'm not a fan of this idea.

It seems too aggressive for default behavior. Also, I have a feeling that initializing a project inside an existing directory is something you'd almost never want to do (as it was probably a typo or an accident). I think the CLI should at least ask you whether you're OK with it, or even do it only when given the appropriate flag.

Btw, Git's default behavior matches Wasp's current behavior:
```
fatal: destination path 'project' already exists and is not an empty directory.
```
