### ISSUE TITLE
Update the docs for server setup function

### ISSUE THREAD

**Issue by sodic** [wasp-lang/wasp#761]
Our docs currently list cron jobs as [an example use case for the server setup function](https://wasp-lang.dev/docs/language/features#setupfn-extimport-optional-1). Since Wasp now supports jobs, we should come up with a more pedagogical example (e.g., you can use the server setup function for pinging a different server or something more meaningful).

Also, because cron jobs are probably the first thing that pops into people's heads when they see a server setup function, we should also mention that that is most likely not the most appropriate place to define them (but could be fine depending on the context).

**Comment by infomiho** [comment]
Improved here: https://wasp-lang.dev/docs/project/server-config
