### ISSUE TITLE
Instead of Heroku being default deployment method, find smth else (Render?)

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#767]
Heroku is not free anymore, so we want to find another deployment method we will recommend as the default method. Maybe render.com .
This will in the biggest part come down to writing docs for deploying to this newly picked hosting provider.

**Comment by EmmanuelTheCoder** [comment]
Is Render free?

**Comment by Martinsos** [comment]
Seems to be! Check this out: https://render.com/free . 750h free per month, which is 31.25 days of computation per month.

**Comment by Martinsos** [comment]
Done!
