### ISSUE TITLE
[Realworld] Uncontrolled input on login

### ISSUE THREAD

**Issue by sodic** [wasp-lang/wasp#783]
Our realworld example app throws the following error when logging in:
```
react-dom.development.js:67 Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
    at input
    at form
    at div
    at LoginPage (http://localhost:3000/static/js/bundle.js:2997:79)
    at AddHeader
    at Route (http://localhost:3000/static/js/bundle.js:88660:29)
    at div
    at Router (http://localhost:3000/static/js/bundle.js:88332:30)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:87847:35)
    at QueryClientProvider (http://localhost:3000/static/js/bundle.js:101838:5)
```

We should fix it :)

NOTE: We've recently solved a [similar error](https://github.com/wasp-lang/wasp/pull/720#issuecomment-1246828596), looking at [the fix](https://github.com/wasp-lang/wasp/pull/727) might help you.

**Comment by sivasuriyankumarasamy** [comment]
Hi @sodic, please assign this to me.

**Comment by pwn0x80** [comment]
hey @sodic  can you assign this issue to me i can work on it

**Comment by sodic** [comment]
I've already assigned it to @sivasuriyankumarasamy, but if he's no longer interested, you can take it. Let's give him a day to respond. If he doesn't, it's yours tomorrow at this time :)

**Comment by sivasuriyankumarasamy** [comment]
Hi @sodic,

I have raised a pr for this issue. Please review.
https://github.com/wasp-lang/wasp/pull/792

**Comment by sodic** [comment]
Thanks! Will merge it in a minute.

Btw, one general tip for contributing to open source projects on GitHub:
- Always mention the issue your PR is fixing in its description (e.g., "Fixes #issueNumber"). This way, Github will links between the PR and the issue in the discussions. Also it will automatically close the original issue after the PR gets merged. I've edited your PR"s description to include it, so no worries for that one :)
