### ISSUE TITLE
[Realworld] Unmounted component warning after logging out

### ISSUE THREAD

**Issue by sodic** [wasp-lang/wasp#784]
Our Realworld example app sometimes throws the following error after the user logs out:
```
react-dom.development.js:67 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at Navbar (http://localhost:3000/static/js/bundle.js:1414:19)
    at div
    at Container (http://localhost:3000/static/js/bundle.js:7948:23)
    at WithStyles (http://localhost:3000/static/js/bundle.js:20180:31)
    at UserSettingsPage (http://localhost:3000/static/js/bundle.js:3721:5)
    at AddHeader
    at http://localhost:3000/static/js/bundle.js:776:69
```

We should fix it :)

NOTE: We've recently solved a [similar error](https://github.com/wasp-lang/wasp/pull/720#issuecomment-1246828596), looking at [the fix](https://github.com/wasp-lang/wasp/pull/727) might help you.

**Comment by anup-a** [comment]
Hey 👋 @sodic . Great Project. Can I take up this one ?

**Comment by anup-a** [comment]
Strange but I was not able to reproduce the error. Can you guide me with some steps to reproduce?

**Comment by sodic** [comment]
Hey, @anup-a, sorry for the late response? If you're still interested, I can give you the instructions on reproducing it in a couple of hours.

**Comment by infomiho** [comment]
What I got so far:
- it only triggers if you are on a component that's wrapped with `createAuthRequiredPage` when logging out
- it seems that this warning was removed from React 18 completely: https://github.com/reactwg/react-18/discussions/82

I'll investigate a bit more to see if there is anything actionable or if we should move to upgrade to React 18 as a means of "fixing" this issue.

**Comment by sodic** [comment]
Finally they're removing this warning. Half of the code review fixes in my last company were either telling someone to use the `isMounted` check (when I'm the reviewer), or adding it (when I'm the author).

Anyway, if it's not a memory leak, we can just wait for React 18.

**Comment by sodic** [comment]
Since realworld no longer exists, I'm closing this.
