### ISSUE TITLE
Fix invalid Contact link on our website

### ISSUE THREAD

**Issue by sodic** [wasp-lang/wasp#789]
**Describe the bug**
The Contact link is broken on some of our sites.

**To Reproduce**
1. Go to any of our blog articles, such as https://wasp-lang.dev/blog/2021/09/01/haskell-forall-tutorial
2. Scroll all the way down to see the footer
3. Click on the 'Contacts' link
4. Observe an unexpected "Page not found" message

**Expected behavior**
The footer link should take us to the Contact page.

**Screenrecording of the bug**

https://user-images.githubusercontent.com/22752307/198567640-7da0f335-30d9-4a75-9945-dce1bfe91b50.mp4

**Comment by sodic** [comment]
Sure, go for it!

**Comment by vaishnav-mk** [comment]
https://github.com/wasp-lang/wasp/pull/790 should fix this!

**Comment by sodic** [comment]
Fixed.
