### ISSUE TITLE
Implement new command: `wasp deps list`

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#79]
Wasp already brings some npm dependencies with it, and we can't really ignore them, at least for now.

However, although affected by them, there is no easy way for Wasper to find out what they are (except for looking into .wasp/out/ dir).

What we could do is have command `wasp deps list` that would list all of these Wasp dependencies together with their versions, and could also list dependencies added by Wasper via `dependencies` declaration next to them while already listing them.

Draft:
- Add command `wasp deps list` in `cli/`.
- Command would obtain list of npm deps from WebAppGenerator and from ServerGenerator. They don't yet export these lists so we should also take care of that.
- Command could also add user defined deps by inspecting Wasp AST and fetching deps from it.

**Comment by matijaSos** [comment]
I agree, this is definitely useful and needed.

**Comment by Martinsos** [comment]
@turbodami you could take this one!
