### ISSUE TITLE
Add support in Wasp for hosting the frontend in non-root directory

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#8]
Right now, we successfully hosted our todoApp example, generated in Wasp, at examples.wasp-lang.dev.

However, if we would want to host it at examples.wasp-lang.dev/todoApp (for example), we could not, because with current configuration it can only be served from the root directory of the domain.

We need to figure out what is needed to get this working, and add support for this in Wasp!

**Comment by infomiho** [comment]
This can be a feature e.g. `app.client.baseDir` and we can add the needed adjustments to the `Router` and the Vite config.

The user sets `/my-sub-dir` as their `baseDir` and we apply it as the base and the basename in Vite and Router, respectively.

**Comment by infomiho** [comment]
This is connected to https://github.com/wasp-lang/wasp/issues/1085 since part of this issue is the action of setting the `base` option in the Vite config. 

We should have this in mind when implementing custom Vite config support.
