### ISSUE TITLE
Add command `wasp db ui`

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#80]
Or smth like that, that will for now spin up prisma studio.

How to do it:
1. Add Command under `cli/`. Check out other commands there to get an idea, e.g. `wasp db migrate-up`.
2. It should run `prisma studio`. Keep in mind that in our case, `prisma studio` has to be run from `server/`, while schema is in `db/`, so schema has to explicitly be defined when running `prisma studio` with `--schema ../db/schema.prisma`.

**Comment by matijaSos** [comment]
maybe we can call it "studio" as well, or maybe "inspector", I think these are more common terms for this kind of thing (database inspector).

**Comment by matijaSos** [comment]
Implemented with #120
