### ISSUE TITLE
In development, browser tab goes blank after file changes

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#84]
To reproduce: do some change in Wasp app, Wasp will recompile and generate new files, which will trigger nodemon and CRA, and when they are done browser tab with Wasp app will go blank.

It seems the cause of this is that when someting runs in parallel with CRA, CRA creates this empty tab -> probably because it finishes too soon and does not catch some of the changes? But actually it certainly does catch them because app is in correct state, it is just that browser tab got blank and needs reloading. In our case what is running in parallel is writing files -> CRA most likely triggers on very first file we write, but then we write a couple more files and those are problematic.
This problem has been described here actuallyi: https://github.com/facebook/create-react-app/issues/5809 .

I am not sure how we can fix this -> one way would be to make sure CRA does not trigger until we are done with writing all the files, but we don't have that level of control over CRA. We could stop it and start it again, but that seems wasteful and possibly slow. Maybe, same as for nodemon, we can set a delay via CLI parameters? That could solve this problem for some time. Or we could somehow make sure to trigger it one more time, once we write last file?
It might actually help if we understand better what is exactly causing the problem -> maybe we can make a PR on CRA and solve it not only for us but also for others who are running stuff in parallel with CRA and having this problem.

**Comment by Kamahl19** [comment]
@Martinsos isnt this fixed in v4? It started working for me in similar case

**Comment by Martinsos** [comment]
@Kamahl19 you are right, thank you for letting us know about this! I updated react-scripts to 4.0.0 and it seems to have solved the problem.
