### ISSUE TITLE
How I can use multiple registry?

### ISSUE THREAD

**Issue by hoanghiaquyen** [wasp-lang/wasp#853]
Because my company use private registry. So have some library I can't get it from registry. As me know, npm have config for that: npm i --registry=https://registry.npmjs.org

**Comment by Martinsos** [comment]
@hoanghiaquyen thanks for reachign out and sorry for missing this question previously!
Right now we don't have a capability for that, but will create an issue for it!
Just to check, have you somehow resolved it or just gave up on it?

**Comment by hoanghiaquyen** [comment]
Dear @Martinsos. Thank you for reply. Currently, I bypass it by edit file .npmrc. But I think it not best idea

**Comment by hoanghiaquyen** [comment]
I tried add .npmrc in main project but it not working. So I replaced in the file global of .npmrc. So I said it was a bad idea. I hope to find a better solution
