### ISSUE TITLE
Abstract email sending with Wasp (for e.g. email login)

### ISSUE THREAD

**Issue by matijaSos** [wasp-lang/wasp#870]
@vincanger had a good idea on how we could make it easier/possible for Wasp users to have email login and all the functionality that comes with it (reset password etc).

![vince_email_idea](https://user-images.githubusercontent.com/1536649/206162285-8fb26a86-8c98-465d-a525-4ab2114ef78d.png)

**Comment by vincanger** [comment]
This is in reference to passworldless (aka "one-time-password") login. Would be cool if they just supply their SMTP credentials, and we could input those into nodemailer for them.

**Comment by EmmanuelTheCoder** [comment]
@vincanger  is there any drawback with supplying SMTP credentials, especially regarding security?

**Comment by matijaSos** [comment]
closing as duplicate of #691
