### ISSUE TITLE
Improve Wasp IDE support for PSL

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#887]

**Comment by Martinsos** [comment]
Related to https://github.com/wasp-lang/wasp/issues/641 .

**Comment by Martinsos** [comment]
Couple more solutions:
1. Implement our own LSP functionality for psl powered entities in Wasp.
2. Implement our own DSL for entities, instead of using PSL, and then implement our own LSP support for that.
3. Maybe do something with vscode virtual file system.

**Comment by Martinsos** [comment]
Interesting to check out: Vue has Volar code extension. They have other languages embedded in their language (well they have xml/html which then some of it contains JS, some of it smth else) and what they do to provide proper IDE support for those is construct "fake" ("virtual", temporary) files on disk where they extract those languages -> for example one file containing Javascript -> and then do stuff on those files. Stuff like formatting, hints. Then they collect that info and apply it back to their file.

We could use this for Prisma -> we could construct prisma.schema file, run formatting and possibly even prisma LSP on it, and then apply that info in our file. We would need a bit of source mapping to correctly map it, of course.

So it might be worth checking out how are they doing it with Volar.

**Comment by Zeko369** [comment]
In the meantime [volar.js](https://volarjs.github.io/) became a separate project that can be used for other language extensions (i.e. Astro is using it [in the latest version](https://astro.build/blog/astro-260/#language-tool-improvements))

**Comment by Martinsos** [comment]
> In the meantime [volar.js](https://volarjs.github.io/) became a separate project that can be used for other language extensions (i.e. Astro is using it [in the latest version](https://astro.build/blog/astro-260/#language-tool-improvements))

Wooooooah that is amazing isn't it!? Oh man! This not only could solve our Prisma issues, but also allow us to possibly embed some JS which I always wanted (@sodic don't read this :D)!

Ok this is getting exciting!

**Comment by Martinsos** [comment]
This is now work in progress! @infomiho is working on this currently, and direction we took is taking PSL out of Wasp file and allowing them to use have their prisma.schema file. We will be parsing that file then so we keep the level of understanding we had so far.

**Comment by infomiho** [comment]
Completed in #2035
