### ISSUE TITLE
Update wasp version in wasp.cabal in every commit (when needed)?

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#892]
What do you think pplz about following:
Should we update the Wasp version (e.g. 0.7.0 to 0.8.0) in the wasp.cabal as we introduce changes? For example if we introduce a breaking change in our commit/PR, should we go bump the version in cabal in that same commit/PR? Or same for minor or patch. That means we would have to understand what our change did, of course, but also know the version of the last release, so we know where it needs to be after our commit. We are already trying to add entries to ChangeLog immediatelly.

Or we can continue doing it later -> when releasing, we figure out how big the changes are and we update the cabal version.

I am not sure what is normal practice. It does sound nice main actually having a correct version, and not old version, but that requires a bit of awareness from the dev and one more thing to think about, so maybe it is just too much work?

what I am thinking about is updating version in every commit.
Similar to how it was asked here: https://softwareengineering.stackexchange.com/questions/278538/incrementing-version-during-development-or-after-release .
So for example if last released version was 0.7.1, and we introduced a breaking change on main in the meantime (which is our dev branch), and I try running that code on the Wasp code that requires 0.7 version of Wasp, I would want wasp CLI to realize I am using it with the wrong version! It can't do that unless it knows it is not 0.7.1 anymore, but is 0.8.0.
So probably we should be updating Wasp version as we go, on every commit when update is needed.

**Comment by Martinsos** [comment]
Right now I think we should introduce it as a practice, and after every commit make sure to update Wasp version and Changelog if needed.

We can do this by having PR template that asks you if you updated ChangeLog and if you updated wasp.cabal version!

**Comment by sodic** [comment]
I remember us talking about this. What did we decide in the end?

**Comment by Martinsos** [comment]
We didn't decide anything! I made a proposal above, to update Wasp version in cabal, and also Changelog, in the commit that makes these changes, and we could enforce this via PR template.
I would be ok with giving that a try, if the rest agrees.

**Comment by Martinsos** [comment]
Ok, we decided to change it in every PR!
