### ISSUE TITLE
signUp action from TODO example injects User although it doesn't use it directly

### ISSUE THREAD

**Issue by matijaSos** [wasp-lang/wasp#90]
See code here: https://github.com/wasp-lang/wasp/blob/master/waspc/examples/todoApp/todoApp.wasp#L82

```
------ todoApp.wasp
action signUp {
  fn: import { signUp } from "@ext/actions.js",
  entities: [User]
}

------ ext/actions.js
export const signUp = async (args, context) => {
  await createNewUser({ email: args.email, password: args.password })
}
```

As stated in the title, this is the case where we inject User to the action function but then it doesn't use it directly, because it uses `createNewUser()` function provided by Wasp auth module. Wasper could have omitted `entities: [User]` declaration from the action declaration and everything would compile, but the problem is that then Wasp wouldn't be aware that this action changes User entity (creates new one) so then it can't update the query caches accordingly.

So the way it is now Wasper has to remember to declare that the action is affecting certain entity although it doesn't use it directly - this is extra mental work for Wasper and could result in errors.

We should think what is the solution we want to achieve here. Maybe supporting composability of the actions would be a solution - e.g. if `signUp` action uses `createNewUser` (e.g. it could inject it as well) action which changes `User`, then we can know that `signUp` action also changes user, although it is not explicitly declared.

**Comment by infomiho** [comment]
@matijaSos can we close this?

**Comment by Martinsos** [comment]
createNewUser doesn't exist any more, but the issue of possibly action doing something on an entity that isn't injected still exists -> but I believe we have another issue for handling that, so yup I will close this one!
