### ISSUE TITLE
Remove duplication for app routes

### ISSUE THREAD

**Issue by sodic** [wasp-lang/wasp#941]
When performing a redirect in Wasp, you have to specify the route as a string (something like `history.push('/someroute')`). There are no checks for whether this route is defined in a `.wasp` file.

It would be nice to remove this duplication:
- Specify all the routes only once (inside the Wasp file)
- Import them into the code using automatically generated symbols (variables).

Very rough outline (just to demonstrate the idea):
```javascript
import { Route } from '@wasp/routes'

history.push(Route.someRoute)
```

**Comment by Martinsos** [comment]
@infomiho would this be covered, or at least connected, with your Typesafe routes (Link)?

**Comment by infomiho** [comment]
Yes, we could also export the Routes object with all the routes as well as a custom `<Link>` component.

**Comment by infomiho** [comment]
We now support this since #1235
