### ISSUE TITLE
[examples/Waspello] Text protrudes out of the card when too long to fit

### ISSUE THREAD

**Issue by matijaSos** [wasp-lang/wasp#942]
Here's the screenshot of the problem:

![Screenshot 2023-01-09 at 14 36 02](https://user-images.githubusercontent.com/1536649/211321235-36e92e32-d1e1-40b9-a5a7-8ce47961e934.png)

This worked until I switched to Tailwind CSS and enabled their Preflight CSS which "resets" a lot of the default settings for HTML elements. Probably this is a simple fix, just need to figure out what exactly got messed up and add a missing class.

This would also make a great first issue for new Wasp contributors!

**Comment by MuhammadAakash** [comment]
Hi @matijaSos 
I would like to work on this issue.

**Comment by matijaSos** [comment]
> 

Of course! Let us know if you have any issues getting started.

**Comment by MuhammadAakash** [comment]
@matijaSos 
Sure

**Comment by koyaboy** [comment]
Hi @matijaSos , this looks like something I can handle but to be frank, I'm new to open source and this is slightly overwhelming for me. Could you point me in the right direction of where to start or approach dealing with this issue ?

**Comment by Skar3Krow** [comment]
Hello @matijaSos I would like to contribute to this issue !!

**Comment by Martinsos** [comment]
Sure @Skar3Krow go for it!

**Comment by Vivek-1102** [comment]
Hey @matijaSos Vivek here need to do my first open source contribution for wasp by fixing this issue

**Comment by Vivek-1102** [comment]
@matijaSos can you tell me the exact page where you are seeing this error

**Comment by Martinsos** [comment]
Hey @Vivek-1102 , sure, here is the example app in question: https://github.com/wasp-lang/wasp/tree/main/examples/waspello -> so if you run it and create a card with big text, you will see the problem!

**Comment by Vivek-1102** [comment]
Hey @matijaSos really sorry for such a long wait i think i have successfully found the solution for the above issue but i need a help for setting the waspello project locally . If you dont mind helping and if you really got any time it will great hearing from you.

Problems : 
 1. Could not run the wasp start db command

**Comment by Vivek-1102** [comment]
Is somehow possible to run the app without docker container?

**Comment by Martinsos** [comment]
Nope, you need Docker for that one! Is installing docker an issue for you?
You can also not use `wasp start db` and just set up your own postgres db if you want, by installing postgres on your machine and setting it up there.

**Comment by Vivek-1102** [comment]
yeah i understand but i am not used to docker i somehow need help with the docker part rest i can do on my own 
1. I have installed docker
2. installed postgres
3. Generated Google client and secret

**Comment by Vivek-1102** [comment]
@matijaSos just suggest me some video which will help me learn the dockerized app

**Comment by Martinsos** [comment]
Which step exactly are you struggling with? YOu don't need to know much about docker -> it is required only to run `wasp db start`. Once you have Docker installed and configured, that is it, you don't have to use it directly.
The rest of app doesn't run inside Docker.
As for videos: I don't have any special recommendation, your google effort is as good as mine here!

**Comment by Vivek-1102** [comment]
I have installed docker and then pulled postgres image from docker hub
What next?

**Comment by Vivek-1102** [comment]
Hey @matijaSos will you please review my PR above
