### ISSUE TITLE
Allow adding NPM dependencies from CLI

### ISSUE THREAD

**Issue by shayneczyzewski** [wasp-lang/wasp#949]
Right now, when adding NPM decencies, users must go look up the current version.

It would be nice if it behaved like `npm install foo` and it adds the latest version to `package.json`. Ours could be something like `wasp install foo` and adds the latest version to your .wasp file.

**Comment by Martinsos** [comment]
Might depend on #734, we should wait a bit for it to progress before we continue with this.

**Comment by infomiho** [comment]
Done since 0.12.0
