### ISSUE TITLE
Do not perform migration check/produce warning output when running `wasp build`

### ISSUE THREAD

**Issue by shayneczyzewski** [wasp-lang/wasp#968]
If you run `wasp build`, you will see output like the following:
![Screenshot_20230123_101120.png](https://images.zenhubusercontent.com/61a787e2a470ed4096d83e22/401b243e-c45a-4ea3-b450-e4def06d53ae)

The `stderr` output about a `DATABASE_URL` and not being able to connect is confusing since it seems to imply something is wrong, but the build actually succeeded here. It was just caused by a check we should not be making when building.

When we run `wasp build`, it in turn calls the following chain of functions:
- Build.buildIO
- Compile.compileIOWithOptions
- Lib.compile
- Lib.generateCode
- Generator.writeWebAppCode
- Setup.runSetup
- Setup.setupDatabase
- DbGenerator.postWriteDbGeneratorActions

In this final step, we run `warnIfDbNeedsMigration`: https://github.com/wasp-lang/wasp/blob/main/waspc/src/Wasp/Generator/DbGenerator.hs#L86

We do not need to do this when building. The trick will be though how can we cleanly not do this _just for build_, but hopefully without passing some flag down 8 function calls :)

**Comment by Martinsos** [comment]
Same as #1152 so closing it!
