### ISSUE TITLE
[Wasp CLI] Allow starting new project from different templates

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#984]
Right now, you can do `wasp new MyApp` and you get a new app that is bare bones, just one route and page.

What would be cool is if we offered different templates, for example: "blog template", "app with auth template", "app with jobs and auth template", ... .

We don't need to ship these bundled with CLI as we do right now for the "new" app -> we could instead have them on our GH repo and then Wasp would just pull the correct one and copy it to the local directory of the user. @infomiho had a nice command for doing that, by using `gitget` npm package. Even the "new" app could then be on the GH repo. It could even allow people to create their own templates and reference them.

Main task here is creating these nice template apps, then pulling them via Wasp CLI is just a mechanism of delivery, in theory they could git clone them directly if they wish.

**Comment by Martinsos** [comment]
Alterantive is better support for scaffolding, be it on starting new app or later, related issue here: https://github.com/wasp-lang/wasp/issues/606 .

**Comment by infomiho** [comment]
Just for reference the `gitget` command (used by Astro internally for their needs):

```bash
npx gitget wasp-lang/wasp/examples/tutorials/TodoApp TodoApp
```

**Comment by infomiho** [comment]
Closed via https://github.com/wasp-lang/wasp/pull/1105
