### ISSUE TITLE
Allow operations (actions and queries) to opt out of `auth` middleware on server

### ISSUE THREAD

**Issue by Martinsos** [wasp-lang/wasp#99]
Right now, if `auth` feature is used, all actions and queries have `auth` middleware in front of them.

But, this is problematic in some situations, for example if you have `signUp` action that calls `createNewUser`, it will get rejected with 401 if JWT token is wrong. Which makes sense, but we actually want `signUp` to succed in situation like this, because how are we going to fix that JWT token otherwise? So, what we really want is for `signUp` to not require authentication, which makes sense, but, we don't have that right now as an option.

This should probably work smth like this:
```
action signUp {
  fn: import { signUp } from "@ext/actions.js",
  entities: [User],
  auth: false
}
```
and in this case `auth` middleware should not be applied on server on this action.

I am marking this as enhancement because that is what it is, but also as bug because it actually limits user severly in situation like this and manifests as kind of a bug.

Draft:
1. Update Wasp/Query.hs and Wasp/Action.hs to have `auth :: Bool` field.
2. Update Parser/Operation.hs to correctly parse the `auth` property.
3. In ServerGenerator, update operations generation to not put `auth` middleware on operations that have `auth` specified as `False`.

**Comment by saatvikshah** [comment]
Could this issue be assigned to me?

**Comment by saatvikshah** [comment]
Shouldn't it be `auth: Maybe Bool`, so that if `auth` is not specified we authenticate by default?

**Comment by Martinsos** [comment]
Sure, go for it!
Yes, if it is not specified it should be "true". Or we could have "Maybe Bool". Not sure what is better hm.
