### ISSUE TITLE
No thumbnail for wasp-lang.dev

### ISSUE THREAD

**Issue by matijaSos** [wasp-lang/wasp#995]
When we share the url to wasp-lang.dev on e.g. twitter or LinkedIn, it turns up with an empty thumbnail:

<img width="526" alt="Screenshot 2023-02-07 at 09 42 57" src="https://user-images.githubusercontent.com/1536649/217597852-49cdf5a1-1358-4fff-822d-8790d4c1162e.png">

We could probably use some Docusaurus metadata properties to provide a thumbnail image, like we do for blog posts.

**Comment by programmersoham** [comment]
Are you referring to this? @matijaSos 
![image](https://user-images.githubusercontent.com/54547662/223360614-82d3f4d0-adfb-46ab-8a9b-8bdec742c3b5.png)

**Comment by programmersoham** [comment]
The wasp logo is mentioned in the metadata in docs website source.
![image](https://user-images.githubusercontent.com/54547662/223361680-f1ed9421-c493-40a4-96a3-e211472710ce.png)

**Comment by matijaSos** [comment]
@programmersoham yes, something like that! It might be that this is defined for the docs but not for the landing page. What is the file you were checking out above?

**Comment by infomiho** [comment]
Finished by https://github.com/wasp-lang/wasp/pull/1434/files
