### ISSUE TITLE
Wasp CLI crashes on M1 Mac running Ventura when you make edits to an entity while running `start`

### ISSUE THREAD

**Issue by shayneczyzewski** [wasp-lang/wasp#999]
**Describe the bug**
Wasp CLI crashes on M1 Mac running Ventura when you make edits to an entity while running `start`. **This only happens on an M1 + Ventura configuration. It does not happen on older versions of Macs, nor on Linux.**

I will do a bit more digging to see the exact line, and see if swapping to strict IO helps.

**To Reproduce**
1. `wasp clean`
2. `wasp start` (leave running)
3. Add a property to an entity, hit save
4. Remove the property, hit save
5. Do this a few times until you see: `Db: wasp-bin: /Users/shayne/dev/wasp/examples/tutorials/TodoApp/.wasp/out/db/schema.prisma.wasp-generate-checksum: openFile: resource busy (file is locked)` (only takes 1 or 2 saves for me)

**Expected behavior**
Do not die.

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.2
 - Version: any version of Wasp

**Comment by Martinsos** [comment]
This must be due to lazy evaluation!

https://stackoverflow.com/questions/5053135/resource-busy-file-is-locked-error-in-haskell

So we need to figure out where are we writing to a file that we are still reading! But there are not many files that we both write to and read from, right? Most of them we just read, or just write. I think we do both only with some of those meta files in the generated code? Maybe wasp checksums file, or something like that? So I would search for files that we both read and write and ensure that we don't try to write while still in the process of lazily reading it.

**Comment by shayneczyzewski** [comment]
> This is most likely due to lazy evaluation!
> 
> https://stackoverflow.com/questions/5053135/resource-busy-file-is-locked-error-in-haskell
> 
> So we need to figure out where are we writing to a file that we are still reading! But there are not many files that we both write to and read from, right? Most of them we just read, or just write. I think we do both only with some of those meta files in the generated code? Maybe wasp checksums file, or something like that? So I would search for files that we both read and write and ensure that we don't try to write while still in the process of lazily reading it.

Yes, it seems so. But it doesn't make sense it is specific to a version of an OS or chip architecture. You would think it should fail across the board, which it does not. But we can probably patch it up anyways.

**Comment by Martinsos** [comment]
> > This is most likely due to lazy evaluation!
> > https://stackoverflow.com/questions/5053135/resource-busy-file-is-locked-error-in-haskell
> > So we need to figure out where are we writing to a file that we are still reading! But there are not many files that we both write to and read from, right? Most of them we just read, or just write. I think we do both only with some of those meta files in the generated code? Maybe wasp checksums file, or something like that? So I would search for files that we both read and write and ensure that we don't try to write while still in the process of lazily reading it.
> 
> Yes, it seems so. But it doesn't make sense it is specific to a version of an OS or chip architecture. You would think it should fail across the board, which it does not. But we can probably patch it up anyways.

That is weird. Maybe some default behaviour of OS changed in some way, or some IO operations of OS are better optimized or smth so it actually uses the Haskell capabilities better and it comes to situation that wasn't happening before?

I do hope still that it is just our mistake in how we do reads / writes.
If not, it might be that it is either bug in Haskell IO, or in the OS.
